/* Supabase-backed administration UI. Authorization is enforced by Auth and database RLS. */
const reviewStatuses=new Set(['pending','published','rejected','removed']);
const readReviews=()=>((Array.isArray(get('dge-reviews',[]))?get('dge-reviews',[]):[])).map(r=>({...r,reviewerId:r.reviewerId||r.authorEmail||'',reviewedUserId:r.reviewedUserId||r.target||'',comment:r.comment??r.text??'',status:reviewStatuses.has(r.status)?r.status:'pending'}));
const putReviews=x=>set('dge-reviews',x);
const acct=()=>get('dge-accounts',[]);
const jobBy=id=>jobs.find(j=>j.id===id);
const who=id=>acct().find(a=>a.email===id)?.name||get('dge-workers',[]).find(w=>w.owner===id)?.name||id||'მომხმარებელი';
function reviewEligibility(reviewerId,jobId,reviewedUserId,excludeReviewId=null){const job=jobBy(jobId),duplicate=readReviews().some(review=>review.jobId===jobId&&review.reviewerId===reviewerId&&review.id!==excludeReviewId);const checks=[!!job,job?.status==='completed',!!reviewerId&&!!reviewedUserId&&reviewerId!==reviewedUserId,!duplicate];return{job,ok:checks.every(Boolean),checks}}
function canUserReviewJob(uid,jid,target){return reviewEligibility(uid,jid,target).ok}
function hasReviewedJob(jid,uid){return readReviews().some(r=>r.jobId===jid&&r.reviewerId===uid)}
function createReview({jobId,reviewerId,reviewedUserId,rating,comment}){if(user?.email!==reviewerId)throw Error('შეფასებისთვის ანგარიშზე შესვლა აუცილებელია.');if(!Number.isInteger(Number(rating))||rating<1||rating>5)throw Error('აირჩიე 1-დან 5 ვარსკვლავამდე შეფასება.');if(!canUserReviewJob(reviewerId,jobId,reviewedUserId))throw Error('შეფასების დატოვების უფლება ამ სამუშაოზე არ გაქვს.');const rows=readReviews();if(rows.some(r=>r.jobId===jobId&&r.reviewerId===reviewerId))throw Error('ამ სამუშაოზე შეფასება უკვე დატოვებულია.');const r={id:'review-'+Date.now(),jobId,reviewerId,reviewedUserId,rating:Number(rating),comment:String(comment||'').trim(),status:'pending',createdAt:Date.now(),updatedAt:Date.now(),reportCount:0,reportedBy:[]};rows.unshift(r);putReviews(rows);return r}
function publicReviews(id){return readReviews().filter(r=>r.reviewedUserId===id&&r.status==='published')}
function reviewSummary(id){const rows=publicReviews(id);return{rows,count:rows.length,average:rows.length?rows.reduce((n,r)=>n+Number(r.rating),0)/rows.length:0}}
function completedCount(id){return jobs.filter(job=>job.status==='completed'&&job.owner===id).length}
function compactRating(id){const s=reviewSummary(id);return s.count?'<div class="rating-inline">⭐ '+s.average.toFixed(1)+' · '+s.count+' შეფასება · '+completedCount(id)+' დასრულებული სამუშაო</div>':'<div class="rating-inline rating-empty">შეფასებები ჯერ არ აქვს</div>'}
function reviewSection(id){const s=reviewSummary(id);return '<section class="reviews-section"><h3>შეფასებები '+(s.count?'⭐ '+s.average.toFixed(1)+' · '+s.count:'')+'</h3>'+(s.count?s.rows.map(r=>'<article class="review-item"><div class="review-stars">'+starString(r.rating)+'</div>'+(r.comment?'<p>„'+esc(r.comment)+'“</p>':'')+'<small>— '+esc(who(r.reviewerId))+' · '+esc(timeAgo(r.createdAt))+'</small><button class="report-link" data-report-review="'+esc(r.id)+'">🚩 შეფასების დარეპორტება</button></article>').join(''):'<div class="notice">შეფასებები ჯერ არ აქვს</div>')+'</section>'}
const adminLog=(action,type,id,note='')=>{const a=get('dge-admin-activity',[]);a.unshift({id:'log-'+Date.now(),adminId:user?.email,action,targetType:type,targetId:id,createdAt:Date.now(),note});set('dge-admin-activity',a)};
function adminShell(tab,body){const links=[['overview','📊 მიმოხილვა','/admin'],['users','👥 მომხმარებლები','/admin/users'],['jobs','📋 განცხადებები','/admin/jobs'],['reviews','⭐ შეფასებები','/admin/reviews'],['reports','🚨 რეპორტები','/admin/reports'],['settings','⚙️ პარამეტრები','/admin/settings']];return '<section class="admin-page"><header class="admin-top"><button class="admin-menu-toggle" data-admin-menu>☰</button><div><span class="eyebrow">ადმინისტრირება</span><h1>ადმინ პანელი</h1></div><div class="admin-user">'+esc(user?.email||'')+' <a class="btn btn-secondary btn-small" href="#/">საიტზე გადასვლა</a><button class="btn btn-secondary btn-small" data-logout>გასვლა</button></div></header><div class="admin-layout"><nav class="admin-sidebar" data-admin-sidebar>'+links.map(x=>'<a class="'+(x[0]===tab?'active':'')+'" href="#'+x[2]+'">'+x[1]+'</a>').join('')+'</nav><main class="admin-content">'+body+'</main></div></section>'}
function activityList(){const rows=get('dge-admin-activity',[]);return rows.length?rows.slice(0,10).map(a=>'<p class="admin-activity-row"><b>'+esc(a.action)+'</b> · '+esc(a.targetType)+' '+esc(a.targetId)+' · '+new Date(a.createdAt).toLocaleString('ka-GE')+'</p>').join(''):'<div class="admin-empty">აქტივობა ჯერ არ არის.</div>'}
function adminOverview(){const users=acct(),pending=readReviews().filter(r=>r.status==='pending').length,reports=get('dge-reports',[]).filter(r=>(r.status||'new')==='new').length,stats=[['👥 მომხმარებლები',users.length,'/admin/users'],['📋 აქტიური განცხადებები',jobs.filter(j=>(j.status||'active')==='active').length,'/admin/jobs?status=active'],['📋 ყველა განცხადება',jobs.length,'/admin/jobs'],['⭐ შეფასებები',readReviews().length,'/admin/reviews'],['⭐ მოლოდინში შეფასებები',pending,'/admin/reviews?status=pending'],['🚨 ახალი რეპორტები',reports,'/admin/reports?status=new'],['✅ დასრულებული სამუშაოები',jobs.filter(j=>j.status==='completed').length,'/admin/jobs?status=completed']];return adminShell('overview','<h2>მიმოხილვა</h2><p>პლატფორმის მიმდინარე მონაცემები.</p><div class="admin-stat-grid">'+stats.map(s=>'<a class="admin-stat" href="#'+s[2]+'"><span>'+s[0]+'</span><strong>'+s[1]+'</strong></a>').join('')+'</div><section class="admin-panel"><h3>ბოლო აქტივობა</h3>'+activityList()+'</section>')}
function reviewCard(r){const j=jobBy(r.jobId),rel=reviewEligibility(r.reviewerId,r.jobId,r.reviewedUserId,r.id);return '<article class="admin-review-card"><div class="admin-review-top"><b>'+starString(r.rating)+' · '+r.rating+'/5</b><span class="admin-status status-'+r.status+'">'+({pending:'მოლოდინში',published:'გამოქვეყნებული',rejected:'უარყოფილი',removed:'წაშლილი'}[r.status])+'</span></div><p>'+esc(who(r.reviewerId))+' → '+esc(who(r.reviewedUserId))+'</p><p>განცხადება: '+esc(j?.title||'ვერ მოიძებნა')+' · '+esc(r.jobId)+'</p><p>'+esc(r.comment||'კომენტარი არ არის')+'</p>'+(!rel.ok?'<p class="error-msg">შეფასების კავშირი გადამოწმებას საჭიროებს.</p>':'')+'<div class="admin-actions"><button class="btn btn-secondary btn-small" data-review-view="'+esc(r.id)+'">ნახვა</button>'+(r.status==='pending'?'<button class="btn btn-primary btn-small" data-review-status="published" data-id="'+esc(r.id)+'">გამოქვეყნება</button><button class="btn btn-secondary btn-small" data-review-status="rejected" data-id="'+esc(r.id)+'">უარყოფა</button>':'')+(r.status==='published'?'<button class="btn btn-secondary btn-small" data-review-status="removed" data-id="'+esc(r.id)+'">წაშლა</button>':'')+'</div></article>'}
function adminReviews(){const p=new URLSearchParams(location.hash.split('?')[1]||''),tab=p.get('status')||'all',tabs=[['all','ყველა'],['pending','მოლოდინში'],['published','გამოქვეყნებული'],['rejected','უარყოფილი'],['removed','წაშლილი']],rows=readReviews().filter(r=>tab==='all'||r.status===tab);return adminShell('reviews','<h2>⭐ შეფასებები</h2><div class="admin-tabs">'+tabs.map(t=>'<a class="'+(t[0]===tab?'active':'')+'" href="#/admin/reviews'+(t[0]==='all'?'':'?status='+t[0])+'">'+t[1]+'</a>').join('')+'</div>'+(rows.length?'<div class="admin-review-list">'+rows.map(reviewCard).join('')+'</div>':'<div class="admin-empty">'+(tab==='pending'?'მოლოდინში შეფასებები არ არის.':'შეფასებები ჯერ არ არის.')+'</div>'))}
function adminUsers(){const p=new URLSearchParams(location.hash.split('?')[1]||''),q=(p.get('q')||'').toLowerCase(),role=p.get('role')||'all',rows=acct().filter(a=>(role==='all'||a.role===role)&&(!q||(a.name+' '+a.email+' '+(a.phone||'')).toLowerCase().includes(q)));return adminShell('users','<h2>👥 მომხმარებლები</h2><form class="admin-search" id="admin-user-search"><input name="q" placeholder="მოძებნე სახელი, ელფოსტა ან ტელეფონი" value="'+esc(q)+'"><button class="btn btn-primary btn-small">ძებნა</button></form><div class="admin-tabs">'+[['all','ყველა'],['worker','სამუშაოს მაძიებლები'],['employer','დამსაქმებლები'],['both','ორივე'],['admin','ადმინისტრატორები']].map(t=>'<a href="#/admin/users?role='+t[0]+'&q='+encodeURIComponent(q)+'" class="'+(role===t[0]?'active':'')+'">'+t[1]+'</a>').join('')+'</div>'+(rows.length?'<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>სახელი</th><th>ელფოსტა</th><th>ტელეფონი</th><th>როლი</th><th>რეიტინგი</th><th>დასრულებული</th><th>სტატუსი</th></tr></thead><tbody>'+rows.map(a=>'<tr><td class="admin-user-name">'+Avatar(a,'sm')+esc(a.name||'—')+'</td><td>'+esc(a.loginEmail||(String(a.email||'').includes('@')?a.email:'—'))+'</td><td>'+esc(a.phone||'—')+'</td><td>'+esc(a.role||'worker')+'</td><td>'+compactRating(a.email)+'</td><td>'+completedCount(a.email)+'</td><td>'+esc(a.status||'აქტიური')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="admin-empty">მომხმარებლები ვერ მოიძებნა.</div>'))}
function adminJobs(){const p=new URLSearchParams(location.hash.split('?')[1]||''),requested=p.get('status')||'all',allowed=['all','active','in_progress','completed','cancelled'],status=allowed.includes(requested)?requested:'all',rows=jobs.filter(job=>status==='all'||(job.status||'active')===status),tabs=[['all','ყველა'],['active','აქტიური'],['in_progress','პროცესში'],['completed','დასრულებული'],['cancelled','გაუქმებული']],header='<thead><tr><th>განცხადება</th><th>დამსაქმებელი</th><th>მდებარეობა</th><th>თარიღი</th><th>ანაზღაურება</th><th>სტატუსი</th></tr></thead>',body=rows.map(job=>'<tr><td>'+esc(job.title)+'<small>'+esc(job.category)+'</small></td><td>'+esc(job.name||who(job.owner))+'</td><td>'+esc(job.city+', '+job.area)+'</td><td>'+esc(job.date||'—')+'</td><td>'+esc(job.paymentAmount??job.pay??'შეთანხმებით')+' ₾</td><td>'+esc(statusText(job.status||'active'))+'</td></tr>').join('');return adminShell('jobs','<h2>📋 განცხადებები</h2><div class="admin-tabs">'+tabs.map(tab=>'<a class="'+(status===tab[0]?'active':'')+'" href="#/admin/jobs?status='+tab[0]+'">'+tab[1]+'</a>').join('')+'</div>'+(rows.length?'<div class="admin-table-wrap"><table class="admin-table">'+header+'<tbody>'+body+'</tbody></table></div>':'<div class="admin-empty">განცხადებები ვერ მოიძებნა.</div>'))}
function adminReports(){const p=new URLSearchParams(location.hash.split('?')[1]||''),tab=p.get('status')||'all',a=get('dge-reports',[]).map(r=>({...r,kind:'job',status:r.status||'new'})),b=get('dge-review-reports',[]).map(r=>({...r,kind:'review',status:r.status||'new'})),rows=[...a,...b].filter(r=>tab==='all'||r.status===tab);return adminShell('reports','<h2>🚨 რეპორტები</h2><div class="admin-tabs">'+[['all','ყველა'],['new','ახალი'],['reviewed','განხილული'],['closed','დახურული']].map(t=>'<a href="#/admin/reports?status='+t[0]+'" class="'+(tab===t[0]?'active':'')+'">'+t[1]+'</a>').join('')+'</div>'+(rows.length?'<div class="admin-review-list">'+rows.map(r=>'<article class="admin-review-card"><b>'+(r.kind==='review'?'რეპორტი შეფასებაზე':'განცხადების / მომხმარებლის რეპორტი')+'</b><p>'+esc(r.reason)+' · '+esc(r.description||'')+'</p><small>'+esc(r.reporterId||r.reportingUser||'ანონიმური')+'</small><div class="admin-actions"><button class="btn btn-secondary btn-small" data-report-state="'+r.kind+'" data-id="'+esc(r.id)+'" data-state="reviewed">განხილულად მონიშვნა</button><button class="btn btn-secondary btn-small" data-report-state="'+r.kind+'" data-id="'+esc(r.id)+'" data-state="closed">დახურვა</button></div></article>').join('')+'</div>':'<div class="admin-empty">'+(tab==='new'?'ახალი რეპორტები არ არის.':'რეპორტები ჯერ არ არის.')+'</div>'))}
function adminSettings(){return adminShell('settings','<h2>⚙️ პარამეტრები</h2><section class="admin-panel"><h3>ადმინისტრირების ჟურნალი</h3>'+activityList()+'<p>მონაცემები და უფლებები დაცულად იმართება Supabase-ის მეშვეობით.</p></section>')}
function adminView(path){if(!user){sessionStorage.setItem('dge-return','#'+location.hash.slice(1));location.hash='#/login';return true}if(user.role!=='admin'){app.innerHTML='<section class="container"><div class="admin-denied"><h2>ამ გვერდზე წვდომა არ გაქვს.</h2><a href="#/" class="btn btn-primary">მთავარ გვერდზე დაბრუნება</a></div></section>';return true}app.innerHTML=path==='/admin'?adminOverview():path==='/admin/users'?adminUsers():path==='/admin/jobs'?adminJobs():path==='/admin/reviews'?adminReviews():path==='/admin/reports'?adminReports():adminSettings();accountNavigation();return true}
const previousAdminRoute=routeView;routeView=function(){let path=(location.hash||'#/').split('?')[0].slice(1);if(path==='/admin'||path.startsWith('/admin/')){adminView(path);window.scrollTo(0,0);return}previousAdminRoute();if(path==='/login'&&user?.role==='admin'){location.hash='#/admin';return}if(path==='/dashboard'&&user?.role==='admin')location.hash='#/admin';accountNavigation()};render=routeView;routeView();
const baseProfileView=profilePage;profilePage=function(){return user?.role==='admin'?layout('ადმინისტრატორის ანგარიში','ადმინისტრატორის როლი დაცულია.','<div class="notice">ადმინისტრატორის როლი პროფილის ფორმიდან ვერ შეიცვლება.</div>'):baseProfileView()};
const baseAccountNav=accountNavigation;accountNavigation=function(){baseAccountNav();if(user?.role==='admin')document.querySelector('[data-account-dropdown]')?.insertAdjacentHTML('afterbegin','<a href="#/admin">⚙️ ადმინ პანელი</a>')};
document.addEventListener('click',event=>{
 const action=event.target.closest('[data-review-status]');if(action){if(user?.role!=='admin')return;const rows=readReviews(),review=rows.find(row=>row.id===action.dataset.id),state=action.dataset.reviewStatus;if(!review)return;if(state==='published'&&!reviewEligibility(review.reviewerId,review.jobId,review.reviewedUserId,review.id).ok){notify('შეფასების მონაცემები გადამოწმებას საჭიროებს.');return}if(state==='removed'&&!confirm('დარწმუნებული ხარ, რომ გსურს ამ შეფასების წაშლა?'))return;const note=state==='published'?'':(prompt('უარყოფის მიზეზი (არასავალდებულო)')||'');review.status=state;review.adminNote=note;review.updatedAt=Date.now();putReviews(rows);adminLog(state==='published'?'შეფასება გამოქვეყნდა':state==='rejected'?'შეფასება უარყოფილია':'შეფასება წაიშალა','review',review.id,note);routeView();return}
 const menu=event.target.closest('[data-admin-menu]');if(menu){document.querySelector('[data-admin-sidebar]')?.classList.toggle('open');return}
 const report=event.target.closest('[data-report-state]');if(report){if(user?.role!=='admin')return;const key=report.dataset.reportState==='review'?'dge-review-reports':'dge-reports',rows=get(key,[]),row=rows.find(item=>item.id===report.dataset.id);if(row){row.status=report.dataset.state;set(key,rows);adminLog('რეპორტის სტატუსი შეიცვალა','report',row.id,row.status);routeView()}return}
 const view=event.target.closest('[data-review-view]');if(view){const review=readReviews().find(row=>row.id===view.dataset.reviewView);if(!review)return;const relation=reviewEligibility(review.reviewerId,review.jobId,review.reviewedUserId,review.id),job=jobBy(review.jobId),checks=['განცხადება არსებობს','განცხადება დასრულებულია','მომხმარებლები განსხვავდებიან','დუბლირებული შეფასება არ არსებობს'];app.insertAdjacentHTML('beforeend','<div class="admin-detail-modal" data-detail><section class="admin-detail-card"><button class="modal-close" data-detail-close>×</button><h2>შეფასების დეტალები</h2><p>შემფასებელი: '+esc(who(review.reviewerId))+' · '+esc(review.reviewerId)+'</p><p>შეფასებული: '+esc(who(review.reviewedUserId))+' · '+esc(review.reviewedUserId)+'</p><p>განცხადება: '+esc(job?.title||'ვერ მოიძებნა')+' · '+esc(job?.city||'')+' '+esc(job?.area||'')+' · '+esc(job?.date||'')+' · '+esc(statusText(job?.status||'active'))+'</p><p>'+starString(review.rating)+' · '+esc(review.comment)+'</p><h3>შეფასების მონაცემები</h3>'+checks.map((text,index)=>'<p class="'+(relation.checks[index]?'verify-ok':'verify-bad')+'">'+(relation.checks[index]?'✓':'⚠')+' '+text+'</p>').join('')+'</section></div>');return}
 if(event.target.closest('[data-detail-close]'))event.target.closest('[data-detail]')?.remove()
},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-report-review]');if(!b)return;if(!user){notify('რეპორტისთვის ანგარიშზე შესვლა აუცილებელია.');return}const reason=prompt('მიზეზი: შეურაცხმყოფელი შინაარსი, ყალბი ინფორმაცია, სპამი, შეუსაბამო შინაარსი ან სხვა');if(!reason)return;let rows=get('dge-review-reports',[]);if(rows.some(r=>r.reviewId===b.dataset.reportReview&&r.reporterId===user.email)){notify('ამ შეფასებაზე რეპორტი უკვე გაგზავნილია.');return}rows.unshift({id:'rr-'+Date.now(),reviewId:b.dataset.reportReview,reporterId:user.email,reason,description:'',createdAt:Date.now(),status:'new'});set('dge-review-reports',rows);notify('რეპორტი გაიგზავნა. მადლობა.')});

// Public helpers kept together for the future API/service adapter.
function getReviewsForUser(id){return readReviews().filter(r=>r.reviewedUserId===id)}
function getPublishedReviewsForUser(id){return publicReviews(id)}
function getPendingReviews(){return readReviews().filter(r=>r.status==='pending')}
function updateReviewStatus(id,status,note=''){if(user?.role!=='admin')throw Error('ამ მოქმედების უფლება არ გაქვს.');if(!reviewStatuses.has(status))throw Error('შეფასების სტატუსი არასწორია.');const rows=readReviews(),r=rows.find(x=>x.id===id);if(!r)throw Error('შეფასება ვერ მოიძებნა.');r.status=status;r.adminNote=String(note||'').trim();r.updatedAt=Date.now();putReviews(rows);adminLog(status==='published'?'შეფასება გამოქვეყნდა':status==='rejected'?'შეფასება უარყოფილია':'შეფასება წაიშალა','review',id,r.adminNote);return r}
function reportReview(id,reason,description=''){if(!user)throw Error('რეპორტისთვის ანგარიშზე შესვლა აუცილებელია.');if(!publicReviews(readReviews().find(r=>r.id===id)?.reviewedUserId||'').some(r=>r.id===id))throw Error('შეფასება ვერ მოიძებნა.');const rows=get('dge-review-reports',[]);if(rows.some(r=>r.reviewId===id&&r.reporterId===user.email))throw Error('ამ შეფასებაზე რეპორტი უკვე გაგზავნილია.');const report={id:'rr-'+Date.now(),reviewId:id,reporterId:user.email,reason,description:String(description||'').trim(),createdAt:Date.now(),status:'new'};rows.unshift(report);set('dge-review-reports',rows);return report}

document.addEventListener('click',e=>{const b=e.target.closest('[data-report-review]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(!user){notify('რეპორტისთვის ანგარიშზე შესვლა აუცილებელია.');return}const reason=prompt('მიზეზი: შეურაცხმყოფელი შინაარსი, ყალბი ინფორმაცია, სპამი, შეუსაბამო შინაარსი ან სხვა');if(!reason)return;try{reportReview(b.dataset.reportReview,reason);notify('რეპორტი გაიგზავნა. მადლობა.')}catch(err){notify(err.message)}},true);
// Use real local records for the dashboard activity feed, in addition to admin audit events.
activityList=function(){const rows=[...get('dge-admin-activity',[]).map(a=>({label:a.action,detail:a.targetType+' · '+a.targetId,at:a.createdAt})),...acct().map(a=>({label:'ახალი მომხმარებელი',detail:a.name||a.email,at:a.createdAt||0})),...jobs.map(j=>({label:'ახალი განცხადება',detail:j.title,at:j.createdAt||0})),...jobs.filter(j=>j.status==='completed').map(j=>({label:'სამუშაო დასრულდა',detail:j.title,at:j.updatedAt||j.createdAt||0})),...readReviews().map(r=>({label:'ახალი შეფასება',detail:who(r.reviewerId)+' → '+who(r.reviewedUserId),at:r.createdAt})),...get('dge-reports',[]).map(r=>({label:'ახალი რეპორტი',detail:r.reason,at:r.createdAt}))].sort((a,b)=>b.at-a.at).slice(0,10);return rows.length?rows.map(a=>'<p class="admin-activity-row"><b>'+esc(a.label)+'</b> · '+esc(a.detail)+(a.at?' · '+new Date(a.at).toLocaleString('ka-GE'):'')+'</p>').join(''):'<div class="admin-empty">ბოლო აქტივობა ჯერ არ არის.</div>'};
// Admin job search reuses the same in-memory records and current status filter.
const adminJobsBeforeSearch=adminJobs;adminJobs=function(){const p=new URLSearchParams(location.hash.split('?')[1]||''),term=(p.get('q')||'').trim().toLocaleLowerCase('ka'),city=(p.get('city')||'').trim().toLocaleLowerCase('ka'),area=(p.get('area')||'').trim().toLocaleLowerCase('ka'),original=jobs;try{jobs=original.filter(j=>(!term||`${j.title||''} ${j.name||''} ${who(j.owner)} ${j.city||''} ${j.category||''}`.toLocaleLowerCase('ka').includes(term))&&(!city||(j.city||'').toLocaleLowerCase('ka').includes(city))&&districtSelectionMatches(area,j.area||j.district));const form='<form class="admin-search admin-location-search" id="admin-job-search"><input name="q" placeholder="მოძებნე სათაური, დამსაქმებელი ან კატეგორია" value="'+esc(p.get('q')||'')+'">'+locationField('city','ქალაქი',p.get('city')||'','','admin-jobs-city')+locationField('area','უბანი',p.get('area')||'',p.get('city')||'','admin-jobs-area')+'<button class="btn btn-primary btn-small">ძებნა</button></form>';return adminJobsBeforeSearch().replace('<div class="admin-tabs">',form+'<div class="admin-tabs">')}finally{jobs=original}};
// Backward-compatible role normalization for accounts created by the earlier work/hire UI.
// Review reports use a structured Georgian form and share the same persistent moderation queue.
document.addEventListener('click',e=>{const b=e.target.closest('[data-report-review]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(!user){notify('რეპორტისთვის ანგარიშზე შესვლა აუცილებელია.');return}document.querySelector('[data-review-report-modal]')?.remove();document.body.insertAdjacentHTML('beforeend','<div class="modal-backdrop" data-review-report-modal><form class="modal-card" data-review-report-form data-id="'+esc(b.dataset.reportReview)+'"><button type="button" class="modal-close" data-review-report-close>×</button><h2>შეფასების დარეპორტება</h2><label class="field">მიზეზი<select name="reason" required><option value="">აირჩიე მიზეზი</option><option>შეურაცხმყოფელი შინაარსი</option><option>ყალბი ინფორმაცია</option><option>სპამი</option><option>შეუსაბამო შინაარსი</option><option>სხვა</option></select></label><label class="field">დამატებითი ინფორმაცია<textarea name="description" placeholder="არასავალდებულო"></textarea></label><div class="error-msg" data-report-error></div><button class="btn btn-primary form-submit">რეპორტის გაგზავნა</button></form></div>')},true);
document.addEventListener('click',e=>{if(e.target.closest('[data-review-report-close]')||e.target.matches('[data-review-report-modal]'))e.target.closest('[data-review-report-modal]')?.remove()},true);
document.addEventListener('submit',e=>{const f=e.target.closest('[data-review-report-form]');if(!f)return;e.preventDefault();e.stopImmediatePropagation();const d=new FormData(f);try{reportReview(f.dataset.id,d.get('reason'),d.get('description'));f.innerHTML='<h2>მადლობა. თქვენი შეტყობინება მიღებულია.</h2><button type="button" class="btn btn-primary" data-review-report-close>დახურვა</button>'}catch(err){f.querySelector('[data-report-error]').textContent=err.message}},true);
const unguardedAdminView=adminView;adminView=function(path){try{return unguardedAdminView(path)}catch(err){console.error(err);app.innerHTML='<section class="container"><div class="admin-error">დაფიქსირდა შეცდომა. გთხოვ, თავიდან სცადე. <button class="btn btn-secondary btn-small" onclick="location.reload()">თავიდან ცდა</button></div></section>';return true}};

