const categories=[['დასუფთავება','✦'],['გადაზიდვა / გადატანა','↗'],['მშენებლობა','⌂'],['რემონტი','⌁'],['ბაღის სამუშაოები','❋'],['ძიძა / ბავშვზე ზრუნვა','♡'],['მოხუცის მოვლა','☘'],['კურიერი / მიტანა','➜'],['ღონისძიების დახმარება','♬'],['სხვა','＋']];
const seedDateAfter=offset=>{const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()+offset);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`};
const seedJobData=[
 {title:'ბინის დალაგება',category:'დასუფთავება',city:'თბილისი',area:'საბურთალო',pay:75,paymentType:'daily',duration:'4-8',description:'ვეძებთ ყურადღებიან ადამიანს ოროთახიანი ბინის დასალაგებლად. საწმენდი საშუალებები ადგილზე დაგხვდება.'},
 {title:'ავეჯის გადატანა',category:'გადაზიდვა / გადატანა',city:'თბილისი',area:'ვაკე',pay:25,paymentType:'hourly',duration:'2-4',description:'საჭიროა ორი ადამიანის დახმარება ავეჯის ახალ ბინაში ატანაზე. ლიფტი მუშაობს.'},
 {title:'ეზოს ბალახის მოთიბვა',category:'ბაღის სამუშაოები',city:'ბათუმი',area:'ბაგრატიონი',pay:100,paymentType:'fixed',duration:'4-8',description:'კერძო სახლის ეზოში ბალახის მოთიბვა და მოჭრილი ბალახის შეგროვება. ინვენტარი გვაქვს.'},
 {title:'სანტექნიკოსის დამხმარე',category:'რემონტი',city:'ქუთაისი',area:'ცენტრი',pay:120,paymentType:'daily',duration:'full-day',description:'ხელოსანს სჭირდება დამხმარე მილების გამოცვლისა და მასალის მოტანისას. გამოცდილება აუცილებელი არ არის.'},
 {title:'ბავშვის სკოლიდან მოყვანა',category:'ძიძა / ბავშვზე ზრუნვა',city:'თბილისი',area:'დიდუბე',pay:18,paymentType:'hourly',duration:'1-2',description:'პასუხისმგებლიანმა ადამიანმა ბავშვი სკოლიდან სახლამდე უნდა მოიყვანოს. გზა მოკლეა.'},
 {title:'ღონისძიების დარბაზის მომზადება',category:'ღონისძიების დახმარება',city:'თბილისი',area:'ვერა',pay:90,paymentType:'daily',duration:'4-8',description:'საჭიროა დახმარება პატარა ღონისძიების წინ სკამების, მაგიდებისა და დეკორაციების განლაგებაში.'},
 {title:'ფანჯრების წმენდა',category:'დასუფთავება',city:'რუსთავი',area:'ახალი რუსთავი',pay:55,paymentType:'fixed',duration:'2-4',description:'ვეძებთ ადამიანს ბინის ფანჯრებისა და აივნის მინის გასაწმენდად. საწმენდი საშუალებები ადგილზეა.'},
 {title:'სამშენებლო ნარჩენების გატანა',category:'მშენებლობა',city:'თბილისი',area:'გლდანი',pay:110,paymentType:'daily',duration:'2-4',description:'რემონტის შემდეგ ტომრებში მოთავსებული ნარჩენების ეზომდე ჩამოტანაში გვჭირდება დახმარება.'},
 {title:'კედლის შეღებვა',category:'რემონტი',city:'ბათუმი',area:'ძველი ბათუმი',pay:160,paymentType:'fixed',duration:'full-day',description:'ერთ ოთახში კედლების შეღებვა. საღებავი და ლილვაკები მზად არის, საჭიროა ფრთხილი შესრულება.'},
 {title:'ძაღლის გასეირნება',category:'სხვა',city:'თბილისი',area:'ვაკე',pay:15,paymentType:'hourly',duration:'1-2',description:'მეგობრული საშუალო ზომის ძაღლის გასეირნება პარკში. სასურველია ცხოველებთან გამოცდილება.'},
 {title:'პროდუქტების მიტანა',category:'კურიერი / მიტანა',city:'ქუთაისი',area:'ჭავჭავაძე',pay:35,paymentType:'fixed',duration:'1-2',description:'მაღაზიიდან პროდუქტების მიტანა ახლომდებარე მისამართზე. სია და თანხა წინასწარ მოგეწოდებათ.'},
 {title:'მოხუცის ყოველდღიური დახმარება',category:'მოხუცის მოვლა',city:'თბილისი',area:'ისანი',pay:85,paymentType:'daily',duration:'4-8',description:'ხანდაზმულ ადამიანს სჭირდება მსუბუქი საოჯახო დახმარება და პროდუქტების მოტანა დღის განმავლობაში.'},
 {title:'ავეჯის აწყობა',category:'რემონტი',city:'ზუგდიდი',area:'ცენტრი',pay:100,paymentType:'fixed',duration:'2-4',description:'საძინებლის კარადის აწყობა ინსტრუქციის მიხედვით. ხელსაწყოების ნაწილი ადგილზეა.'},
 {title:'ბაღის ყვავილების მოვლა',category:'ბაღის სამუშაოები',city:'თელავი',area:'ცენტრი',pay:60,paymentType:'daily',duration:'2-4',description:'ყვავილების მორწყვა, გამხმარი ტოტების მოცილება და პატარა ბაღის მოწესრიგება.'},
 {title:'ოფისის დასუფთავება',category:'დასუფთავება',city:'თბილისი',area:'მარჯანიშვილი',pay:80,paymentType:'fixed',duration:'4-8',description:'პატარა ოფისის იატაკის, სამზარეულოსა და სამუშაო ზედაპირების დასუფთავება.'},
 {title:'საწყობის ნივთების გადალაგება',category:'სხვა',city:'რუსთავი',area:'ინდუსტრიული ზონა',pay:95,paymentType:'daily',duration:'4-8',description:'საწყობში ყუთების მონიშნულ თაროებზე გადალაგება. მძიმე ნივთებზე მეორე თანამშრომელი დაგეხმარებათ.'},
 {title:'კაფეში ჭურჭლის დალაგება',category:'სხვა',city:'ბათუმი',area:'ცენტრი',pay:20,paymentType:'hourly',duration:'4-8',description:'საღამოს ცვლაში ჭურჭლის დალაგება და სამუშაო სივრცის მოწესრიგება. კვება ადგილზეა.'},
 {title:'სახლის მცირე შეკეთება',category:'რემონტი',city:'თბილისი',area:'ვარკეთილი',pay:70,paymentType:'fixed',duration:'2-4',description:'კარის სახელურის გამაგრება, რამდენიმე თაროს დამაგრება და მცირე საყოფაცხოვრებო შეკეთება.'},
 {title:'ბინის ნივთების შეფუთვა',category:'გადაზიდვა / გადატანა',city:'გორი',area:'ცენტრი',pay:65,paymentType:'daily',duration:'4-8',description:'გადასვლისთვის წიგნებისა და სამზარეულოს ნივთების ყუთებში ფრთხილად ჩალაგება.'},
 {title:'სტუმრების დახვედრა ღონისძიებაზე',category:'ღონისძიების დახმარება',city:'თბილისი',area:'მთაწმინდა',pay:90,paymentType:'daily',duration:'4-8',description:'ღონისძიების შესასვლელთან სტუმრების დახვედრა და რეგისტრაციის მაგიდასთან დახმარება.'},
 {title:'სარეცხის დაკეცვა',category:'დასუფთავება',city:'ფოთი',area:'ცენტრი',pay:30,paymentType:'fixed',duration:'1-2',description:'ოჯახის სუფთა სარეცხის დაკეცვა და კარადაში დალაგება. სამუშაო მშვიდ გარემოშია.'},
 {title:'აივნის მოწესრიგება',category:'ბაღის სამუშაოები',city:'თბილისი',area:'სოლოლაკი',pay:50,paymentType:'fixed',duration:'2-4',description:'აივნიდან ძველი ნივთების გატანა, იატაკის გაწმენდა და ქოთნების მოწესრიგება.'},
 {title:'ტვირთის ჩატვირთვა',category:'გადაზიდვა / გადატანა',city:'ქუთაისი',area:'ნიკეა',pay:22,paymentType:'hourly',duration:'2-4',description:'საჭიროა ორი დამხმარე მსუბუქი ავეჯისა და ყუთების მანქანაში ჩასატვირთად.'},
 {title:'ბავშვთან რამდენიმე საათით ყოფნა',category:'ძიძა / ბავშვზე ზრუნვა',city:'თბილისი',area:'დიღომი',pay:45,paymentType:'fixed',duration:'2-4',description:'მშობლის დაბრუნებამდე ხუთი წლის ბავშვთან ყოფნა, თამაში და წახემსების მომზადება.'},
 {title:'ეზოში ფოთლების შეგროვება',category:'ბაღის სამუშაოები',city:'ბათუმი',area:'ანგისა',pay:55,paymentType:'daily',duration:'2-4',description:'ეზოში ჩამოცვენილი ფოთლების შეგროვება და ტომრებში მოთავსება. საჭირო ინვენტარი გვაქვს.'},
 {title:'კიბის უჯრედის დასუფთავება',category:'დასუფთავება',city:'თბილისი',area:'ნაძალადევი',pay:45,paymentType:'fixed',duration:'2-4',description:'საცხოვრებელი კორპუსის სამი სართულის კიბისა და მოაჯირების დასუფთავება.'},
 {title:'სურათების დაკიდება',category:'რემონტი',city:'ზუგდიდი',area:'ცენტრი',pay:40,paymentType:'fixed',duration:'1-2',description:'ოთახში რამდენიმე სურათისა და პატარა სარკის კედელზე სწორად დამაგრება.'},
 {title:'ყურძნის კრეფის დახმარება',category:'ბაღის სამუშაოები',city:'თელავი',area:'წინანდალი',pay:75,paymentType:'daily',duration:'full-day',description:'ვენახში ყურძნის კრეფასა და კალათების გადატანაში გვჭირდება დამატებითი ხელი.'},
 {title:'კატისთვის ყურადღების მიქცევა',category:'სხვა',city:'თბილისი',area:'საბურთალო',pay:25,paymentType:'fixed',duration:'1-2',description:'მეზობლის არყოფნისას კატისთვის საკვების მიცემა და წყლის გამოცვლა.'},
 {title:'ფარდების მოხსნა და დაკიდება',category:'სხვა',city:'რუსთავი',area:'ძველი რუსთავი',pay:45,paymentType:'fixed',duration:'1-2',description:'ორი ოთახიდან ფარდების მოხსნა, გარეცხილის დაკიდება და კარნიზების შემოწმება.'}
];
const seedNames=['თამარ მახარაძე','ნინო ქავთარაძე','გიორგი ბერიძე','მარიამ ლომიძე','ლევან ჯაფარიძე','ეკა მაისურაძე','დავით კაპანაძე','სალომე ნადირაძე','ირაკლი გელაშვილი','ანა ჩხეიძე','ლიკა მელაძე','ზურა წიკლაური','ქეთი ბაქრაძე','სანდრო აბაშიძე','თეონა ხუციშვილი','გიგა კალანდაძე','ნატო კიკნაძე','ბექა დუმბაძე','ნინო ფერაძე','მამუკა ცინცაძე','სოფო ბერიძე','ალექსი სიხარულიძე','თამარ გოცირიძე','გიორგი ზურაბიშვილი','ია ხარშილაძე','ოთარ ლომიძე','მაკა წერეთელი','თორნიკე მაისაშვილი','ლელა შარაშიძე','რატი ქობულაძე'];
const seedTimeWindow=(duration,index)=>{const start=['08:30','09:00','10:00','11:00','13:00'][index%5],[hour,minute]=start.split(':').map(Number),hours=duration==='1-2'?2:duration==='2-4'?3:duration==='4-8'?6:duration==='multi-day'?8:9;return[start,`${String(hour+hours).padStart(2,'0')}:${String(minute).padStart(2,'0')}`]};
const seedJobs=seedJobData.map((item,index)=>{const dateOffset=index%14+1,[start,end]=seedTimeWindow(item.duration,index);return{...item,id:`sample-job-${String(index+1).padStart(3,'0')}`,date:seedDateAfter(dateOffset),dateEnd:item.duration==='multi-day'?seedDateAfter(dateOffset+1):'',start,end,posted:'ახლახან',name:seedNames[index],phone:''}});
const seedWorkerData=[
 {name:'ანა ლომიძე',city:'თბილისი',area:'საბურთალო',skills:['დასუფთავება','ძიძა','მოხუცის მოვლა'],offer:'ბინას დავალაგებ',about:'პასუხისმგებლიანი და მოწესრიგებული ვარ. სახლსა და ბავშვზე ზრუნვაში ოჯახებს მშვიდად და ყურადღებით ვეხმარები.',hasExperience:true,experienceDuration:'3 წელი',paymentType:'daily',pay:70,availability:'ამ კვირაში'},
 {name:'დავით გელაშვილი',city:'თბილისი',area:'ვაკე',skills:['გადაზიდვა / გადატანა','მშენებლობა'],offer:'ავეჯს გადავიტან',about:'ენერგიული და ფიზიკურად ძლიერი ვარ. ავეჯის გადატანასა და ყუთების უსაფრთხოდ ჩალაგებაში დაგეხმარებით.',hasExperience:true,experienceDuration:'5+ წელი',paymentType:'hourly',pay:22,availability:'დღესვე'},
 {name:'თამარ მელაძე',city:'ბათუმი',area:'ცენტრი',skills:['დასუფთავება','ბაღის სამუშაოები'],offer:'ეზოს მოვაწესრიგებ',about:'სახლსა და ბაღს ყურადღებით მოვუვლი. ვმუშაობ წინასწარ შეთანხმებულ დროს და საქმეს პასუხისმგებლობით ვასრულებ.',hasExperience:true,experienceDuration:'2 წელი',paymentType:'fixed',pay:65,availability:'ხვალიდან'},
 {name:'ნიკა ქობულაძე',city:'ქუთაისი',area:'ცენტრი',skills:['კურიერი / მიტანა','გადაზიდვა / გადატანა'],offer:'პროდუქტებს მოგიტანთ',about:'სანდო და პუნქტუალური ვარ, ქალაქში კარგად ვორიენტირებ. მცირე ამანათებსა და პროდუქტებს დროულად მოგიტანთ.',hasExperience:true,experienceDuration:'4 წელი',paymentType:'negotiable',pay:null,availability:'ამ კვირაში'},
 {name:'მარიამ სიხარულიძე',city:'თბილისი',area:'დიდუბე',skills:['ძიძა / ბავშვზე ზრუნვა','მოხუცის მოვლა'],offer:'ბავშვს მოვუვლი',about:'მზრუნველი და მშვიდი ადამიანი ვარ. ბავშვებთან დროის გატარება და ყოველდღიური საოჯახო დახმარება შემიძლია.',hasExperience:true,experienceDuration:'6 წელი',paymentType:'daily',pay:90,availability:'ხვალიდან'},
 {name:'გიორგი ჯიქია',city:'რუსთავი',area:'ცენტრი',skills:['რემონტი','მშენებლობა'],offer:'წვრილ რემონტს გავაკეთებ',about:'ვაკეთებ შეღებვას, თაროების დამაგრებასა და წვრილ შეკეთებებს. ვუფრთხილდები სახლსა და ნივთებს.',hasExperience:true,experienceDuration:'3 წელი',paymentType:'fixed',pay:100,availability:'დღესვე'},
 {name:'ეკა ბერიძე',city:'თბილისი',area:'ისანი',skills:['დასუფთავება','სხვა'],offer:'ფანჯრებს გავწმენდ',about:'სუფთად და გულდასმით ვმუშაობ. ფანჯრების, აივნისა და სახლის მოწესრიგებაში დაგეხმარებით.',hasExperience:false,experienceDuration:'',paymentType:'daily',pay:60,availability:'ამ კვირაში'},
 {name:'სანდრო კაპანაძე',city:'ქუთაისი',area:'ჭავჭავაძე',skills:['რემონტი','გადაზიდვა / გადატანა'],offer:'ავეჯს ავაწყობ',about:'კარადებისა და თაროების აწყობა, მცირე შეკეთება და ნივთების გადატანა შემიძლია. ხელსაწყოებიც მაქვს.',hasExperience:true,experienceDuration:'2 წელი',paymentType:'fixed',pay:85,availability:'დღესვე'},
 {name:'თეონა ნადირაძე',city:'თბილისი',area:'გლდანი',skills:['მოხუცის მოვლა','დასუფთავება'],offer:'მოხუცს დავეხმარები',about:'მოხუც ადამიანს ყოველდღიურ საქმეში მშვიდად და პატივისცემით დავეხმარები. საჭიროებისას პროდუქტებსაც მოვიტან.',hasExperience:true,experienceDuration:'5 წელი',paymentType:'hourly',pay:18,availability:'ხვალიდან'},
 {name:'ლევან წულუკიძე',city:'ბათუმი',area:'ბაგრატიონი',skills:['ბაღის სამუშაოები','მშენებლობა'],offer:'ბაღს მოვუვლი',about:'ეზოს მოვლა, ბალახის მოთიბვა და ფოთლების შეგროვება შემიძლია. საჭირო ინვენტარს შევათანხმებთ.',hasExperience:true,experienceDuration:'1 წელი',paymentType:'daily',pay:80,availability:'ამ კვირაში'},
 {name:'სალომე ჯაფარიძე',city:'თბილისი',area:'ვერა',skills:['ღონისძიების დახმარება','სხვა'],offer:'ღონისძიებაზე დაგეხმარებით',about:'ღონისძიების მომზადებაში, სტუმრების დახვედრასა და სივრცის მოწესრიგებაში ყურადღებით დაგეხმარებით.',hasExperience:true,experienceDuration:'3 წელი',paymentType:'hourly',pay:20,availability:'შეთანხმებით'},
 {name:'გიგა აბაშიძე',city:'ზუგდიდი',area:'ცენტრი',skills:['გადაზიდვა / გადატანა','მშენებლობა'],offer:'ტვირთს ჩავტვირთავ',about:'ფიზიკურად ძლიერი ვარ და ნივთების ჩატვირთვა-გადმოტვირთვაში სწრაფად და ფრთხილად ვმუშაობ.',hasExperience:false,experienceDuration:'',paymentType:'daily',pay:75,availability:'დღესვე'},
 {name:'ნინო ჩხეიძე',city:'თბილისი',area:'ვარკეთილი',skills:['ძიძა / ბავშვზე ზრუნვა','დასუფთავება'],offer:'ბავშვს სკოლაში მივიყვან',about:'პუნქტუალური ვარ და ბავშვთან უსაფრთხო გზით გადაადგილებას განსაკუთრებულ ყურადღებას ვაქცევ.',hasExperience:true,experienceDuration:'2 წელი',paymentType:'fixed',pay:40,availability:'ხვალიდან'},
 {name:'მაკა ხუციშვილი',city:'თელავი',area:'ცენტრი',skills:['ბაღის სამუშაოები','დასუფთავება'],offer:'ვენახში დაგეხმარებით',about:'ბაღისა და ვენახის სეზონურ სამუშაოებში გამოცდილება მაქვს. გუნდურად მუშაობა და დილის დაწყება შემიძლია.',hasExperience:true,experienceDuration:'5+ წელი',paymentType:'daily',pay:85,availability:'ამ კვირაში'},
 {name:'ირაკლი მაისურაძე',city:'თბილისი',area:'ნაძალადევი',skills:['რემონტი','სხვა'],offer:'თაროებს დავამაგრებ',about:'კედელზე თაროების, სურათებისა და მცირე ავეჯის უსაფრთხოდ დამაგრება შემიძლია.',hasExperience:true,experienceDuration:'3 წელი',paymentType:'fixed',pay:45,availability:'დღესვე'},
 {name:'ლიკა ბაქრაძე',city:'ბათუმი',area:'ძველი ბათუმი',skills:['დასუფთავება','ძიძა / ბავშვზე ზრუნვა'],offer:'სახლს დავალაგებ',about:'გულდასმით ვალაგებ სახლსა და სამუშაო სივრცეს. პასუხისმგებლიანი ვარ და სისუფთავეს დიდ ყურადღებას ვაქცევ.',hasExperience:true,experienceDuration:'1 წელი',paymentType:'daily',pay:65,availability:'შეთანხმებით'},
 {name:'ბექა დუმბაძე',city:'ფოთი',area:'ცენტრი',skills:['კურიერი / მიტანა','გადაზიდვა / გადატანა'],offer:'ამანათს მოგიტანთ',about:'ქალაქში გადაადგილება და მცირე ამანათების დროულად მიტანა შემიძლია. პუნქტუალური და ყურადღებიანი ვარ.',hasExperience:false,experienceDuration:'',paymentType:'hourly',pay:16,availability:'დღესვე'},
 {name:'ქეთი გოცირიძე',city:'თბილისი',area:'დიღომი',skills:['მოხუცის მოვლა','ძიძა / ბავშვზე ზრუნვა'],offer:'ყოველდღიურ საქმეში დაგეხმარებით',about:'ოჯახებს ყოველდღიურ საოჯახო საქმეში მზრუნველად და შეთანხმებული გრაფიკით ვეხმარები.',hasExperience:true,experienceDuration:'10+ წელი',paymentType:'negotiable',pay:null,availability:'შეთანხმებით'},
 {name:'ოთარ ლომიძე',city:'გორი',area:'ცენტრი',skills:['მშენებლობა','გადაზიდვა / გადატანა'],offer:'მასალას გადავიტან',about:'სამშენებლო მასალისა და მსუბუქი ავეჯის გადატანა შემიძლია. ვმუშაობ ფრთხილად და შეთანხმებულ ფასად.',hasExperience:true,experienceDuration:'4 წელი',paymentType:'daily',pay:95,availability:'ხვალიდან'},
 {name:'სოფო წერეთელი',city:'ქუთაისი',area:'ნიკეა',skills:['დასუფთავება','სხვა'],offer:'სარეცხს დავკეცავ',about:'სარეცხის დაკეცვა, კარადაში დალაგება და სახლის მსუბუქი მოწესრიგება შემიძლია.',hasExperience:false,experienceDuration:'',paymentType:'fixed',pay:35,availability:'ამ კვირაში'},
 {name:'რატი შარაშიძე',city:'თბილისი',area:'საბურთალო',skills:['რემონტი','გადაზიდვა / გადატანა'],offer:'კარადას ავაწყობ',about:'ავეჯის აწყობა და მცირე საყოფაცხოვრებო შეკეთება შემიძლია. წინასწარ შევათანხმოთ სამუშაოს მოცულობა.',hasExperience:true,experienceDuration:'2 წელი',paymentType:'fixed',pay:70,availability:'დღესვე'},
 {name:'ია კალანდაძე',city:'რუსთავი',area:'ახალი რუსთავი',skills:['ძიძა / ბავშვზე ზრუნვა','მოხუცის მოვლა'],offer:'ბავშვთან დავრჩები',about:'მშობლის არყოფნისას ბავშვთან რამდენიმე საათით დარჩენა და მარტივი წახემსების მომზადება შემიძლია.',hasExperience:true,experienceDuration:'1 წელი',paymentType:'hourly',pay:17,availability:'ხვალიდან'},
 {name:'ალექსი ცინცაძე',city:'თბილისი',area:'მთაწმინდა',skills:['ღონისძიების დახმარება','კურიერი / მიტანა'],offer:'სტუმრებს დავხვდები',about:'ღონისძიების სტუმრებს მივიღებ, რეგისტრაციაში დაგეხმარებით და სივრცეს მოწესრიგებულად შევინარჩუნებ.',hasExperience:false,experienceDuration:'',paymentType:'hourly',pay:20,availability:'შეთანხმებით'},
 {name:'ნატო ქობულაძე',city:'ბათუმი',area:'ანგისა',skills:['ბაღის სამუშაოები','დასუფთავება'],offer:'ეზოს ფოთლებს შევაგროვებ',about:'ეზოს ფოთლების შეგროვება, ყვავილების მოვლა და აივნის მოწესრიგება შემიძლია.',hasExperience:true,experienceDuration:'3 წელი',paymentType:'daily',pay:60,availability:'ამ კვირაში'}
];
const seedWorkers=seedWorkerData.map((worker,index)=>({...worker,id:`sample-worker-${String(index+1).padStart(3,'0')}`,exp:worker.hasExperience?worker.experienceDuration:'',initials:worker.name.split(' ').map(part=>part[0]).slice(0,2).join(''),phone:''}));const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const listingSeedVersion='20261001-many-fresh-listings-v1';if(get('dge-listing-seed-version','')!==listingSeedVersion){set('dge-jobs',seedJobs);set('dge-workers',[]);set('dge-listing-seed-version',listingSeedVersion)}let jobs=get('dge-jobs',seedJobs),saved=get('dge-saved',[]),user=get('dge-user',null),toastTimer;
const app=document.getElementById('app');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const dateKa=d=>{if(!d)return 'შეთანხმებით';const [y,m,day]=d.split('-').map(Number),months=['იანვარი','თებერვალი','მარტი','აპრილი','მაისი','ივნისი','ივლისი','აგვისტო','სექტემბერი','ოქტომბერი','ნოემბერი','დეკემბერი'];return `${day} ${months[m-1]||''}`};const shortDate=d=>{if(!d)return 'შეთანხმებით';const [y,m,day]=d.split('-').map(Number),months=['იან','თებ','მარ','აპრ','მაი','ივნ','ივლ','აგვ','სექ','ოქტ','ნოე','დეკ'];return `${day} ${months[m-1]||''}`};
function notify(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}function catOptions(sel=''){return '<option value="">ყველა კატეგორია</option>'+categories.map(([c])=>`<option ${c===sel?'selected':''}>${c}</option>`).join('')}function jobCard(j){return `<article class="job-card"><div class="card-top"><span class="pill">${esc(j.category)}</span>${j.subcategory?`<span class="pill pill-sub">${esc(j.subcategory)}</span>`:""}<button class="save-btn ${saved.includes(j.id)?'saved':''}" data-save="${esc(j.id)}" aria-label="შენახვა">${saved.includes(j.id)?'♥':'♡'}</button></div><h3>${esc(j.title)}</h3><div class="meta"><span>⌖ ${esc(j.city)}, ${esc(j.area)}</span><span>◷ ${shortDate(j.date)}</span><span>◷ ${esc(j.start)} – ${esc(j.end)}</span></div><p class="job-description">${esc(j.description)}</p><div class="card-bottom"><div class="price">${Number(j.pay).toLocaleString('ka-GE')} ₾ <small>/ დღეში</small></div><a href="#/job/${encodeURIComponent(j.id)}" class="btn btn-secondary btn-small">დეტალურად <span>→</span></a></div><div class="posted"><span class="posted-label">გამოქვეყნდა</span> <span class="posted-time">${esc(j.posted||'ახლახან')}</span></div></article>`}
function layout(title,subtitle,body,eyebrow='დღიური სამუშაო'){return `<section class="container"><div class="page-head"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${subtitle}</p></div>${body}</section>`}
function home(){const recent=[...jobs].slice(0,3);return `<section class="hero"><div class="hero-wrap"><div class="hero-copy"><h1>იპოვე დღიური სამუშაო ან ადამიანი, რომელიც გჭირდება</h1><p>ერთ სივრცეში შეხვდი ადამიანებს, რომლებიც ეძებენ სამუშაოს და მათ, ვისაც დახმარება სჭირდება.</p><div class="hero-actions"><a class="btn btn-primary" href="#/jobs">ვეძებ სამუშაოს <span>→</span></a><a class="btn btn-secondary" href="#/workers">ვეძებ ადამიანს <span>→</span></a></div><div class="trust-row"><span>დღიური სამუშაოები</span><span>უფასო განცხადებები</span><span>სანდო ადამიანები</span><span>მარტივი პროცესი</span></div></div><div class="hero-visual" aria-label="სახლი და ბაღი"><div class="hero-art"><div class="hero-sun"></div><div class="house"><div class="window"></div><div class="door"></div></div><div class="plant"><div class="pot"></div></div></div></div></div></section><section class="section section-white"><div class="container"><div class="section-heading"><div><span class="eyebrow">იპოვე შენი საქმე</span><h2>პოპულარული კატეგორიები</h2><p>აირჩიე რაც გჭირდება</p></div><a class="text-link" href="#/jobs">ყველა კატეგორია →</a></div><div class="categories">${categories.map(([c,i],n)=>`<a class="category" href="#/jobs?category=${encodeURIComponent(c)}"><span class="cat-icon">${i}</span><span><strong>${c}</strong><small>${jobs.filter(j=>j.category===c).length||(n%5+2)} განცხადება</small></span></a>`).join('')}</div></div></section><section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">ახალი შესაძლებლობები</span><h2>ბოლო განცხადებები</h2><p>იპოვე შენთვის შესაფერისი საქმე</p></div><a class="text-link" href="#/jobs">ყველა განცხადება →</a></div><div class="job-grid">${recent.map(jobCard).join('')}</div></div></section><section class="section section-white" id="how"><div class="container"><div class="section-heading"><div><span class="eyebrow">მარტივი დასაწყისი</span><h2>როგორ მუშაობს?</h2><p>სამი მარტივი ნაბიჯი</p></div></div><div class="how-grid"><article class="how-item"><span class="step">1</span><h3>მოძებნე ან გამოაქვეყნე</h3><p>აირჩიე განცხადება შენს ქალაქში ან აღწერე, როგორი დახმარება გჭირდება.</p></article><article class="how-item"><span class="step">2</span><h3>დაუკავშირდი ადამიანს</h3><p>შეათანხმე სამუშაოს დეტალები პირდაპირ დამსაქმებელთან ან შემსრულებელთან.</p></article><article class="how-item"><span class="step">3</span><h3>შეასრულე საქმე</h3><p>შეხვდით შეთანხმებულ დროს და მიიღე ანაზღაურება შესრულებული სამუშაოსთვის.</p></article></div></div></section><section class="section"><div class="container"><div class="cta-band"><div><h2>გჭირდება დახმარება დღეს?</h2><p>გამოაქვეყნე განცხადება უფასოდ და იპოვე შესაფერისი ადამიანი.</p></div><a class="btn" href="#/post">განცხადების დამატება <span>→</span></a></div></div></section>`}
function jobsPage(){const q=new URLSearchParams(location.hash.split('?')[1]||'');const cat=q.get('category')||'', city=q.get('city')||'', date=q.get('date')||'', min=q.get('min')||'', duration=q.get('duration')||'', term=q.get('q')||'';return layout('დღიური სამუშაოს ძებნა','იპოვე შენთვის შესაფერისი საქმე შენს ქალაქში.',`<form id="filters" class="filter-panel"><div class="field"><label for="fcat">კატეგორია</label><select id="fcat" name="category">${catOptions(cat)}</select></div><div class="field"><label for="fcity">ქალაქი / რაიონი</label><input id="fcity" name="city" placeholder="მაგ. თბილისი" value="${esc(city)}"></div><div class="field"><label for="fdate">თარიღი</label><input id="fdate" type="date" name="date" value="${esc(date)}"></div><div class="field"><label for="fmin">მინ. ანაზღაურება (₾)</label><input id="fmin" type="number" min="0" name="min" placeholder="მაგ. 50" value="${esc(min)}"></div><div class="field"><label for="fdur">ხანგრძლივობა</label><select id="fdur" name="duration"><option value="">ნებისმიერი</option><option value="4" ${duration==='4'?'selected':''}>4 საათამდე</option><option value="8" ${duration==='8'?'selected':''}>8 საათამდე</option><option value="9" ${duration==='9'?'selected':''}>8 საათზე მეტი</option></select></div><button class="btn btn-primary" type="submit">ძებნა <span>⌕</span></button><div class="field span-2"><input id="fq" name="q" placeholder="მოძებნე სიტყვით…" value="${esc(term)}" aria-label="მოძებნე სიტყვით"></div></form><div id="jobResults"></div>`,'დღიური სამუშაოები საქართველოში')}
function updateResults(){const form=document.getElementById('filters');if(!form)return;const data=new FormData(form),cat=data.get('category'),city=(data.get('city')||'').toLowerCase(),date=data.get('date'),min=Number(data.get('min')||0),dur=data.get('duration'),term=(data.get('q')||'').toLowerCase();const list=jobs.filter(j=>(!cat||j.category===cat)&&(!city||`${j.city} ${j.area}`.toLowerCase().includes(city))&&(!date||j.date===date)&&j.pay>=min&&(!dur||((new Date(`1970-01-01T${j.end}:00`)-new Date(`1970-01-01T${j.start}:00`))/3600000<=Number(dur)))&&(!term||`${j.title} ${j.description} ${j.category}`.toLowerCase().includes(term)));document.getElementById('jobResults').innerHTML=`<div class="results-head"><span>ნაპოვნია <strong>${list.length}</strong> განცხადება</span><span>განახლებულია ახლახან</span></div>${list.length?`<div class="job-grid">${list.map(jobCard).join('')}</div>`:`<div class="empty"><strong>განცხადებები ვერ მოიძებნა</strong>შეცვალე ფილტრები ან სხვა სიტყვით სცადე ძებნა.<div><button class="btn btn-secondary btn-small" style="margin-top:13px" data-clear-filters>ფილტრების გასუფთავება</button></div></div>`}`}
function details(id){const j=jobs.find(x=>x.id===id);if(!j)return layout('განცხადება ვერ მოიძებნა','ეს განცხადება შესაძლოა უკვე დასრულებულია.','<div class="empty"><strong>განცხადება მიუწვდომელია</strong><a href="#/jobs" class="btn btn-primary" style="margin-top:12px">ყველა განცხადება</a></div>');return `<section class="container"><div class="page-head"><a class="text-link" href="#/jobs">← განცხადებებზე დაბრუნება</a></div><div class="detail-layout"><article class="detail-main"><div class="detail-topline"><span class="pill">${esc(j.subcategory||j.category)}</span><button class="btn btn-secondary detail-save-button" data-save="${esc(j.id)}">${saved.includes(j.id)?'♥ შენახულია':'♡ შენახვა'}</button></div><h1>${esc(j.title)}</h1><div class="meta"><span>⌖ ${esc(j.city)}, ${esc(j.area)}</span><span>◷ ${shortDate(j.date)}</span><span>გამოქვეყნდა ${esc(j.posted)}</span></div><div class="detail-meta"><div><small>ანაზღაურება</small><strong>${Number(j.pay).toLocaleString('ka-GE')} ₾ / დღეში</strong></div><div><small>სამუშაოს დრო</small><strong>${esc(j.start)} – ${esc(j.end)}</strong></div><div><small>კატეგორია</small><strong>${esc(j.category)}</strong></div><div><small>მისამართი</small><strong>${esc(j.city)}, ${esc(j.area)}</strong></div></div><h3>სამუშაოს აღწერა</h3><p>${esc(j.description)}</p><h3>დამატებითი ინფორმაცია</h3><p>დეტალები და ზუსტი მისამართი შეთანხმდება დაკავშირებისას.</p><button class="btn btn-primary" data-apply="${esc(j.id)}">სამუშაოზე განაცხადის გაკეთება <span>→</span></button></article><aside class="profile-box">${Avatar({name:j.name,email:j.owner},'lg')}<h3>${esc(j.name)}</h3><p>განცხადების ავტორი</p><div class="notice">დაუკავშირდი და შეათანხმე სამუშაოს დეტალები.</div><button class="btn btn-primary" data-contact="${esc(j.id)}">დაკავშირება</button></aside></div></section>`}
function postPage(){return layout('სამუშაოს შეთავაზება','შეავსე ინფორმაცია და იპოვე შესაფერისი ადამიანი.',`<form class="form-shell" id="postForm"><div class="form-grid"><div class="field"><label>სამუშაოს დასახელება *</label><input name="title" required placeholder="მაგ. ბინის დასუფთავება" minlength="3"></div><div class="field"><label>კატეგორია *</label><select name="category" required>${catOptions()}</select></div><div class="field span-2"><label>აღწერა *</label><textarea name="description" required minlength="15" placeholder="მოკლედ აღწერე სამუშაო და საჭირო უნარები"></textarea></div><div class="field"><label>ქალაქი *</label><input name="city" required placeholder="მაგ. თბილისი"></div><div class="field"><label>მისამართი / უბანი *</label><input name="area" required placeholder="მაგ. ვაკე"></div><div class="field"><label>სამუშაოს თარიღი *</label><input name="date" type="date" required min="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>ანაზღაურება (₾) *</label><input name="pay" type="number" required min="1" placeholder="მაგ. 80"></div><div class="field"><label>დაწყების დრო *</label><input name="start" type="time" required value="09:00"></div><div class="field"><label>დასრულების დრო *</label><input name="end" type="time" required value="17:00"></div><div class="field"><label>ტელეფონი *</label><input name="phone" type="tel" required pattern="[+0-9 ()-]{9,}" placeholder="5XX XX XX XX"></div><div class="field"><label>თქვენი სახელი *</label><input name="name" required value="${esc(user?.name||'')}" placeholder="სახელი და გვარი"></div></div><p class="hint">* აუცილებელი ველები. განცხადება უფასოა.</p><button class="btn btn-primary form-submit">განცხადების გამოქვეყნება <span>→</span></button><div id="postMessage"></div></form>`,'დაეხმარე საქმეს პოვნაში')}
function workerPayLabel(w){return w?.paymentType==='negotiable'?'შეთანხმებით':`${Number(w?.pay||0).toLocaleString('ka-GE')} ₾`}
function workerExperienceValue(w){if(w.hasExperience===true||w.hasExperience==='yes')return w.experienceDuration||'';if(w.hasExperience===false||w.hasExperience==='no')return '';return w.exp||''}
function workerCard(w){const payLabel=w.paymentType==='negotiable'?'ანაზღაურება':w.paymentType==='hourly'?'საათობრივი ანაზღაურება':w.paymentType==='fixed'?'ფიქსირებული ანაზღაურება':'დღიური ანაზღაურება',experience=workerExperienceValue(w),location=[w.city,w.area||w.district||'ყველა უბანი'].filter(Boolean).map(esc).join(', ');return `<article class="worker-card">${Avatar(w,'lg')}<h3>${esc(w.name)}</h3><p>⌖ ${location}</p><div class="skills">${w.skills.map((s,index)=>`<span class="skill${index>3?' skill-overflow':''}">${esc(s)}</span>`).join('')}${w.skills.length>4?`<span class="skill skill-more" aria-label="და კიდევ ${w.skills.length-4} ქვეკატეგორია" title="და კიდევ ${w.skills.length-4} ქვეკატეგორია">…</span>`:''}</div><p>${esc(w.about.slice(0,85))}${w.about.length>85?'…':''}</p><div class="worker-stats${experience?'':' worker-stats-no-experience'}${w.paymentType==='negotiable'?' worker-stats-negotiable':''}">${experience?`<span><strong>${esc(experience)}</strong>გამოცდილება</span>`:''}<span class="worker-pay-stat"><strong>${esc(workerPayLabel(w))}</strong><small class="worker-stat-label">${payLabel}</small></span><span class="worker-availability-stat"><strong>${esc(w.availability)}</strong><small class="worker-stat-label">ხელმისაწვდომია</small></span></div><a class="btn btn-secondary btn-small" style="margin-top:14px;width:100%" href="#/worker/${encodeURIComponent(w.id)}">პროფილის ნახვა →</a></article>`}
function workersPage(){return layout('ვეძებ ადამიანს','გაეცანი გამოცდილ ადამიანებს, რომლებიც მზად არიან დასახმარებლად.',`<div class="filter-panel" style="grid-template-columns:1fr 1fr auto"><div class="field"><label>ქალაქი / რაიონი</label><input id="workerCity" placeholder="მაგ. თბილისი"></div><div class="field"><label>უნარი / კატეგორია</label><select id="workerSkill">${catOptions()}</select></div><button class="btn btn-primary" id="workerSearch">ძებნა ⌕</button></div><div id="workerResults" class="worker-grid"></div>`,'სანდო ადამიანები მთელი საქართველოს მასშტაბით')}
function updateWorkers(){const el=document.getElementById('workerResults');if(!el)return;const city=(document.getElementById('workerCity').value||'').toLowerCase(),skill=document.getElementById('workerSkill').value;const arr=seedWorkers.filter(w=>(!city||`${w.city} ${w.area}`.toLowerCase().includes(city))&&(!skill||w.skills.includes(skill)));el.innerHTML=arr.length?arr.map(workerCard).join(''):`<div class="empty" style="grid-column:1/-1"><strong>ადამიანები ვერ მოიძებნა</strong>ცადე სხვა ქალაქი ან კატეგორია.</div>`}
function workerDetail(id){const w=seedWorkers.find(x=>x.id===id);if(!w)return layout('პროფილი ვერ მოიძებნა','','<div class="empty">პროფილი მიუწვდომელია.</div>');return `<section class="container"><div class="page-head"><a href="#/workers" class="text-link">← ადამიანების ძებნაზე დაბრუნება</a></div><div class="detail-layout"><article class="detail-main"><div class="worker-profile-heading">${Avatar(w,'profile')}<div><h1>${esc(w.name)}</h1><div class="meta">⌖ ${esc(w.city)}, ${esc(w.area)}</div></div></div><h3>უნარები</h3><div class="skills" style="justify-content:flex-start">${w.skills.map(s=>`<span class="skill">${esc(s)}</span>`).join('')}</div><h3>ჩემ შესახებ</h3><p>${esc(w.about)}</p><h3>გამოცდილება</h3><p>${esc(w.exp)} სამუშაო გამოცდილება. წინა სამუშაოებისა და რეკომენდაციების დამატება მალე იქნება შესაძლებელი.</p><h3>წინა სამუშაოები და შეფასებები</h3><div class="notice">შეფასებები მალე დაემატება.</div></article><aside class="profile-box"><h3>სამუშაო პირობები</h3><div class="worker-stats" style="text-align:left"><span><strong>${w.pay} ₾</strong>დღიური ანაზღაურება</span><span><strong>${esc(w.availability)}</strong>ხელმისაწვდომია</span></div><button class="btn btn-primary" data-worker-contact="${esc(w.id)}">დაკავშირება</button></aside></div></section>`}
function login(){return `<div class="auth-wrap"><form class="auth-card" id="authForm"><span class="eyebrow">კეთილი იყოს შენი დაბრუნება</span><div class="auth-tabs"><button type="button" class="active" data-tab="login">შესვლა</button><button type="button" data-tab="register">რეგისტრაცია</button></div><h1 id="authTitle">შესვლა</h1><p id="authSub">შედი ანგარიშზე და განაგრძე</p><div id="authFields"><div class="field"><label>ელფოსტა</label><input name="email" required type="email" placeholder="სახელი@example.ge"></div><div class="field" style="margin-top:13px"><label>პაროლი</label><input name="password" required type="password" minlength="4" placeholder="მინიმუმ 4 სიმბოლო"></div></div><button class="btn btn-primary form-submit" id="authSubmit">შესვლა →</button><div id="authMessage"></div></form></div>`}
function dashboard(){if(!user)return `<div class="auth-wrap"><div class="auth-card"><h1>შესვლა</h1><p>დაინახე შენი განცხადებები და განაცხადები.</p><a class="btn btn-primary" href="#/login">შესვლა / რეგისტრაცია</a></div></div>`;const mine=jobs.filter(j=>j.owner===user.email),myapps=get('dge-apps',[]).filter(a=>a.email===user.email);return `<section class="container"><div class="page-head"><span class="eyebrow">პირადი სივრცე</span><h1>გამარჯობა, ${esc(user.name)}!</h1><p>მართე შენი განცხადებები და განაცხადები ერთ სივრცეში.</p></div><div class="dashboard"><nav class="side-menu"><a class="active" href="#/dashboard">მიმოხილვა</a><a href="#/post">＋ ახალი განცხადება</a><a href="#/saved">შენახული განცხადებები (${saved.length})</a><a href="#/dashboard?tab=applications">ჩემი განაცხადები (${myapps.length})</a><a href="#/dashboard?tab=posts">ჩემი განცხადებები (${mine.length})</a><a href="#/profile">პროფილი</a><a href="#" data-logout>გასვლა</a></nav><div class="dash-main"><h2>შენი საქმიანობა</h2><p>ანგარიშის მიმოხილვა</p><div class="dash-stats"><div class="stat-card"><small>ჩემი განცხადებები</small><strong>${mine.length}</strong></div><div class="stat-card"><small>შენახული</small><strong>${saved.length}</strong></div><div class="stat-card"><small>ჩემი განაცხადები</small><strong>${myapps.length}</strong></div></div><div class="section-heading"><h2>${new URLSearchParams(location.hash.split('?')[1]||'').get('tab')==='applications'?'ჩემი განაცხადები':'ბოლო განცხადებები'}</h2><a class="text-link" href="#/post">+ დამატება</a></div>${mine.length?`<div class="job-grid">${mine.map(jobCard).join('')}</div>`:`<div class="empty"><strong>ჯერ განცხადება არ დაგიმატებია</strong>შექმენი პირველი განცხადება ან დაათვალიერე ხელმისაწვდომი საქმეები.<a class="btn btn-primary btn-small" style="margin-top:13px" href="#/post">განცხადების დამატება</a></div>`}</div></div></section>`}
function savedPage(){const items=jobs.filter(j=>saved.includes(j.id));return layout('შენახული განცხადებები','შენთვის საინტერესო შესაძლებლობები ერთ ადგილას.',items.length?`<div class="job-grid">${items.map(jobCard).join('')}</div>`:'<div class="empty"><strong>შენახული განცხადებები ჯერ არ გაქვს</strong>დააჭირე ♡ ღილაკს საინტერესო განცხადების შესანახად.<a href="#/jobs" class="btn btn-primary btn-small" style="margin-top:12px">სამუშაოს ძებნა</a></div>')}
function profilePage(){if(!user)return login();return layout('ჩემი პროფილი','მართე შენი ანგარიშის ინფორმაცია.',`<form id="profileForm" class="form-shell"><section class="profile-photo-card"><div><span class="eyebrow">ანგარიშის ფოტო</span><h2>პროფილის ფოტო</h2><p>ფოტოს დამატება არასავალდებულოა.</p></div>${profilePhotoEditor(user,'profile')}</section><div class="form-grid"><div class="field"><label>სახელი და გვარი</label><input name="name" required value="${esc(user.name)}"></div><div class="field"><label>ელფოსტა</label><input disabled value="${esc(user.email)}"></div><div class="field"><label>ტელეფონი</label><input name="phone" type="tel" value="${esc(user.phone||'')}" placeholder="5XX XX XX XX"></div>${profileGenderOptions(user.gender)}<div class="field"><label>ჩემი როლი</label><select name="role"><option ${user.role==='work'?'selected':''} value="work">სამუშაოს ვეძებ</option><option ${user.role==='hire'?'selected':''} value="hire">ადამიანს ვეძებ</option><option ${user.role==='both'?'selected':''} value="both">ორივე</option></select></div></div><button class="btn btn-primary form-submit">შენახვა</button><div id="profileMessage"></div></form>`,'ანგარიშის პარამეტრები')}
function render(){const hash=location.hash||'#/';const path=hash.slice(1).split('?')[0];document.getElementById('nav').classList.remove('open');if(path==='/')app.innerHTML=home();else if(path==='/jobs')app.innerHTML=jobsPage();else if(path.startsWith('/job/'))app.innerHTML=details(decodeURIComponent(path.split('/')[2]));else if(path==='/post')app.innerHTML=postPage();else if(path==='/workers')app.innerHTML=workersPage();else if(path.startsWith('/worker/'))app.innerHTML=workerDetail(decodeURIComponent(path.split('/')[2]));else if(path==='/login')app.innerHTML=login();else if(path==='/dashboard')app.innerHTML=dashboard();else if(path==='/saved')app.innerHTML=savedPage();else if(path==='/profile')app.innerHTML=profilePage();else if(path==='/how'){app.innerHTML=`<section class="section"><div class="container"><div class="page-head"><span class="eyebrow">მარტივი დასაწყისი</span><h1>როგორ მუშაობს?</h1><p>სამუშაოს პოვნა ან შეთავაზება სამ მარტივ ნაბიჯში.</p></div><div class="how-grid"><article class="how-item"><span class="step">01</span><h3>მოძებნე ან გამოაქვეყნე</h3><p>აირჩიე განცხადება შენს ქალაქში ან აღწერე საჭირო დახმარება.</p></article><article class="how-item"><span class="step">02</span><h3>დაუკავშირდი ადამიანს</h3><p>შეათანხმე სამუშაოს დეტალები პირდაპირ.</p></article><article class="how-item"><span class="step">03</span><h3>შეასრულე საქმე</h3><p>შეხვდით შეთანხმებულ დროს და მიიღე ანაზღაურება.</p></article></div></div></section>`}else app.innerHTML=home();if(path==='/jobs')updateResults();if(path==='/workers'){updateWorkers();document.getElementById('workerSearch')?.addEventListener('click',updateWorkers);document.getElementById('workerCity')?.addEventListener('input',updateWorkers);document.getElementById('workerSkill')?.addEventListener('change',updateWorkers);}window.scrollTo(0,0)}
document.addEventListener('click',e=>{const saveBtn=e.target.closest('[data-save]');if(saveBtn){const id=saveBtn.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];set('dge-saved',saved);notify(saved.includes(id)?'განცხადება შენახულია':'შენახული განცხადებებიდან წაიშალა');render();return}const clear=e.target.closest('[data-clear-filters]');if(clear){location.hash='#/jobs';return}const apply=e.target.closest('[data-apply]');if(apply){e.preventDefault();e.stopImmediatePropagation();notify('განაცხადების გაგზავნა დროებით შეჩერებულია');return}const contact=e.target.closest('[data-contact]');if(contact){const j=jobs.find(x=>x.id===contact.dataset.contact);notify(`${j.name}: ${j.phone}`);return}const wc=e.target.closest('[data-worker-contact]');if(wc){const w=[...get('dge-workers',[]),...seedWorkers].find(x=>x.id===wc.dataset.workerContact);notify(`${w.name}: ${w.phone||'ტელეფონი მოთხოვნისას'}`);return}const tab=e.target.closest('[data-tab]');if(tab){const reg=tab.dataset.tab==='register';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===tab));document.getElementById('authTitle').textContent=reg?'რეგისტრაცია':'შესვლა';document.getElementById('authSub').textContent=reg?'შექმენი ანგარიში რამდენიმე წამში':'შედი ანგარიშზე და განაგრძე';document.getElementById('authSubmit').textContent=reg?'ანგარიშის შექმნა →':'შესვლა →';if(reg)document.getElementById('authFields').innerHTML=`<div class="field"><label>სახელი და გვარი</label><input name="name" required placeholder="მაგ. ნინო ბერიძე"></div><div class="field" style="margin-top:12px"><label>ელფოსტა</label><input name="email" required type="email" placeholder="სახელი@example.ge"></div><div class="field" style="margin-top:12px"><label>პაროლი</label><input name="password" required type="password" minlength="4" placeholder="მინიმუმ 4 სიმბოლო"></div><div class="field" style="margin-top:14px"><label>რას ეძებ?</label><div class="radio-row"><label class="radio-option"><input type="radio" name="role" value="work" checked>სამუშაოს ვეძებ</label><label class="radio-option"><input type="radio" name="role" value="hire">ადამიანს ვეძებ</label></div><label class="radio-option" style="display:block;margin-top:7px"><input type="checkbox" name="both">ორივე ტიპის შესაძლებლობა მაინტერესებს</label></div>`;else document.getElementById('authFields').innerHTML=`<div class="field"><label>ელფოსტა</label><input name="email" required type="email" placeholder="სახელი@example.ge"></div><div class="field" style="margin-top:13px"><label>პაროლი</label><input name="password" required type="password" minlength="4" placeholder="მინიმუმ 4 სიმბოლო"></div>`;return}if(e.target.closest('[data-logout]')){e.preventDefault();user=null;localStorage.removeItem('dge-user');notify('ანგარიშიდან გამოხვედი');location.hash='#/';return}});
document.addEventListener('submit',e=>{if(e.target.id==='filters'){e.preventDefault();updateResults();return}if(e.target.id==='postForm'){e.preventDefault();const f=new FormData(e.target);const createdAt=Date.now();const j={id:'j'+createdAt,createdAt,title:f.get('title'),category:f.get('category'),subcategory:f.get('subcategory'),city:f.get('city'),area:f.get('area'),date:f.get('date'),start:f.get('start')||'',end:f.get('end')||'',pay:Number(f.get('pay')),description:f.get('description'),posted:'ახლახან',name:f.get('name'),phone:f.get('phone'),owner:user?.email||''};jobs.unshift(j);set('dge-jobs',jobs);document.getElementById('postMessage').innerHTML='<div class="success-box">განცხადება წარმატებით გამოქვეყნდა! გადავდივართ განცხადებაზე…</div>';setTimeout(()=>location.hash=`#/job/${j.id}`,850);return}if(e.target.id==='authForm'){e.preventDefault();const f=new FormData(e.target),register=document.getElementById('authTitle').textContent==='რეგისტრაცია';let existing=get('dge-accounts',[]);if(register){if(existing.some(x=>x.email===f.get('email'))){document.getElementById('authMessage').innerHTML='<div class="error-msg">ამ ელფოსტით ანგარიში უკვე არსებობს.</div>';return}user={name:f.get('name'),email:f.get('email'),role:f.get('both')?'both':f.get('role')};existing.push({...user,password:f.get('password')});set('dge-accounts',existing)}else{const account=existing.find(x=>x.email===f.get('email')&&x.password===f.get('password'));if(!account){document.getElementById('authMessage').innerHTML='<div class="error-msg">ელფოსტა ან პაროლი არასწორია. რეგისტრაციისთვის აირჩიე შესაბამისი ჩანართი.</div>';return}user={name:account.name,email:account.email,role:account.role}}set('dge-user',user);notify(register?'ანგარიში შეიქმნა':'კეთილი იყოს შენი დაბრუნება');location.hash=sessionStorage.getItem('dge-next')?'#/post-role':(sessionStorage.getItem('dge-return')||'#/dashboard');sessionStorage.removeItem('dge-next');sessionStorage.removeItem('dge-return');return}if(e.target.id==='profileForm'){e.preventDefault();const d=new FormData(e.target);user={...user,name:d.get('name'),phone:d.get('phone')||'',gender:d.get('gender')||'unspecified',profilePhoto:d.get('profilePhoto')||null,role:d.get('role')};set('dge-user',user);const rows=get('dge-accounts',[]),idx=rows.findIndex(a=>a.email===user.email);if(idx>=0){rows[idx]={...rows[idx],name:user.name,phone:user.phone,gender:user.gender,profilePhoto:user.profilePhoto,role:user.role};set('dge-accounts',rows)}refreshAvatars?.();document.getElementById('profileMessage').innerHTML='<div class="success-box">პროფილი განახლდა.</div>';return}});
document.addEventListener('input',e=>{if(e.target.closest('#filters'))updateResults()});document.getElementById('menuToggle').addEventListener('click',()=>{const nav=document.getElementById('nav'),trigger=document.querySelector('.account-nav-trigger'),panel=trigger?.closest('.account-nav')?.querySelector('.account-dropdown');if(window.setAccountMenuState)setAccountMenuState(trigger,panel,false);else if(trigger&&panel){trigger.setAttribute('aria-expanded','false');trigger.classList.remove('is-open');panel.hidden=true;panel.classList.remove('is-open')}nav.classList.toggle('open')});document.getElementById('workerSearch')?.addEventListener('click',updateWorkers);document.getElementById('workerCity')?.addEventListener('input',updateWorkers);document.getElementById('workerSkill')?.addEventListener('change',updateWorkers);render();










