function authBrand(){return '<a class="auth-brand" href="#/" data-auth-dismiss aria-label="Pove24.com — მთავარ გვერდზე"><span>Pove24.com</span></a>'}
function authPasswordField(name,label,placeholder,autocomplete){return '<div class="field auth-field"><label for="'+name+'">'+label+'</label><div class="auth-password-wrap"><input id="'+name+'" name="'+name+'" type="password" required '+(autocomplete==='new-password'&&name==='password'?'minlength="8"':'')+' autocomplete="'+autocomplete+'" placeholder="'+placeholder+'"><button class="auth-password-toggle" type="button" data-password-toggle="'+name+'" aria-label="პაროლის ჩვენება" aria-pressed="false">'+dayIcon('eye',19)+'</button></div></div>'}
function authPage(mode='login'){
 const registering=mode==='register',heading=registering?'ანგარიშის შექმნა':'შესვლა',returnTo=sessionStorage.getItem('dge-return')||'',postIntent=returnTo.includes('post-role')||returnTo.includes('/post')||sessionStorage.getItem('dge-next')==='1',intro=postIntent?(registering?'რეგისტრაციის დასრულების შემდეგ შეძლებთ განცხადების დამატებას':'განცხადების დასამატებლად შედი ანგარიშში ან შექმენი ახალი ანგარიში.'):(registering?'შექმენი ანგარიში და დაიწყე გამოყენება.':'შედი შენს ანგარიშზე და გააგრძელე.'),introClass=postIntent?' auth-context':'';
 const fields=registering
  ?'<input type="hidden" name="name" data-full-name><div class="field auth-field"><label for="auth-first-name">სახელი<span class="auth-required">*</span></label><input id="auth-first-name" name="firstName" required autocomplete="given-name" placeholder="შეიყვანე სახელი"></div><div class="field auth-field"><label for="auth-last-name">გვარი<span class="auth-required">*</span></label><input id="auth-last-name" name="lastName" required autocomplete="family-name" placeholder="შეიყვანე გვარი"></div><div class="field auth-field"><label for="auth-register-email">ელფოსტა<span class="auth-required">*</span></label><input id="auth-register-email" name="email" type="email" required autocomplete="email" placeholder="მაგ. სახელი@example.ge"></div>'+authPasswordField('password','პაროლი<span class="auth-required">*</span>','მინიმუმ 8 სიმბოლო','new-password')+authPasswordField('passwordConfirm','გაიმეორე პაროლი<span class="auth-required">*</span>','გაიმეორე პაროლი','new-password')+'<div class="auth-extras">'+registrationProfileFields()+'<fieldset class="auth-role-field"><legend>როგორ გამოიყენებ პლატფორმას?</legend><div class="radio-row"><label class="radio-option"><input type="radio" name="role" value="work" checked>სამუშაოს ვეძებ</label><label class="radio-option"><input type="radio" name="role" value="hire">ადამიანს ვეძებ</label></div><label class="radio-option auth-both-option"><input type="checkbox" name="both">ორივე ტიპის შესაძლებლობა მაინტერესებს</label></fieldset></div>'
  :'<div class="field auth-field"><label for="auth-email">ელფოსტა</label><input id="auth-email" name="email" type="email" required autocomplete="username" placeholder="მაგ. სახელი@example.ge"></div>'+authPasswordField('password','პაროლი','შეიყვანე პაროლი','current-password')+'<div class="auth-recovery-row"><button type="button" class="auth-text-button" data-auth-recovery>პაროლის აღდგენა</button></div>';
 const switchText=registering?'უკვე გაქვს ანგარიში?':'არ გაქვს ანგარიში?',switchLabel=registering?'შესვლა':'შექმენი',nextMode=registering?'login':'register',submit=registering?'გაგრძელება':'შესვლა';
 return '<section class="auth-screen"><div class="auth-card '+(registering?'auth-card-register':'auth-card-login')+'">'+authBrand()+'<button class="auth-close" type="button" data-auth-dismiss aria-label="ავტორიზაციის დახურვა">'+dayIcon('xCircle',20)+'</button>'+(registering?'<h1 id="authTitle">'+heading+'</h1>':'')+'<p class="auth-intro'+introClass+'">'+intro+'</p><form id="authForm" data-auth-mode="'+mode+'">'+fields+'<button class="btn btn-primary auth-submit" type="submit">'+submit+'</button><div class="auth-message" id="authMessage" role="status" aria-live="polite"></div></form><p class="auth-switch">'+switchText+' <button type="button" class="auth-switch-action" data-auth-switch="'+nextMode+'">'+switchLabel+'</button></p></div></section>'
}
function loginPage(){return authPage('login')}
function registerPage(){return authPage('register')}
function login(){const params=new URLSearchParams((location.hash||'').split('?')[1]||'');return (location.hash.split('?')[0]==='#/register'||params.get('register')==='1'||params.get('mode')==='register')?registerPage():loginPage()}
function setAuthMode(mode){
 const hash=mode==='register'?'#/login?register=1':'#/login';
 history.replaceState(history.state,'',location.pathname+location.search+hash);
 document.body.classList.add('auth-page-active');
 app.innerHTML=authPage(mode);
 app.querySelector('.auth-card')?.classList.add('auth-mode-enter');
}
function clearAuthIntent(){['dge-return','dge-next','dge-pending-save','dge-pending-profile-save'].forEach(key=>sessionStorage.removeItem(key))}
const authUiPreviousRoute=routeView;
routeView=function(){const hash=location.hash||'#/';const path=hash.split('?')[0],protectedPaths=['/start','/post-role','/post','/worker-form','/dashboard','/saved','/profile','/admin','/admin/users','/admin/jobs','/admin/reviews','/admin/reports','/admin/settings'];if(!user&&protectedPaths.some(route=>path===route||route==='/admin'&&path.startsWith('/admin/'))){const intended=path==='/start'||path==='/post'||path==='/post-role'?'#/post-role':hash;sessionStorage.setItem('dge-return',intended);location.replace('#/login');document.body.classList.add('auth-page-active');app.innerHTML=loginPage();return}if(path==='/register'&&!user){document.body.classList.add('auth-page-active');app.innerHTML=registerPage();window.scrollTo(0,0);return}if(path==='/login'&&!user){document.body.classList.add('auth-page-active');app.innerHTML=login();accountNavigation();window.scrollTo(0,0);return}document.body.classList.remove('auth-page-active');authUiPreviousRoute()};render=routeView;
routeView();
document.addEventListener('click',event=>{
 const switchButton=event.target.closest('[data-auth-switch]');if(switchButton){event.preventDefault();event.stopImmediatePropagation();setAuthMode(switchButton.dataset.authSwitch);return}
 const dismiss=event.target.closest('[data-auth-dismiss]');if(dismiss){event.preventDefault();event.stopImmediatePropagation();clearAuthIntent();location.hash='#/';return}
 const startLink=event.target.closest('a[href="#/start"]');if(startLink&&!user){event.preventDefault();event.stopImmediatePropagation();sessionStorage.setItem('dge-return','#/post-role');location.hash='#/login';return}

 const toggle=event.target.closest('[data-password-toggle]');if(toggle){const input=document.getElementById(toggle.dataset.passwordToggle);if(!input)return;const visible=input.type==='password';input.type=visible?'text':'password';toggle.setAttribute('aria-pressed',String(visible));toggle.setAttribute('aria-label',visible?'პაროლის დამალვა':'პაროლის ჩვენება');toggle.innerHTML=dayIcon(visible?'eyeOff':'eye',19);input.focus();return}
 if(event.target.closest('[data-auth-recovery]')){const message=document.getElementById('authMessage');if(message)message.innerHTML='<div class="auth-info">პაროლის აღდგენა ამ ვერსიაში ჯერ არ არის ხელმისაწვდომი.</div>';return}
},true);
document.addEventListener('input',event=>{if(!event.target.closest('#authForm'))return;const form=event.target.form;if(form?.dataset.authMode==='register'){const first=form.elements.firstName?.value.trim()||'',last=form.elements.lastName?.value.trim()||'';form.elements.name.value=[first,last].filter(Boolean).join(' ');const pass=form.elements.password,confirm=form.elements.passwordConfirm;if(pass&&confirm)confirm.setCustomValidity(confirm.value&&pass.value!==confirm.value?'პაროლები ერთმანეთს არ ემთხვევა.':'')}});
window.addEventListener('hashchange',()=>{if(!['#/login','#/register'].some(route=>(location.hash||'').startsWith(route)))document.body.classList.remove('auth-page-active')});
