const categoryGroups={
 'სახლის საქმეები':['სახლის დალაგება','გენერალური დასუფთავება','ფანჯრების წმენდა','უთოობა','ტანსაცმლის დალაგება','კერძის მომზადება','სხვა სახლის საქმე','საყიდლებზე წასვლა'],
 'ადამიანების დახმარება':['ხანდაზმულის დახმარება/მოვლა','ბავშვზე ზრუნვა / ძიძა','საყიდლებზე წასვლა','წამლების / ნივთების მოტანა','სხვა დახმარება ადამიანისთვის'],
 'შინაური ცხოველები':['ძაღლის გასეირნება','შინაური ცხოველის მოვლა','ვეტერინართან მიყვანა','სხვა საქმე შინაურ ცხოველთან'],
 'რემონტი და ხელოსნობა':['შეღებვა','კედლის შეკეთება','ავეჯის აწყობა','ავეჯის შეკეთება','ელექტროობის დამხმარე','სანტექნიკის დამხმარე','სხვა ხელოსნური სამუშაო'],
 'ეზო და გარე სამუშაოები':['ბაღის მოვლა','ბალახის გათიბვა','მცენარეების მოვლა','ეზოს დასუფთავება','თოვლის დასუფთავება','სხვა ეზოს სამუშაო'],
 'მიტანა და გადაადგილება':['კურიერი','მანქანით დახმარება','მძღოლი ერთი დღით','ავეჯის/ნივთების გადატანა','ტვირთის დატვირთვა/გადმოტვირთვა','ბინის დაცლა','სხვა მიტანის ან გადაადგილების საქმე'],
 'ღონისძიებები':['ღონისძიების დამხმარე','ქორწილის დამხმარე','სერვირების დამხმარე','მიმტანი','ღონისძიების მონტაჟი / დემონტაჟი','ფოტოს / ვიდეოს გადაღების დამხმარე','ღონისძიების სხვა სამუშაო'],
 'ონლაინ / კომპიუტერული':['ვინდოუსის გადაყენება','კომპიუტერის აწყობა','სხვა კომპიუტერული მომსახურება'],
 'სხვა':['სხვა დღიური სამუშაო']
};
const popularCategories=[['🧹','დასუფთავება','სახლის დალაგება'],['🐕','ძაღლის გასეირნება','ძაღლის გასეირნება'],['📦','გადატანა / გადაზიდვა','ავეჯის/ნივთების გადატანა'],['👵','ხანდაზმულის დახმარება/მოვლა','ხანდაზმულის დახმარება/მოვლა'],['👶','ძიძა','ბავშვზე ზრუნვა / ძიძა'],['🌱','ბაღის სამუშაოები','ბაღის მოვლა'],['🚗','მიტანა / კურიერი','კურიერი'],['🔨','ხელოსნური სამუშაოები','სხვა ხელოსნური სამუშაო'],['🎉','ღონისძიების დახმარება','ღონისძიების დამხმარე'],['🛒','საყიდლებზე დახმარება','საყიდლებზე წასვლა']];
catOptions=function(selected=''){return '<option value="">აირჩიე კატეგორია</option>'+Object.entries(categoryGroups).map(([group,items])=>`<optgroup label="${group}">${items.map(item=>`<option ${item===selected?'selected':''}>${item}</option>`).join('')}</optgroup>`).join('')};
function modalView(title,subtitle,content,close=true,className=''){return `<div class="modal-backdrop" data-modal-backdrop><section class="modal-card ${className}" role="dialog" aria-modal="true" aria-labelledby="modalTitle">${close?'<button class="modal-close" data-close-modal aria-label="დახურვა">×</button>':''}<span class="eyebrow">Pove24.com · მარტივი დასაწყისი</span><h2 id="modalTitle">${title}</h2><p>${subtitle}</p>${content}</section></div>`}
function startView(){return modalView('განცხადების დასამატებლად საჭიროა შესვლა','შედი ან შექმენი ანგარიში განცხადების დასამატებლად.',`<div class="modal-actions"><a class="btn btn-primary" href="#/login" data-continue-auth>შესვლა</a><a class="btn btn-secondary" href="#/login?register=1" data-continue-auth>რეგისტრაცია</a></div><small class="modal-foot">უკვე გაქვს ანგარიში? <a href="#/login" data-continue-auth>შედი</a></small>`)}
function roleView(){return modalView('რისი გაკეთება გსურთ?','აირჩიე მიზანი — შესაბამის ფორმას მაშინვე გაჩვენებთ.',`<div class="role-options"><a href="#/post?role=hire" class="role-option"><span class="role-option-icon">${dayIcon('users',23)}</span><strong class="role-option-title">ადამიანს ვეძებ</strong><span class="role-option-arrow">${dayIcon('arrowRight',19)}</span><small class="role-option-description">მჭირდება ადამიანი კონკრეტული სამუშაოს შესასრულებლად</small></a><a href="#/worker-form" class="role-option"><span class="role-option-icon">${dayIcon('briefcase',23)}</span><strong class="role-option-title">სამუშაოს ვეძებ</strong><span class="role-option-arrow">${dayIcon('arrowRight',19)}</span><small class="role-option-description">ვეძებ დღიურ ან დროებით სამუშაოს</small></a></div>`,true,'role-modal')}
function allCategoriesView(){return modalView('ყველა კატეგორია','აირჩიე სამუშაოს ტიპი.',`<div class="all-categories">${Object.entries(categoryGroups).map(([group,items])=>`<section><h3>${group}</h3><div>${items.map(item=>`<a href="#/jobs?q=${encodeURIComponent(item)}">${item}<span>→</span></a>`).join('')}</div></section>`).join('')}</div>`)}
function handshakeHeroMarkup(){return `<div class="hero-visual handshake-visual thumbs-visual"><div class="hero-art thumbs-art"><img class="thumbs-hero-poster" src="assets/thumbs-up-hero-20261008.webp" alt="" aria-hidden="true" fetchpriority="high" decoding="async"><video class="thumbs-hero-video" muted loop playsinline preload="none" poster="assets/thumbs-up-hero-20261008.webp" aria-hidden="true" tabindex="-1"><source src="assets/thumbs-up-animation.mp4" type="video/mp4"></video></div></div>`}
function startThumbsMotion(panel){const video=panel?.querySelector('.thumbs-hero-video');if(!video||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;video.muted=true;video.playsInline=true;panel.dataset.motionActive='true';const playback=video.play();if(playback?.then)playback.then(()=>{if(panel.dataset.motionActive==='true')panel.classList.add('is-playing')}).catch(()=>{});else panel.classList.add('is-playing')}
function stopThumbsMotion(panel){if(!panel)return;panel.dataset.motionActive='false';panel.classList.remove('is-playing');const video=panel.querySelector('.thumbs-hero-video');if(video){video.pause();if(video.readyState>0){try{video.currentTime=0}catch{}}}}
document.addEventListener('pointerover',e=>{const panel=e.target.closest('.thumbs-visual');if(!panel||e.pointerType!=='mouse'||panel.contains(e.relatedTarget))return;startThumbsMotion(panel)});
document.addEventListener('pointerout',e=>{const panel=e.target.closest('.thumbs-visual');if(!panel||e.pointerType!=='mouse'||panel.contains(e.relatedTarget))return;stopThumbsMotion(panel)});
const mobileThumbsMotionQuery=window.matchMedia('(max-width: 620px) and (pointer: coarse)');
const reducedMotionQuery=window.matchMedia('(prefers-reduced-motion: reduce)');
const mobileThumbsInViewObserver=mobileThumbsMotionQuery.matches&&'IntersectionObserver' in window?new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting&&entry.intersectionRatio>=.25&&!reducedMotionQuery.matches)startThumbsMotion(entry.target);else stopThumbsMotion(entry.target)})},{threshold:[0,.25]}):null;
const observedMobileThumbs=new Set();
function observeMobileThumbs(root){if(!mobileThumbsInViewObserver||!root)return;const panels=[];if(root.matches?.('.thumbs-visual'))panels.push(root);root.querySelectorAll?.('.thumbs-visual').forEach(panel=>panels.push(panel));panels.forEach(panel=>{if(observedMobileThumbs.has(panel))return;observedMobileThumbs.add(panel);mobileThumbsInViewObserver.observe(panel)})}
if(mobileThumbsInViewObserver){const appRoot=document.getElementById('app');observeMobileThumbs(appRoot);if(appRoot)new MutationObserver(records=>{for(const panel of observedMobileThumbs){if(!panel.isConnected){stopThumbsMotion(panel);mobileThumbsInViewObserver.unobserve(panel);observedMobileThumbs.delete(panel)}}records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)observeMobileThumbs(node)}))}).observe(appRoot,{childList:true,subtree:true});const onReducedMotionChange=()=>observedMobileThumbs.forEach(panel=>{if(reducedMotionQuery.matches)stopThumbsMotion(panel);else{mobileThumbsInViewObserver.unobserve(panel);mobileThumbsInViewObserver.observe(panel)}});reducedMotionQuery.addEventListener?.('change',onReducedMotionChange);if(!reducedMotionQuery.addEventListener)reducedMotionQuery.addListener?.(onReducedMotionChange)}
home=function(){return `<section class="hero"><div class="hero-wrap"><div class="hero-copy"><h1>იპოვე დღიური სამუშაო ან ადამიანი, რომელიც გჭირდება</h1><p>სამუშაოს ეძებ თუ დახმარება გჭირდება?<br>აქ ორივე მხარე მარტივად პოულობს ერთმანეთს.</p><div class="hero-actions"><a class="btn btn-primary" href="#/jobs">💼 სამუშაოს ვეძებ</a><a class="btn btn-secondary" href="#/workers">👤 ადამიანს ვეძებ</a></div><div class="trust-row"><span>დღიური სამუშაოები</span><span>უფასო განცხადებები</span><span>სანდო ადამიანები</span><span>მარტივი პროცესი</span></div></div>${handshakeHeroMarkup()}</div></section><section class="section section-white"><div class="container"><div class="section-heading"><div><span class="eyebrow">იპოვე შენი საქმე</span><h2>პოპულარული კატეგორიები</h2><p>აირჩიე რაც გჭირდება</p></div><button class="text-link text-button" data-all-categories>ყველა კატეგორია →</button></div><div class="categories">${popularCategories.map(([icon,label,term],i)=>`<a class="category" href="#/jobs?q=${encodeURIComponent(term)}"><span class="cat-icon">${icon}</span><span><strong>${label}</strong><small>${jobs.filter(j=>`${j.title} ${j.category}`.toLowerCase().includes(term.toLowerCase())).length||i%5+2} განცხადება</small></span></a>`).join('')}</div></div></section><section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">ახალი შესაძლებლობები</span><h2>ბოლო განცხადებები</h2></div><a class="text-link" href="#/jobs">ყველა განცხადება →</a></div><div class="job-grid">${jobs.slice(0,3).map(jobCard).join('')}</div></div></section><section class="section section-white"><div class="container"><div class="section-heading"><div><span class="eyebrow">მარტივი დასაწყისი</span><h2>როგორ მუშაობს?</h2></div></div><div class="how-grid"><article class="how-item"><span class="step">01</span><h3>აირჩიე რას ეძებ</h3><p>სამუშაოს ეძებ თუ კონკრეტული საქმისთვის ადამიანს.</p></article><article class="how-item"><span class="step">02</span><h3>შეავსე მარტივი ფორმა</h3><p>მიუთითე ქალაქი, თარიღი და საჭირო დეტალები.</p></article><article class="how-item"><span class="step">03</span><h3>დაუკავშირდი ერთმანეთს</h3><p>შეათანხმე საქმე და ანაზღაურება პირდაპირ.</p></article></div><div class="intent-bar"><a class="btn btn-secondary" href="#/jobs">💼 სამუშაოს ვეძებ</a><a class="btn btn-primary" href="#/start">👤 ადამიანს ვეძებ</a></div></div></section>`};
jobsPage=function(){const q=new URLSearchParams(location.hash.split('?')[1]||'');return layout('დღიური სამუშაოს ძებნა','შეარჩიე ქალაქი, უბანი და სამუშაოს ტიპი.',`<form id="filters" class="filter-panel"><div class="field"><label>კატეგორია</label><select name="category">${catOptions(q.get('category')||'')}</select></div><div class="field"><label>ქალაქი</label><input name="city" placeholder="მაგ. თბილისი" value="${esc(q.get('city')||'')}"></div><div class="field"><label>უბანი</label><input name="area" placeholder="მაგ. ვაკე" value="${esc(q.get('area')||'')}"></div><div class="field"><label>თარიღი</label><input name="date" type="date" value="${esc(q.get('date')||'')}"></div><div class="field"><label>მინ. ანაზღაურება (₾)</label><input name="min" type="number" min="0" placeholder="მაგ. 50" value="${esc(q.get('min')||'')}"></div><div class="field"><label>ხანგრძლივობა</label><select name="duration"><option value="">ნებისმიერი</option><option value="4">4 საათამდე</option><option value="8">8 საათამდე</option><option value="9">8 საათზე მეტი</option></select></div><div class="field search-field"><label>რას ეძებ?</label><input name="q" placeholder="ძაღლის გასეირნება, დასუფთავება, გადატანა" value="${esc(q.get('q')||'')}"></div><button class="btn btn-primary" type="submit">ძებნა ⌕</button></form><div id="jobResults"></div>`,'დღიური სამუშაოები საქართველოში')};
updateResults=function(){const form=document.getElementById('filters');if(!form)return;const d=new FormData(form),cat=d.get('category'),city=(d.get('city')||'').toLowerCase(),area=(d.get('area')||'').toLowerCase(),date=d.get('date'),min=Number(d.get('min')||0),dur=d.get('duration'),term=(d.get('q')||'').toLowerCase();const aliases={'სახლის დალაგება':['დასუფთავება'],'გენერალური დასუფთავება':['დასუფთავება'],'ნივთების გადატანა':['გადაზიდვა'],'ბინის გადატანა':['გადაზიდვა'],'ავეჯის გადატანა':['გადაზიდვა'],'ბაღის მოვლა':['ბაღი'],'სამშენებლო სამუშაოების დამხმარე':['მშენებლობა'],'სხვა ხელოსნური სამუშაო':['რემონტი'],'ბავშვზე ზრუნვა / ძიძა':['ძიძა'],'ღონისძიების დამხმარე':['ღონისძიება'],'კურიერი':['კურიერი']};const list=jobs.filter(j=>(!cat||j.category===cat||j.title.toLowerCase().includes(cat.toLowerCase())||(aliases[cat]||[]).some(x=>(j.category+' '+j.title).toLowerCase().includes(x)))&&(!city||(j.city||'').toLowerCase().includes(city))&&(!area||(j.area||'').toLowerCase().includes(area))&&(!date||j.date===date)&&j.pay>=min&&(!dur||((new Date(`1970-01-01T${j.end}:00`)-new Date(`1970-01-01T${j.start}:00`))/3600000<=Number(dur)))&&(!term||`${j.title} ${j.description} ${j.category}`.toLowerCase().includes(term)));document.getElementById('jobResults').innerHTML=`<div class="results-head"><span>ნაპოვნია <strong>${list.length}</strong> განცხადება</span><span>აირჩიე შენი საქმე</span></div>${list.length?`<div class="job-grid">${list.map(jobCard).join('')}</div>`:`<div class="empty"><strong>განცხადებები ვერ მოიძებნა</strong>შეცვალე ფილტრები ან სხვა სიტყვით სცადე ძებნა.<div><button class="btn btn-secondary btn-small" type="button" data-clear-filters>ფილტრების გასუფთავება</button></div></div>`}`};
postPage=function(){return layout('ახალი განცხადების დამატება','მიუთითე სამუშაოს დეტალები და იპოვე შესაფერისი ადამიანი.',`<form class="form-shell" id="postForm"><div class="form-grid"><div class="field"><label>სამუშაოს დასახელება *</label><input name="title" required minlength="3" placeholder="მაგ. ძაღლის გასეირნება"></div><div class="field"><label>კატეგორია *</label><select name="category" required>${catOptions()}</select></div><div class="field span-2"><label>სამუშაოს აღწერა *</label><textarea name="description" required minlength="15" placeholder="აღწერე შესასრულებელი საქმე"></textarea></div><div class="field"><label>ქალაქი *</label><input name="city" required placeholder="მაგ. თბილისი"></div><div class="field"><label>უბანი / მდებარეობა *</label><input name="area" required placeholder="მაგ. ვაკე"></div><div class="field"><label>სამუშაოს თარიღი *</label><input name="date" type="date" required min="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>ანაზღაურება (₾) *</label><input name="pay" type="number" required min="1" placeholder="მაგ. 80"></div><div class="field"><label>დაწყების დრო *</label><input name="start" type="time" required value="09:00"></div><div class="field"><label>დასრულების დრო *</label><input name="end" type="time" required value="17:00"></div><div class="field"><label>ტელეფონი / საკონტაქტო ინფორმაცია *</label><input name="phone" type="tel" required pattern="[+0-9 ()-]{9,}" placeholder="5XX XX XX XX"></div><div class="field"><label>თქვენი სახელი *</label><input name="name" required value="${esc(user?.name||'')}" placeholder="სახელი და გვარი"></div></div><button class="btn btn-primary form-submit">განცხადების გამოქვეყნება →</button><div id="postMessage"></div></form>`,'ადამიანს ვეძებ')};
function workerProfileForm(){return layout('სამუშაოს ძებნის პროფილი','შეავსე პროფილი, რომ დამსაქმებლებმა შესაფერისი საქმე შემოგთავაზონ.',`<form class="form-shell" id="workerProfileForm"><div class="form-grid"><div class="field"><label>სახელი *</label><input name="name" required value="${esc(user?.name||'')}" placeholder="სახელი და გვარი"></div><div class="field"><label>ქალაქი *</label><input name="city" required placeholder="მაგ. თბილისი"></div><div class="field"><label>უბანი *</label><input name="area" required placeholder="მაგ. საბურთალო"></div><div class="field"><label>რისი გაკეთება შემიძლია *</label><select name="skills" required>${catOptions()}</select></div><div class="field"><label>გამოცდილება *</label><input name="exp" required placeholder="მაგ. 2 წელი"></div><div class="field"><label>სასურველი ანაზღაურება (₾ / დღეში) *</label><input name="pay" type="number" required min="1" placeholder="მაგ. 80"></div><div class="field"><label>როდის ვარ ხელმისაწვდომი *</label><select name="availability" required><option value="">აირჩიე</option><option>დღესვე</option><option>ხვალიდან</option><option>ამ კვირაში</option><option>შეთანხმებით</option></select></div><div class="field"><label>საკონტაქტო ინფორმაცია *</label><input name="phone" type="tel" required placeholder="5XX XX XX XX"></div><div class="field span-2"><label>მოკლე აღწერა *</label><textarea name="about" required minlength="15" placeholder="მოგვიყევი შენს გამოცდილებასა და უნარებზე"></textarea></div></div><button class="btn btn-primary form-submit">პროფილის გამოქვეყნება →</button><div id="workerMessage"></div></form>`,'სამუშაოს ვეძებ')}
function routeView(){const hash=location.hash||'#/';const path=hash.slice(1).split('?')[0],params=new URLSearchParams(hash.split('?')[1]||'');document.getElementById('nav').classList.remove('open');if(path==='/')app.innerHTML=home();else if(path==='/start'){if(user){location.hash='#/post-role';return}app.innerHTML=startView()}else if(path==='/post-role')app.innerHTML=user?roleView():startView();else if(path==='/categories')app.innerHTML=allCategoriesView();else if(path==='/jobs')app.innerHTML=jobsPage();else if(path.startsWith('/job/'))app.innerHTML=details(decodeURIComponent(path.split('/')[2]));else if(path==='/post'){if(!user){sessionStorage.setItem('dge-next','1');app.innerHTML=startView()}else app.innerHTML=params.get('role')==='hire'?postPage():roleView()}else if(path==='/worker-form')app.innerHTML=user?workerProfileForm():startView();else if(path==='/workers')app.innerHTML=workersPage();else if(path.startsWith('/worker/'))app.innerHTML=workerDetail(decodeURIComponent(path.split('/')[2]));else if(path==='/login'){app.innerHTML=login();if(params.get('register')==='1')setTimeout(()=>document.querySelector('[data-tab="register"]')?.click(),0)}else if(path==='/dashboard')app.innerHTML=dashboard();else if(path==='/saved')app.innerHTML=savedPage();else if(path==='/profile')app.innerHTML=profilePage();else if(path==='/how')app.innerHTML=home();else app.innerHTML=home();if(path==='/jobs')updateResults();if(path==='/workers'){updateWorkers();document.getElementById('workerSearch')?.addEventListener('click',updateWorkers);document.getElementById('workerCity')?.addEventListener('input',updateWorkers);document.getElementById('workerSkill')?.addEventListener('change',updateWorkers)}if(window.__poveRouteNavigation)window.scrollTo(0,0)}
render=routeView;

document.addEventListener('click',e=>{if(e.target.closest('[data-all-categories]')){location.hash='#/categories';return}if(e.target.closest('[data-close-modal]')||e.target.matches('[data-modal-backdrop]')){location.hash='#/';return}if(e.target.closest('[data-continue-auth]'))sessionStorage.setItem('dge-next','1')});
document.addEventListener('submit',e=>{if(e.target.id==='workerProfileForm'&&!e.target.querySelector('[data-cat-main]')){e.preventDefault();const f=new FormData(e.target),createdAt=Date.now(),w={id:'w'+createdAt,createdAt,name:f.get('name'),city:f.get('city'),area:f.get('area'),skills:[f.get('skills')],exp:f.get('exp'),pay:Number(f.get('pay')),availability:f.get('availability'),about:f.get('about'),phone:f.get('phone'),initials:f.get('name').split(' ').map(x=>x[0]).slice(0,2).join('')};const all=get('dge-workers',[]);all.unshift(w);set('dge-workers',all);document.getElementById('workerMessage').innerHTML='<div class="success-box">პროფილი გამოქვეყნდა.</div>';setTimeout(()=>location.hash='#/workers',600)}});

updateWorkers=function(){const el=document.getElementById('workerResults');if(!el)return;const city=(document.getElementById('workerCity')?.value||'').toLowerCase(),skill=document.getElementById('workerSkill')?.value||'',people=[...get('dge-workers',[]),...seedWorkers],matches=people.filter(w=>(!city||`${w.city} ${w.area}`.toLowerCase().includes(city))&&(!skill||w.skills.some(s=>s===skill||s.toLowerCase().includes(skill.toLowerCase()))));el.innerHTML=matches.length?matches.map(workerCard).join(''):`<div class="empty" style="grid-column:1/-1"><strong>ადამიანები ვერ მოიძებნა</strong>ცადე სხვა ქალაქი ან კატეგორია.</div>`};
workerDetail=function(id){const w=[...get('dge-workers',[]),...seedWorkers].find(x=>x.id===id);if(!w)return layout('პროფილი ვერ მოიძებნა','','<div class="empty">პროფილი მიუწვდომელია.</div>');const payLabel=w.paymentType==='negotiable'?'ანაზღაურება':w.paymentType==='hourly'?'საათობრივი ანაზღაურება':w.paymentType==='fixed'?'ფიქსირებული ანაზღაურება':'დღიური ანაზღაურება',location=[w.city,w.area||w.district||'ყველა უბანი'].filter(Boolean).map(esc).join(' · ');return `<section class="container"><div class="page-head"><a href="#/workers" class="text-link">← ადამიანების ძებნაზე დაბრუნება</a></div><div class="detail-layout"><article class="detail-main"><div class="worker-profile-heading">${Avatar(w,'profile')}<div><h1>${esc(w.name)}</h1><div class="meta">⌖ ${location}</div></div></div><h3>უნარები</h3><div class="skills" style="justify-content:flex-start">${w.skills.map(s=>`<span class="skill">${esc(s)}</span>`).join('')}</div><h3>ჩემ შესახებ</h3><p>${esc(w.about)}</p><h3>გამოცდილება</h3><p>${esc(w.exp)} სამუშაო გამოცდილება.</p><h3>წინა სამუშაოები და შეფასებები</h3><div class="notice">შეფასებები მალე დაემატება.</div></article><aside class="profile-box"><h3>სამუშაო პირობები</h3><div class="worker-stats" style="text-align:left"><span><strong>${esc(workerPayLabel(w))}</strong>${payLabel}</span><span><strong>${esc(w.availability)}</strong>ხელმისაწვდომია</span></div><button class="btn btn-primary" data-worker-contact="${esc(w.id)}">დაკავშირება</button></aside></div></section>`};


