/* Accessible keyboard and clear-button behavior for the existing searchable city/district controls. */
function prepareLocationCombobox(input){const box=input.parentElement?.querySelector('[data-location-suggestions]');if(!box)return;input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-haspopup','listbox');box.setAttribute('role','listbox');if(!box.id)box.id='list-'+(input.id||Math.random().toString(36).slice(2));input.setAttribute('aria-controls',box.id);let clear=input.parentElement.querySelector('.location-clear');if(!clear){clear=document.createElement('button');clear.type='button';clear.className='location-clear';clear.setAttribute('aria-label','ველის გასუფთავება');clear.innerHTML=dayIcon('xCircle',15);input.insertAdjacentElement('afterend',clear)}clear.classList.toggle('visible',!!input.value)}
function syncLocationOptions(input){const box=input.parentElement.querySelector('[data-location-suggestions]');if(!box)return;const options=[...box.querySelectorAll('[data-location-option]')];options.forEach((option,i)=>{if(!option.id)option.id=box.id+'-option-'+i;option.setAttribute('aria-selected',String(option.dataset.locationOption===input.value));option.classList.toggle('is-selected',option.dataset.locationOption===input.value)})}
document.querySelectorAll('[data-location-role]').forEach(prepareLocationCombobox);
document.addEventListener('focusin',e=>{const input=e.target.closest('[data-location-role]');if(input){prepareLocationCombobox(input);requestAnimationFrame(()=>syncLocationOptions(input))}});
document.addEventListener('input',e=>{const input=e.target.closest('[data-location-role]');if(input){prepareLocationCombobox(input);requestAnimationFrame(()=>syncLocationOptions(input))}});
document.addEventListener('click',e=>{const clear=e.target.closest('.location-clear');if(clear){e.preventDefault();e.stopPropagation();const input=clear.parentElement.querySelector('[data-location-role]');if(!input)return;input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();return}const option=e.target.closest('[data-location-option]');if(option){const input=option.closest('.location-control')?.querySelector('[data-location-role]');if(input)requestAnimationFrame(()=>{input.focus();prepareLocationCombobox(input);const list=input.parentElement.querySelector('[data-location-suggestions]');if(list){list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant')}})}else if(!e.target.closest('.location-control'))document.querySelectorAll('[data-location-suggestions]:not([hidden])').forEach(box=>{box.hidden=true;const input=box.parentElement.querySelector('[data-location-role]');input?.setAttribute('aria-expanded','false');input?.removeAttribute('aria-activedescendant')})});
document.addEventListener('keydown',e=>{const input=e.target.closest('[data-location-role]');if(!input)return;const box=input.parentElement.querySelector('[data-location-suggestions]');if(!box)return;let options=[...box.querySelectorAll('[data-location-option]')];if(e.key==='Escape'){if(!box.hidden){e.preventDefault();box.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant')}return}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(box.hidden)renderLocationChoices(input);syncLocationOptions(input);options=[...box.querySelectorAll('[data-location-option]')];if(!options.length)return;let index=options.findIndex(x=>x.classList.contains('is-active'));index=e.key==='ArrowDown'?(index+1)%options.length:(index<=0?options.length-1:index-1);options.forEach((x,i)=>x.classList.toggle('is-active',i===index));input.setAttribute('aria-activedescendant',options[index].id);options[index].scrollIntoView({block:'nearest'});return}if(e.key==='Enter'&&!box.hidden&&options.length){e.preventDefault();const active=options.find(x=>x.classList.contains('is-active'))||options[0];active.click()}});
document.addEventListener('keydown',e=>{const input=e.target.closest('[data-cat-search]');if(!input)return;const box=input.closest('[data-category-picker]'),menu=box?.querySelector('[data-cat-options]'),options=[...(menu?.querySelectorAll('.category-option')||[])];if(e.key==='Escape'){e.preventDefault();box.querySelector('.category-popover').hidden=true;box.querySelector('[data-cat-toggle]')?.setAttribute('aria-expanded','false');box.querySelector('[data-cat-toggle]')?.focus();return}if(e.key==='ArrowDown'||e.key==='ArrowUp'){if(!options.length)return;e.preventDefault();let i=options.findIndex(x=>x.classList.contains('is-active'));i=e.key==='ArrowDown'?(i+1)%options.length:(i<=0?options.length-1:i-1);options.forEach((x,n)=>x.classList.toggle('is-active',n===i));options[i].scrollIntoView({block:'nearest'});return}if(e.key==='Enter'){const active=options.find(x=>x.classList.contains('is-active'));if(active){e.preventDefault();active.click()}}});


new MutationObserver(records=>records.forEach(r=>r.addedNodes.forEach(n=>{if(n.nodeType===1){if(n.matches('[data-location-role]'))prepareLocationCombobox(n);n.querySelectorAll?.('[data-location-role]').forEach(prepareLocationCombobox)}}))).observe(document.body,{childList:true,subtree:true});

