const profileSavesKey='dge-saved-profiles-users';
let profileSavesByUser=get(profileSavesKey,{}),profileSavesAccount=user?.email||null,savedProfileIds=profileSavesAccount?[...(profileSavesByUser[profileSavesAccount]||[])]:[];
const profileActionIcon=(name,size=18)=>dayIcon(name,size,'profile-action-icon');
function syncProfileSaves(){const account=user?.email||null;if(account===profileSavesAccount)return;if(profileSavesAccount){profileSavesByUser[profileSavesAccount]=[...savedProfileIds];set(profileSavesKey,profileSavesByUser)}profileSavesAccount=account;savedProfileIds=account?[...(profileSavesByUser[account]||[])]:[]}
function saveProfileIds(){if(!user)return;profileSavesByUser[user.email]=[...savedProfileIds];set(profileSavesKey,profileSavesByUser)}
function profileSaveButtonMarkup(profile,id,route){
 const self=!!user?.email&&(profile.owner===user.email||profile.email===user.email||id===user.email);
 if(self)return '';
 const saved=savedProfileIds.includes(id),label=saved?'პროფილი შენახულია':'შენახვა';
 return '<button class="profile-save-button profile-save-header'+(saved?' is-saved':'')+'" type="button" data-profile-save="'+esc(id)+'" data-profile-route="'+esc(route)+'" aria-label="'+label+'" title="'+label+'" aria-pressed="'+saved+'">'+profileActionIcon('heart',19)+'<span class="profile-save-label">'+(saved?'შენახულია':'შენახვა')+'</span></button>'
}
function refreshProfileSaveButtons(){document.querySelectorAll('[data-profile-save]').forEach(button=>{const isSaved=savedProfileIds.includes(button.dataset.profileSave),label=isSaved?'პროფილი შენახულია':'შენახვა';button.classList.toggle('is-saved',isSaved);button.setAttribute('aria-pressed',String(isSaved));button.setAttribute('aria-label',label);button.title=label;button.innerHTML=profileActionIcon('heart',19)+'<span class="profile-save-label">'+(isSaved?'შენახულია':'შენახვა')+'</span>'})}
function profileActionMarkup({id,route,name,recipient,workerId='',profileEmail='',isSelf=false}){
 if(isSelf)return '<p class="profile-self-note">ეს შენი პროფილია.</p>';
 const saved=savedProfileIds.includes(id),workerAttr=workerId?' data-profile-reveal-worker="'+esc(workerId)+'"':'',emailAttr=profileEmail?' data-profile-reveal-user="'+esc(profileEmail)+'"':'';
 const contactPanelId='profile-contact-'+String(id).replace(/[^a-zA-Z0-9_-]/g,'-');
 return '<div class="profile-contact-wrap"><button class="btn btn-primary profile-contact-toggle" type="button" data-profile-contact-toggle aria-haspopup="true" aria-expanded="false" aria-controls="'+contactPanelId+'">'+profileActionIcon('phone',18)+'<span>დაკავშირება</span>'+profileActionIcon('chevronDown',16)+'</button><div class="profile-contact-panel" id="'+contactPanelId+'" data-profile-contact-panel hidden><button type="button" class="profile-contact-option" data-open-profile-chat="'+esc(id)+'" data-profile-route="'+esc(route)+'" data-profile-recipient="'+esc(recipient)+'" data-profile-name="'+esc(name)+'">'+profileActionIcon('message',18)+'<span>მიწერა</span>'+profileActionIcon('chevronRight',16)+'</button><button type="button" class="profile-contact-option" data-profile-reveal-phone=""'+workerAttr+emailAttr+'>'+profileActionIcon('phone',18)+'<span>ნომრის ნახვა</span>'+profileActionIcon('chevronRight',16)+'</button></div></div>'
}
function workerById(id){return [...get('dge-workers',[]),...seedWorkers].find(worker=>String(worker.id)===String(id))}
revealPhone=function(button,phone){if(!phone){notify('ტელეფონის ნომერი მითითებული არ არის.');return}const box=document.createElement('div');box.className='revealed-phone';box.innerHTML='<strong>'+profileActionIcon('phone',18)+'<span>'+esc(phone)+'</span></strong><a class="btn btn-primary" href="tel:'+esc(normalizedPhone(phone))+'">'+profileActionIcon('phone',17)+'<span>დარეკვა</span></a><button class="btn btn-secondary" type="button" data-copy-phone="'+esc(phone)+'">'+profileActionIcon('copy',17)+'<span>ნომრის დაკოპირება</span></button>';button.insertAdjacentElement('afterend',box);button.remove()};
function workerProfileActionsMarkup(worker,id=worker.owner||worker.email||worker.id,route='#/worker/'+encodeURIComponent(worker.id)){
 const isWorker=get('dge-workers',[]).some(row=>row.id===worker.id)||seedWorkers.some(row=>row.id===worker.id),self=!!user?.email&&(worker.owner===user.email||worker.email===user.email),recipient=worker.owner||worker.email||'worker:'+worker.id;
 return profileActionMarkup({id,route,name:worker.name||'მომხმარებელი',recipient,workerId:isWorker?worker.id:'',profileEmail:isWorker?'':worker.email||'',isSelf:self})
}
function jobContactMenuMarkup(job){const id=String(job.id),panelId='job-contact-'+id.replace(/[^a-zA-Z0-9_-]/g,'-'),recipient=job.owner||`poster:${id}`,name=job.name||'განცხადების ავტორი';return '<div class="profile-contact-wrap job-contact-wrap"><button class="btn btn-primary profile-contact-toggle" type="button" data-profile-contact-toggle aria-haspopup="true" aria-expanded="false" aria-controls="'+panelId+'">'+profileActionIcon('phone',18)+'<span>დაკავშირება</span>'+profileActionIcon('chevronDown',16)+'</button><div class="profile-contact-panel" id="'+panelId+'" data-profile-contact-panel hidden><button type="button" class="profile-contact-option" data-open-chat="'+esc(id)+'" data-chat-with="'+esc(recipient)+'" data-chat-name="'+esc(name)+'">'+profileActionIcon('message',18)+'<span>მიწერა</span>'+profileActionIcon('chevronRight',16)+'</button><button type="button" class="profile-contact-option" data-reveal-job-phone="'+esc(id)+'">'+profileActionIcon('phone',18)+'<span>ნომრის ნახვა</span>'+profileActionIcon('chevronRight',16)+'</button></div></div>'}
const jobDetailsWithContactMenu=details;details=function(id){let html=jobDetailsWithContactMenu(id),job=jobs.find(row=>String(row.id)===String(id));if(!job||(user?.email&&job.owner===user.email))return html;return html.replace(/<p class="contact-prompt">[\s\S]*?<\/p><button class="btn btn-primary" data-reveal-job-phone="[^"]+">დაკავშირება<\/button>/,jobContactMenuMarkup(job))};const workerDetailWithProfileActions=workerDetail;
workerDetail=function(id){let html=workerDetailWithProfileActions(id),worker=workerById(id);if(!worker)return html;const key=worker.owner||worker.email||worker.id,route='#/worker/'+encodeURIComponent(worker.id),match=html.match(/<p class="contact-prompt">[^<]*<\/p><button class="btn btn-primary" data-reveal-worker-phone="[^"]+">დაკავშირება<\/button>/);if(match)html=html.replace(match[0],workerProfileActionsMarkup(worker,key,route));html=html.replace('<div class="worker-profile-heading">','<div class="worker-profile-heading profile-save-anchor">');return html.replace('</div></div><h3>უნარები</h3>',`</div>${profileSaveButtonMarkup(worker,key,route)}</div><h3>უნარები</h3>`)};
const workerCardWithRatings=workerCard;
workerCard=function(worker){let html=workerCardWithRatings(worker),id=worker.owner||worker.email||worker.id,route='#/worker/'+encodeURIComponent(worker.id);html=html.replace('<article class="worker-card">','<article class="worker-card profile-save-anchor">');return html.replace('<article class="worker-card profile-save-anchor">',`<article class="worker-card profile-save-anchor">${profileSaveButtonMarkup(worker,id,route)}`)};
const publicProfileWithActions=publicUserProfile;
publicUserProfile=function(email){let html=publicProfileWithActions(email),account=get('dge-accounts',[]).find(row=>row.email===email),worker=get('dge-workers',[]).find(row=>row.owner===email||row.email===email);if(!account&&!worker)return html;const profile=worker||{id:'user-'+email,owner:email,email,name:account?.name||'მომხმარებელი',phone:account?.phone},route='#/user/'+encodeURIComponent(email),actions=workerProfileActionsMarkup(profile,email,route);const existing=html.match(/<aside class="profile-box public-contact-box">[\s\S]*?<\/aside>/);if(existing)html=html.replace(existing[0],actions);else{const reportAt=html.indexOf('<button class="report-link public-report"');html=reportAt>=0?html.slice(0,reportAt)+actions+html.slice(reportAt):html.replace('</section>',actions+'</section>')}html=html.replace('<div class="page-head public-profile-heading">','<div class="page-head public-profile-heading profile-save-anchor">');return html.replace('</div></div><div class="public-profile-card">',`</div>${profileSaveButtonMarkup(profile,email,route)}</div><div class="public-profile-card">`)};
function openProfileSaveModal(button){saveModal(button.dataset.profileSave);const modal=document.querySelector('[data-save-modal]');if(!modal)return;modal.dataset.saveType='profile';modal.dataset.profile=button.dataset.profileSave;modal.dataset.returnPath=button.dataset.profileRoute||('#/worker/'+encodeURIComponent(button.dataset.profileSave));modal.querySelector('#saveModalTitle').textContent='პროფილის შესანახად საჭიროა შესვლა';modal.querySelector('p').textContent='შედი ან შექმენი ანგარიში შენახული პროფილების სამართავად.'}
function toggleProfileSave(id){if(!user)return false;const profile=[...get('dge-workers',[]),...seedWorkers].find(worker=>(worker.owner||worker.email||worker.id)===id),self=id===user.email||!!profile&&(profile.owner===user.email||profile.email===user.email);if(self){notify('საკუთარი პროფილის შენახვა შეუძლებელია.');return false}savedProfileIds=savedProfileIds.includes(id)?savedProfileIds.filter(savedId=>savedId!==id):[...savedProfileIds,id];saveProfileIds();refreshProfileSaveButtons();accountNavigation?.();notify(savedProfileIds.includes(id)?'პროფილი შენახულია':'პროფილი შენახულებიდან წაიშალა');return true}
function resolveProfileRecipient(profileId,recipientHint=''){
 const worker=[...get('dge-workers',[]),...seedWorkers].find(row=>String(row.id)===String(profileId)||(row.owner||row.email)===profileId),account=get('dge-accounts',[]).find(row=>row.email===profileId||row.email===recipientHint);
 return {worker,account,recipient:worker?.owner||worker?.email||account?.email||recipientHint||`worker:${profileId}`,name:worker?.name||account?.name||'მომხმარებელი'}
}
function beginProfileConversation(profileId,recipientHint='',nameHint=''){
 if(!user){sessionStorage.setItem('dge-pending-profile-chat',JSON.stringify({profileId,recipientHint,nameHint}));sessionStorage.setItem('dge-return',location.hash||('#/worker/'+encodeURIComponent(profileId)));location.hash='#/login';return}
 const profile=resolveProfileRecipient(profileId,recipientHint),recipient=profile.recipient,name=nameHint||profile.name;
 if(!recipient||recipient===user.email){notify('საკუთარ თავს ვერ მისწერ.');return}
 const conversationJobId='profile:'+profileId,key=chatKey(conversationJobId,user.email,recipient),rows=get(chatStoreKey,[]);let conversation=rows.find(row=>row.key===key);
 if(!conversation){conversation={key,jobId:conversationJobId,jobTitle:'საუბარი · '+name,participants:[user.email,recipient],names:{[user.email]:user.name,[recipient]:name},messages:[]};rows.push(conversation);set(chatStoreKey,rows)}
 location.hash='#/messages?job='+encodeURIComponent(conversationJobId)+'&with='+encodeURIComponent(recipient)
}
function completeProfileIntents(){if(!user)return;syncProfileSaves();const pendingSave=sessionStorage.getItem('dge-pending-profile-save');if(pendingSave){sessionStorage.removeItem('dge-pending-profile-save');const data=JSON.parse(pendingSave);toggleProfileSave(data.id)}const pendingChat=sessionStorage.getItem('dge-pending-profile-chat');if(pendingChat){sessionStorage.removeItem('dge-pending-profile-chat');const data=JSON.parse(pendingChat);beginProfileConversation(data.profileId,data.recipientHint,data.nameHint);return}refreshProfileSaveButtons()}
document.addEventListener('click',event=>{
 const save=event.target.closest('[data-profile-save]');if(save){event.preventDefault();event.stopImmediatePropagation();syncProfileSaves();if(!user){openProfileSaveModal(save);return}toggleProfileSave(save.dataset.profileSave);return}
 const auth=event.target.closest('[data-save-auth]'),modal=auth?.closest('[data-save-modal]');if(auth&&modal?.dataset.saveType==='profile'){event.preventDefault();event.stopImmediatePropagation();sessionStorage.setItem('dge-pending-profile-save',JSON.stringify({id:modal.dataset.profile}));sessionStorage.setItem('dge-return',modal.dataset.returnPath);modal.remove();location.hash=auth.dataset.saveAuth==='register'?'#/login?register=1':'#/login';return}
 const chat=event.target.closest('[data-open-profile-chat]');if(chat){event.preventDefault();event.stopImmediatePropagation();const profile=resolveProfileRecipient(chat.dataset.openProfileChat,chat.dataset.profileRecipient),recipient=chat.dataset.profileRecipient||profile.recipient;if(user&&recipient===user.email){notify('საკუთარ თავს ვერ მისწერ.');return}beginProfileConversation(chat.dataset.openProfileChat,recipient,chat.dataset.profileName||profile.name);return}
 const toggle=event.target.closest('[data-profile-contact-toggle]');if(toggle){event.preventDefault();event.stopImmediatePropagation();const wrap=toggle.closest('.profile-contact-wrap'),panel=wrap?.querySelector('[data-profile-contact-panel]'),open=toggle.getAttribute('aria-expanded')==='true';document.querySelectorAll('.profile-contact-wrap').forEach(other=>{if(other===wrap)return;other.querySelector('[data-profile-contact-toggle]')?.setAttribute('aria-expanded','false');const otherPanel=other.querySelector('[data-profile-contact-panel]');if(otherPanel)otherPanel.hidden=true});if(panel){toggle.setAttribute('aria-expanded',String(!open));panel.hidden=open}return}
 if(!event.target.closest('.profile-contact-wrap'))document.querySelectorAll('.profile-contact-wrap').forEach(wrap=>{wrap.querySelector('[data-profile-contact-toggle]')?.setAttribute('aria-expanded','false');const panel=wrap.querySelector('[data-profile-contact-panel]');if(panel)panel.hidden=true});
},true);
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;document.querySelectorAll('.profile-contact-wrap').forEach(wrap=>{const toggle=wrap.querySelector('[data-profile-contact-toggle]'),panel=wrap.querySelector('[data-profile-contact-panel]');if(toggle?.getAttribute('aria-expanded')==='true'){toggle.setAttribute('aria-expanded','false');if(panel)panel.hidden=true;toggle.focus()}})});
document.addEventListener('click',event=>{const reveal=event.target.closest('[data-profile-reveal-phone]');if(!reveal)return;const workerId=reveal.dataset.profileRevealWorker,email=reveal.dataset.profileRevealUser,worker=workerId?workerById(workerId):null,account=email?get('dge-accounts',[]).find(row=>row.email===email):null;revealPhone(reveal,worker?.phone||account?.phone)},true);
document.addEventListener('click',event=>{if(event.target.closest('[data-close-social]')){sessionStorage.removeItem('dge-pending-profile-save');sessionStorage.removeItem('dge-pending-profile-chat')}});
const savedPageWithWorkerProfiles=savedPage;
function savedProfileCard(profile){const route='#/user/'+encodeURIComponent(profile.email);return '<article class="worker-card saved-profile-card profile-save-anchor">'+profileSaveButtonMarkup(profile,profile.email,route)+Avatar(profile,'lg')+'<h3>'+esc(profile.name||'მომხმარებელი')+'</h3><p>'+[profile.city,profile.area].filter(Boolean).map(esc).join(' · ')+'</p><a class="btn btn-secondary btn-small" style="margin-top:14px;width:100%" href="'+route+'">პროფილის ნახვა</a></article>'}
savedPage=function(){let html=savedPageWithWorkerProfiles();if(!user)return html;syncProfileSaves();const workers=[...get('dge-workers',[]),...seedWorkers],profiles=workers.filter((worker,index,rows)=>{const key=worker.owner||worker.email||worker.id;return savedProfileIds.includes(key)&&rows.findIndex(other=>(other.owner||other.email||other.id)===key)===index}),workerKeys=new Set(profiles.map(worker=>worker.owner||worker.email||worker.id)),accounts=get('dge-accounts',[]).filter(account=>savedProfileIds.includes(account.email)&&!workerKeys.has(account.email)),cards=[...profiles.map(workerCard),...accounts.map(savedProfileCard)];if(!cards.length)return html;const section='<section class="saved-profiles-section"><div class="section-heading"><h2>შენახული პროფილები</h2></div><div class="worker-grid">'+cards.join('')+'</div></section>';return html.replace('</section>',section+'</section>')};
const socialRouteWithProfiles=routeView;
routeView=function(){syncProfileSaves();socialRouteWithProfiles();completeProfileIntents()};
render=routeView;window.addEventListener('hashchange',()=>setTimeout(completeProfileIntents,0));routeView();
