const profileMediaIcons={camera:'<path d="M14 4h-4l-2 3H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2-3Z"/><circle cx="12" cy="13" r="3.5"/>',edit:'<path d="m16 4 4 4M4 20l4-.8L20 7a2.8 2.8 0 0 0-4-4L4.8 15.2 4 20Z"/>',trash:'<path d="M3 6h18m-2 0-1 15H6L5 6m4 0V4h6v2m-5 4v7m4-7v7"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>'};
function profileMediaIcon(name){return '<svg class="day-icon" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.85" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(profileMediaIcons[name]||profileMediaIcons.camera)+'</svg>'}
function profilePhotoEditor(profile={},scope='profile'){
 const photo=profile.profilePhoto||profile.avatarUrl||profile.photoUrl||'',gender=profile.gender||'unspecified',current={...profile,profilePhoto:photo,gender};
 return '<div class="profile-photo-editor" data-photo-widget data-photo-scope="'+scope+'"><div class="profile-photo-current" data-photo-current>'+Avatar(current,scope==='registration'?'lg':'profile','profile-photo-avatar')+'</div><input type="hidden" name="profilePhoto" data-photo-value value="'+avatarEscape(photo)+'"><input class="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" data-photo-file><div class="profile-photo-actions"><button class="btn btn-secondary" type="button" data-photo-pick>'+profileMediaIcon(photo?'edit':'camera')+'<span>'+(photo?'ფოტოს შეცვლა':'პროფილის ფოტოს დამატება')+'</span></button>'+(scope==='registration'?'<button class="photo-skip" type="button" data-photo-skip>ახლა არა</button>':'')+'<button class="btn btn-ghost photo-delete" type="button" data-photo-delete '+(photo?'':'hidden')+'>'+profileMediaIcon('trash')+'<span>ფოტოს წაშლა</span></button></div><div class="profile-photo-preview" data-photo-preview hidden><div data-photo-preview-avatar></div><p>ახალი ფოტო</p><div><button class="btn btn-primary" type="button" data-photo-save>'+profileMediaIcon('check')+'<span>შენახვა</span></button><button class="btn btn-secondary" type="button" data-photo-cancel>'+profileMediaIcon('close')+'<span>გაუქმება</span></button></div></div><p class="profile-photo-hint">JPG, PNG ან WEBP · მაქს. 8 მბ</p></div>'
}
function profileGenderOptions(value='unspecified',custom=false){
 const selected=value||'unspecified',options=[['unspecified','არ მინდა მითითება'],['female','ქალი'],['male','კაცი']];
 if(!custom)return '<div class="field"><label for="profile-gender">სქესი</label><select id="profile-gender" name="gender">'+options.map(([v,label])=>'<option value="'+v+'" '+(selected===v?'selected':'')+'>'+label+'</option>').join('')+'</select></div>';
 const current=options.find(([v])=>v===selected)||options[0];return '<div class="field auth-gender-field"><label id="profile-gender-label" for="profile-gender-trigger">სქესი</label><div class="site-select" data-gender-select><select class="site-select-native visually-hidden" name="gender" tabindex="-1" aria-hidden="true">'+options.map(([v,label])=>'<option value="'+v+'" '+(selected===v?'selected':'')+'>'+label+'</option>').join('')+'</select><button id="profile-gender-trigger" class="site-select-trigger" type="button" role="combobox" aria-labelledby="profile-gender-label profile-gender-value" aria-expanded="false" aria-controls="profile-gender-options" aria-haspopup="listbox"><span id="profile-gender-value" data-gender-value>'+current[1]+'</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><div class="site-select-options" id="profile-gender-options" role="listbox" aria-labelledby="profile-gender-label" hidden>'+options.map(([v,label])=>'<button class="site-select-option" type="button" role="option" data-gender-option="'+v+'" aria-selected="'+(selected===v)+'" tabindex="-1">'+label+'</button>').join('')+'</div></div></div>'
}
function registrationProfileFields(){return '<div class="field"><label for="registration-phone">ტელეფონი <span class="optional-label">არასავალდებულო</span></label><input id="registration-phone" name="phone" type="tel" placeholder="5XX XX XX XX"></div>'+profileGenderOptions('unspecified',true)+'<section class="registration-photo-section" data-registration-photo><h3>პროფილის ფოტო</h3>'+profilePhotoEditor({gender:'unspecified'},'registration')+'</section>'}
function photoWidgetProfile(widget,photo){const form=widget.closest('form'),gender=form?.elements.gender?.value||user?.gender||'unspecified',name=form?.elements.name?.value||user?.name||'';return{...(user||{}),name,gender,profilePhoto:photo||null}}
function updatePhotoWidget(widget,photo){const p=photoWidgetProfile(widget,photo),avatar=widget.querySelector('[data-photo-current]');if(avatar)avatar.innerHTML=Avatar(p,widget.dataset.photoScope==='registration'?'lg':'profile','profile-photo-avatar');const remove=widget.querySelector('[data-photo-delete]');if(remove)remove.hidden=!photo;const pick=widget.querySelector('[data-photo-pick]');if(pick){pick.innerHTML=profileMediaIcon(photo?'edit':'camera')+'<span>'+(photo?'ფოტოს შეცვლა':'პროფილის ფოტოს დამატება')+'</span>'}}
async function persistProfileField(key,value){if(!user)return false;try{const savedValue=key==='profilePhoto'&&typeof value==='string'&&value.startsWith('data:image/')?await Pove24Store.uploadProfilePhoto(value):value;user={...user,[key]:savedValue};set('dge-user',user);if(key==='profilePhoto')document.querySelectorAll('[data-photo-widget] [data-photo-value]').forEach(input=>{input.value=savedValue||''});refreshAvatars?.();await Pove24Store.flush();return true}catch(error){notify(error.message||'პროფილის შენახვა ვერ მოხერხდა.');return false}}
function fileAsDataUrl(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('ფაილის წაკითხვა ვერ მოხერხდა.'));reader.readAsDataURL(blob)})}
async function compressProfilePhoto(file){
 if(!file)return null;const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type.toLowerCase()))throw Error('აირჩიე JPG, PNG ან WEBP ფორმატის ფოტო.');if(file.size>8*1024*1024)throw Error('ფოტოს ზომა 8 მბ-ს არ უნდა აღემატებოდეს.');
 let bitmap;try{bitmap=await createImageBitmap(file)}catch{throw Error('ფოტოს გახსნა ვერ მოხერხდა. აირჩიე სხვა ფაილი.')}
 const scale=Math.min(1,384/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();
 const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82))||await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!blob)throw Error('ფოტოს დამუშავება ვერ მოხერხდა.');return fileAsDataUrl(blob)
}
let pendingPhotoDeleteWidget=null;
function showPhotoDeleteConfirmation(widget){pendingPhotoDeleteWidget=widget;document.querySelector('[data-photo-delete-modal]')?.remove();document.body.insertAdjacentHTML('beforeend','<div class="modal-backdrop photo-delete-backdrop" data-photo-delete-modal><section class="modal-card photo-delete-dialog" role="dialog" aria-modal="true" aria-labelledby="photo-delete-title"><button class="modal-close" type="button" data-photo-delete-cancel aria-label="დახურვა">'+profileMediaIcon('close')+'</button><h2 id="photo-delete-title">დარწმუნებული ხარ, რომ გსურს პროფილის ფოტოს წაშლა?</h2><div class="photo-delete-actions"><button type="button" class="btn btn-secondary" data-photo-delete-cancel>გაუქმება</button><button type="button" class="btn btn-danger" data-photo-delete-confirm>'+profileMediaIcon('trash')+'<span>ფოტოს წაშლა</span></button></div></section></div>');document.querySelector('[data-photo-delete-cancel]')?.focus()}
function closePhotoDeleteConfirmation(){document.querySelector('[data-photo-delete-modal]')?.remove();pendingPhotoDeleteWidget=null}
document.addEventListener('click',e=>{
 const pick=e.target.closest('[data-photo-pick]');if(pick){pick.closest('[data-photo-widget]')?.querySelector('[data-photo-file]')?.click();return}
 const skip=e.target.closest('[data-photo-skip]');if(skip){const widget=skip.closest('[data-photo-widget]');widget.querySelector('[data-photo-value]').value='';widget.querySelector('[data-photo-file]').value='';widget.dataset.pendingPhoto='';widget.querySelector('[data-photo-preview]').hidden=true;updatePhotoWidget(widget,'');return}
 const save=e.target.closest('[data-photo-save]');if(save){const widget=save.closest('[data-photo-widget]'),photo=widget.dataset.pendingPhoto;if(!photo)return;widget.querySelector('[data-photo-value]').value=photo;widget.dataset.pendingPhoto='';widget.querySelector('[data-photo-preview]').hidden=true;updatePhotoWidget(widget,photo);if(widget.dataset.photoScope!=='registration')persistProfileField('profilePhoto',photo).then(ok=>{if(ok)notify('პროფილის ფოტო განახლდა')});return}
 const cancel=e.target.closest('[data-photo-cancel]');if(cancel){const widget=cancel.closest('[data-photo-widget]');widget.dataset.pendingPhoto='';widget.querySelector('[data-photo-file]').value='';widget.querySelector('[data-photo-preview]').hidden=true;updatePhotoWidget(widget,widget.querySelector('[data-photo-value]').value);return}
 const remove=e.target.closest('[data-photo-delete]');if(remove){const widget=remove.closest('[data-photo-widget]');if(widget?.querySelector('[data-photo-value]').value)showPhotoDeleteConfirmation(widget);return}
 if(e.target.closest('[data-photo-delete-cancel]')||e.target.matches('[data-photo-delete-modal]')){closePhotoDeleteConfirmation();return}
 if(e.target.closest('[data-photo-delete-confirm]')){const widget=pendingPhotoDeleteWidget;if(widget){widget.querySelector('[data-photo-value]').value='';widget.querySelector('[data-photo-file]').value='';widget.dataset.pendingPhoto='';widget.querySelector('[data-photo-preview]').hidden=true;updatePhotoWidget(widget,'');if(widget.dataset.photoScope!=='registration')persistProfileField('profilePhoto',null).then(ok=>{if(ok)notify('პროფილის ფოტო წაიშალა')})}closePhotoDeleteConfirmation()}
});
document.addEventListener('change',async e=>{
 if(e.target.matches('[data-photo-file]')){const input=e.target,widget=input.closest('[data-photo-widget]'),preview=widget.querySelector('[data-photo-preview]');if(!input.files?.[0])return;try{widget.dataset.pendingPhoto=await compressProfilePhoto(input.files[0]);widget.querySelector('[data-photo-preview-avatar]').innerHTML=Avatar(photoWidgetProfile(widget,widget.dataset.pendingPhoto),'lg','profile-photo-preview-avatar');preview.hidden=false}catch(error){notify(error.message);input.value=''}return}
 if(e.target.matches('select[name="gender"]'))document.querySelectorAll('[data-photo-widget]').forEach(widget=>{const photo=widget.dataset.pendingPhoto||widget.querySelector('[data-photo-value]').value;updatePhotoWidget(widget,photo)})
});
document.addEventListener('click',e=>{if(e.target.closest('[data-tab="register"]'))queueMicrotask(()=>{const fields=document.getElementById('authFields');if(fields&&document.getElementById('authTitle')?.textContent==='რეგისტრაცია'&&!fields.querySelector('[data-registration-photo]'))fields.insertAdjacentHTML('beforeend',registrationProfileFields())})});
function closeGenderMenu(root,restoreFocus=false){if(!root)return;const trigger=root.querySelector('.site-select-trigger');root.classList.remove('is-open');trigger?.setAttribute('aria-expanded','false');root.querySelector('.site-select-options')?.setAttribute('hidden','');if(restoreFocus)trigger?.focus()}
function chooseGenderOption(root,value){const select=root.querySelector('select[name="gender"]'),option=root.querySelector('[data-gender-option="'+value+'"]');if(!select||!option)return;select.value=value;root.querySelector('[data-gender-value]').textContent=option.textContent;root.querySelectorAll('[data-gender-option]').forEach(item=>item.setAttribute('aria-selected',String(item===option)));select.dispatchEvent(new Event('change',{bubbles:true}));closeGenderMenu(root,true)}
document.addEventListener('click',e=>{
 const trigger=e.target.closest('.site-select-trigger');if(trigger){const root=trigger.closest('[data-gender-select]'),isOpen=root.classList.contains('is-open');document.querySelectorAll('[data-gender-select].is-open').forEach(item=>closeGenderMenu(item));if(!isOpen){root.classList.add('is-open');trigger.setAttribute('aria-expanded','true');root.querySelector('.site-select-options').removeAttribute('hidden')}return}
 const option=e.target.closest('[data-gender-option]');if(option){chooseGenderOption(option.closest('[data-gender-select]'),option.dataset.genderOption);return}
 document.querySelectorAll('[data-gender-select].is-open').forEach(root=>{if(!root.contains(e.target))closeGenderMenu(root)})
});
document.addEventListener('keydown',e=>{
 const trigger=e.target.closest('.site-select-trigger');if(trigger&&['ArrowDown','ArrowUp','Enter',' '].includes(e.key)){e.preventDefault();const root=trigger.closest('[data-gender-select]');if(!root.classList.contains('is-open')){root.classList.add('is-open');trigger.setAttribute('aria-expanded','true');root.querySelector('.site-select-options').removeAttribute('hidden')}root.querySelector('[aria-selected="true"]')?.focus();return}
 const option=e.target.closest('[data-gender-option]');if(!option)return;const root=option.closest('[data-gender-select]'),items=[...root.querySelectorAll('[data-gender-option]')],index=items.indexOf(option);if(e.key==='Escape'){e.preventDefault();closeGenderMenu(root,true)}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();items[(index+(e.key==='ArrowDown'?1:items.length-1))%items.length].focus()}else if(e.key==='Home'){e.preventDefault();items[0].focus()}else if(e.key==='End'){e.preventDefault();items.at(-1).focus()}else if(e.key==='Enter'||e.key===' '){e.preventDefault();option.click()}
});
document.addEventListener('focusout',e=>{const root=e.target.closest?.('[data-gender-select]');if(root)setTimeout(()=>{if(!root.contains(document.activeElement))closeGenderMenu(root)},0)});
