/* Public review display and completed-job status helpers. */
const reviewStoreKey='dge-reviews';
const allReviews=()=>get(reviewStoreKey,[]);
const reviewKeyForWorker=worker=>worker.owner||worker.email||`worker:${worker.id}`;
function reviewSummary(target){const rows=allReviews().filter(review=>review.target===target||review.reviewedUserId===target);return{rows,count:rows.length,average:rows.length?rows.reduce((sum,review)=>sum+Number(review.rating||0),0)/rows.length:0}}
function completedCount(target){return jobs.filter(job=>job.status==='completed'&&job.owner===target).length}
function starString(rating){const full=Math.max(0,Math.min(5,Math.round(Number(rating)||0)));return '★'.repeat(full)+'☆'.repeat(5-full)}
function compactRating(target){const summary=reviewSummary(target);return summary.count?`<div class="rating-inline"><span>⭐ ${summary.average.toFixed(1)}</span><span>${summary.count} შეფასება</span></div>`:'<div class="rating-inline rating-empty">ჯერ არ აქვს შეფასებები</div>'}
function reviewSection(target){const summary=reviewSummary(target);return `<section class="reviews-section"><div class="reviews-title"><h3>შეფასებები</h3>${summary.count?`<span class="rating-average">⭐ ${summary.average.toFixed(1)} <small>${summary.count} შეფასება</small></span>`:''}</div>${summary.count?`<div class="review-list">${summary.rows.slice().sort((a,b)=>b.createdAt-a.createdAt).map(review=>`<article class="review-item"><div class="review-stars" aria-label="${review.rating} ვარსკვლავი">${starString(review.rating)}</div>${review.text||review.comment?`<p>„${esc(review.text||review.comment)}“</p>`:''}<div class="review-author">${Avatar(review.authorEmail||{name:review.authorName},'sm')}<small>— ${esc(review.authorName||'მომხმარებელი')}, ${esc(timeAgo(review.createdAt))}</small></div></article>`).join('')}</div>`:'<div class="notice">ჯერ არ აქვს შეფასებები</div>'}</section>`}
function timeAgo(timestamp){const days=Math.max(0,Math.floor((Date.now()-Number(timestamp||Date.now()))/86400000));if(!days)return 'ახლახან';if(days===1)return '1 დღის წინ';if(days<30)return `${days} დღის წინ`;return `${Math.floor(days/30)} თვის წინ`}
function jobStatusText(job){return({active:'აქტიური',in_progress:'შესრულების პროცესში',completed:'დასრულებული',cancelled:'გაუქმებული'})[job.status||'active']||'აქტიური'}
function jobFlowPanel(job){const status=job.status||'active';return `<section class="job-progress"><div class="progress-heading"><div><h3>სამუშაოს სტატუსი</h3><p>აქტიური → შესრულების პროცესში → დასრულებული</p></div><span class="status-badge status-${esc(status)}">${esc(jobStatusText(job))}</span></div></section>`}
const baseWorkerCard=workerCard;workerCard=function(worker){const html=baseWorkerCard(worker),key=reviewKeyForWorker(worker);return html.replace('<p>⌖ ',`${compactRating(key)}<p>⌖ `)};
const baseWorkerDetail=workerDetail;workerDetail=function(id){let html=baseWorkerDetail(id),worker=[...get('dge-workers',[]),...seedWorkers].find(item=>String(item.id)===String(id));if(!worker)return html;const key=reviewKeyForWorker(worker);html=html.replace('<h3>წინა სამუშაოები და შეფასებები</h3><div class="notice">შეფასებები მალე დაემატება.</div>',`<h3>დასრულებული განცხადებები: ${completedCount(key)}</h3>${reviewSection(key)}`);return html.replace('</h1>',`</h1>${compactRating(key)}`)};
const baseProfilePage=profilePage;profilePage=function(){const html=baseProfilePage();if(!user)return html;return html.replace('</form>',`</form><section class="profile-reviews"><div class="profile-rating-head"><h2>ჩემი შეფასებები</h2>${compactRating(user.email)}</div>${reviewSection(user.email)}</section>`)};
const baseDetails=details;details=function(id){let html=baseDetails(id);const job=jobs.find(item=>String(item.id)===String(id));if(!job)return html;html=html.replace('</article>',`${jobFlowPanel(job)}</article>`);return html.replace('<p>განცხადების ავტორი</p>',`<p>განცხადების ავტორი</p>${compactRating(job.owner)}`)};
function publicUserProfile(email){const account=get('dge-accounts',[]).find(row=>row.email===email),profile=get('dge-workers',[]).find(row=>row.owner===email),person=account||profile||{email},name=account?.name||profile?.name||'მომხმარებელი',place=profile||account||{},rating=reviewSummary(email);return `<section class="container"><div class="page-head public-profile-heading">${Avatar(person,'profile')}<div><a class="text-link" href="#/jobs">← განცხადებებზე დაბრუნება</a><span class="eyebrow">მომხმარებლის პროფილი</span><h1>${esc(name)}</h1><p>${place.city?`📍 ${esc(place.city)}${place.area?`, ${esc(place.area)}`:''}`:'დღიური სამუშაოების პლატფორმის წევრი'}</p></div></div><div class="public-profile-card"><div class="public-rating">${rating.count?`<strong>⭐ ${rating.average.toFixed(1)}</strong><span>${rating.count} შეფასება</span>`:'ჯერ არ აქვს შეფასებები'}</div>${completedCount(email)?`<p>დასრულებული განცხადებები: <strong>${completedCount(email)}</strong></p>`:''}</div>${reviewSection(email)}</section>`}
const detailWithRatings=details;details=function(id){let html=detailWithRatings(id);const job=jobs.find(item=>String(item.id)===String(id));if(job?.owner)html=html.replace(`<h3>${esc(job.name)}</h3>`,`<h3><a href="#/user/${encodeURIComponent(job.owner)}">${esc(job.name)}</a></h3>`);return html};
const routeWithReviewProfile=routeView;routeView=function(){const hash=location.hash||'#/';const [route]=hash.slice(1).split('?');if(route.startsWith('/user/')){app.innerHTML=publicUserProfile(decodeURIComponent(route.slice('/user/'.length)));window.scrollTo(0,0);return}routeWithReviewProfile()};render=routeView;routeView();