const reviewStoreKey='dge-reviews';
const allReviews=()=>get(reviewStoreKey,[]);
const applicationsFor=jobId=>get('dge-apps',[]).filter(x=>x.id===jobId);
const applicationsForUser=email=>{const ids=new Set(get('dge-apps',[]).filter(x=>x.email===email).map(x=>x.id));return jobs.filter(j=>ids.has(j.id))};
const reviewKeyForWorker=w=>w.owner||w.email||`worker:${w.id}`;
function reviewSummary(target){const rows=allReviews().filter(r=>r.target===target);return{rows,count:rows.length,average:rows.length?rows.reduce((sum,r)=>sum+Number(r.rating||0),0)/rows.length:0}}
function completedCount(target){return jobs.filter(j=>j.status==='completed'&&(j.owner===target||applicationsFor(j.id).some(a=>a.email===target))).length}
function starString(n){const full=Math.round(Number(n)||0);return '★'.repeat(full)+'☆'.repeat(5-full)}
function compactRating(target){const s=reviewSummary(target);return s.count?`<div class="rating-inline"><span>⭐ ${s.average.toFixed(1)}</span><span>${s.count} შეფასება</span><span>${completedCount(target)} დასრულებული სამუშაო</span></div>`:`<div class="rating-inline rating-empty">ჯერ არ აქვს შეფასებები</div>`}
function reviewSection(target){const s=reviewSummary(target);return `<section class="reviews-section"><div class="reviews-title"><h3>შეფასებები</h3>${s.count?`<span class="rating-average">⭐ ${s.average.toFixed(1)} <small>${s.count} შეფასება</small></span>`:''}</div>${s.count?`<div class="review-list">${s.rows.slice().sort((a,b)=>b.createdAt-a.createdAt).map(r=>`<article class="review-item"><div class="review-stars" aria-label="${r.rating} ვარსკვლავი">${starString(r.rating)}</div>${r.text?`<p>„${esc(r.text)}“</p>`:''}<div class="review-author">${Avatar(r.authorEmail||{name:r.authorName},'sm')}<small>— ${esc(r.authorName||'მომხმარებელი')}, ${esc(timeAgo(r.createdAt))}</small></div></article>`).join('')}</div>`:'<div class="notice">ჯერ არ აქვს შეფასებები</div>'}</section>`}
function timeAgo(timestamp){const days=Math.max(0,Math.floor((Date.now()-Number(timestamp||Date.now()))/86400000));if(!days)return 'ახლახან';if(days===1)return '1 დღის წინ';if(days<30)return `${days} დღის წინ`;const months=Math.floor(days/30);return `${months} თვის წინ`}
function userName(email,fallback='მომხმარებელი'){return get('dge-accounts',[]).find(x=>x.email===email)?.name||((user?.email===email)?user.name:fallback)}
function jobStatusText(job){return({active:'აქტიური',in_progress:'შესრულების პროცესში',completed:'დასრულებული'})[job.status||'active']||'აქტიური'}
function jobFlowPanel(job){const status=job.status||'active',next=status==='active'?'in_progress':status==='in_progress'?'completed':'',participant=!!user&&(user.email===job.owner||applicationsFor(job.id).some(a=>a.email===user.email)),apps=applicationsFor(job.id),isOwner=!!user&&user.email===job.owner;let reviewActions='';if(status==='completed'&&participant){if(isOwner){const candidates=[...new Set(apps.map(a=>a.email).filter(email=>email&&email!==job.owner))];reviewActions=candidates.length?candidates.map(email=>reviewExists(job.id,user.email)?'<span class="review-done">ამ სამუშაოზე შეფასება უკვე დატოვე</span>':`<button class="btn btn-secondary btn-small" data-open-review data-job="${esc(job.id)}" data-target="${esc(email)}" data-target-name="${esc(userName(email))}">შეაფასე ${esc(userName(email))}</button>`).join(''):'<div class="notice">განაცხადის ავტორის მიღების შემდეგ შეძლებ მის შეფასებას.</div>'}else if(job.owner){reviewActions=reviewExists(job.id,user.email)?'<span class="review-done">ამ სამუშაოზე შეფასება უკვე დატოვე</span>':`<button class="btn btn-primary btn-small" data-open-review data-job="${esc(job.id)}" data-target="${esc(job.owner)}" data-target-name="${esc(job.name||userName(job.owner))}">შეაფასე დამსაქმებელი</button>`}}
 return `<section class="job-progress"><div class="progress-heading"><div><h3>სამუშაოს სტატუსი</h3><p>აქტიური → შესრულების პროცესში → დასრულებული</p></div><span class="status-badge status-${status}">${jobStatusText(job)}</span></div>${participant&&next?`<button class="btn btn-secondary btn-small" data-job-status="${esc(job.id)}" data-next-status="${next}">${next==='completed'?'სამუშაო დასრულებულია':'შესრულების პროცესში გადაყვანა'}</button>`:''}${status==='completed'&&reviewActions?`<div class="job-review-actions"><strong>სამუშაო დასრულებულია</strong><div>${reviewActions}</div></div>`:''}</section>`}
function ratingModal(jobId,target,targetName){return `<div class="modal-backdrop" data-rating-backdrop><form class="modal-card rating-modal" data-review-form data-job="${esc(jobId)}" data-target="${esc(target)}"><button type="button" class="modal-close" data-close-rating aria-label="დახურვა">×</button><span class="eyebrow">დასრულებული სამუშაო</span><h2>შეაფასე შესრულებული სამუშაო</h2><p>${esc(targetName)}-თან თანამშრომლობის გამოცდილება</p><div class="star-picker" role="radiogroup" aria-label="შეფასება">${[1,2,3,4,5].map(n=>`<button type="button" role="radio" aria-checked="false" aria-label="${n} ვარსკვლავი" data-star="${n}">☆</button>`).join('')}</div><input type="hidden" name="rating" value=""><label class="review-label" for="reviewText">როგორი იყო თქვენი გამოცდილება?</label><textarea id="reviewText" name="text" maxlength="350" placeholder="დაწერე შეფასება... (არასავალდებულო)"></textarea><button class="btn btn-primary form-submit" type="submit">შეფასების დატოვება</button><div class="error-msg" data-review-error></div></form></div>`}
function openRatingModal(jobId,target,name){if(!user){sessionStorage.setItem('dge-return',location.hash||'#/');location.hash='#/login';return}app.insertAdjacentHTML('beforeend',ratingModal(jobId,target,name))}
function reviewExists(jobId,author){return allReviews().some(r=>r.jobId===jobId&&r.authorEmail===author)}

const baseWorkerCard=workerCard;workerCard=function(w){let html=baseWorkerCard(w),key=reviewKeyForWorker(w);return html.replace('<p>⌖ ',`${compactRating(key)}<p>⌖ `)};
const baseWorkerDetail=workerDetail;workerDetail=function(id){let html=baseWorkerDetail(id),w=[...get('dge-workers',[]),...seedWorkers].find(x=>x.id===id);if(!w)return html;const key=reviewKeyForWorker(w);html=html.replace('<h3>წინა სამუშაოები და შეფასებები</h3><div class="notice">შეფასებები მალე დაემატება.</div>',`<h3>დასრულებული სამუშაოები: ${completedCount(key)}</h3>${reviewSection(key)}`);html=html.replace('</h1>',`</h1>${compactRating(key)}`);return html};
const baseProfilePage=profilePage;profilePage=function(){let html=baseProfilePage();if(!user)return html;return html.replace('</form>',`</form><section class="profile-reviews"><div class="profile-rating-head"><h2>ჩემი შეფასებები</h2>${compactRating(user.email)}</div><p class="completed-count">დასრულებული სამუშაოები: ${completedCount(user.email)}</p>${reviewSection(user.email)}</section>`)};
dashboard=function(){if(!user)return `<div class="auth-wrap"><div class="auth-card"><h1>შესვლა</h1><p>მართე შენი განცხადებები და განაცხადები.</p><a class="btn btn-primary" href="#/login">შესვლა / რეგისტრაცია</a></div></div>`;const tab=new URLSearchParams(location.hash.split('?')[1]||'').get('tab')||'overview',mine=jobs.filter(j=>j.owner===user.email),myApps=applicationsForUser(user.email),received=mine.filter(j=>applicationsFor(j.id).length),list=tab==='applications'?myApps:tab==='received'?received:tab==='posts'?mine:mine.slice(0,3),title=tab==='applications'?'ჩემი განაცხადები':tab==='received'?'მიღებული განაცხადები':tab==='posts'?'ჩემი განცხადებები':'ბოლო განცხადებები';return `<section class="container"><div class="page-head"><span class="eyebrow">პირადი სივრცე</span><h1>გამარჯობა, ${esc(user.name)}!</h1><p>მართე განცხადებები, განაცხადები და დასრულებული სამუშაოები.</p></div><div class="dashboard"><nav class="side-menu"><a href="#/dashboard" class="${tab==='overview'?'active':''}">მიმოხილვა</a><a href="#/post-role">＋ ახალი განცხადება</a><a href="#/saved">შენახული განცხადებები (${saved.length})</a><a href="#/dashboard?tab=applications" class="${tab==='applications'?'active':''}">ჩემი განაცხადები (${myApps.length})</a><a href="#/dashboard?tab=posts" class="${tab==='posts'?'active':''}">ჩემი განცხადებები (${mine.length})</a><a href="#/dashboard?tab=received" class="${tab==='received'?'active':''}">მიღებული განაცხადები (${received.length})</a><a href="#/profile">პროფილი</a><a href="#" data-logout>გასვლა</a></nav><div class="dash-main"><div class="dash-stats"><div class="stat-card"><small>ჩემი განცხადებები</small><strong>${mine.length}</strong></div><div class="stat-card"><small>ჩემი განაცხადები</small><strong>${myApps.length}</strong></div><div class="stat-card"><small>დასრულებული სამუშაოები</small><strong>${completedCount(user.email)}</strong></div></div><div class="section-heading"><h2>${title}</h2><a class="text-link" href="#/start">+ დამატება</a></div>${list.length?`<div class="job-grid">${list.map(j=>jobCard(j)).join('')}</div>`:`<div class="empty"><strong>${tab==='applications'?'განაცხადები ჯერ არ გაქვს':tab==='received'?'განაცხადები ჯერ არ მიგიღია':'ჯერ განცხადება არ დაგიმატებია'}</strong>აირჩიე განცხადება ან გამოაქვეყნე ახალი, რომ დაიწყო.<a class="btn btn-primary btn-small" href="#/jobs" style="margin-top:12px">სამუშაოს ძებნა</a></div>`}</div></div></section>`};
const baseDetails=details;details=function(id){let html=baseDetails(id);const job=jobs.find(j=>j.id===id);if(!job)return html;const target=job.owner;html=html.replace('</article>',`${jobFlowPanel(job)}</article>`);if(target)html=html.replace('<p>განცხადების ავტორი</p>',`<p>განცხადების ავტორი</p>${compactRating(target)}`);else html=html.replace('<p>განცხადების ავტორი</p>','<p>განცხადების ავტორი</p><div class="rating-inline rating-empty">ჯერ არ აქვს შეფასებები</div>');return html};


document.addEventListener('click',e=>{if(e.target.closest('[data-job-status]')){const b=e.target.closest('[data-job-status]'),job=jobs.find(x=>x.id===b.dataset.jobStatus);if(!job||!user||(job.owner!==user.email&&!applicationsFor(job.id).some(a=>a.email===user.email)))return;job.status=b.dataset.nextStatus;set('dge-jobs',jobs);notify(job.status==='completed'?'სამუშაო დასრულებულად მოინიშნა':'სამუშაო შესრულების პროცესშია');routeView();return}if(e.target.closest('[data-open-review]')){const b=e.target.closest('[data-open-review]');openRatingModal(b.dataset.job,b.dataset.target,b.dataset.targetName);return}if(e.target.closest('[data-close-rating]')||e.target.matches('[data-rating-backdrop]')){e.target.closest('.modal-backdrop')?.remove();return}const star=e.target.closest('[data-star]');if(star){const form=star.closest('[data-review-form]'),value=Number(star.dataset.star);form.querySelector('[name="rating"]').value=value;form.querySelectorAll('[data-star]').forEach(b=>{const on=Number(b.dataset.star)<=value;b.textContent=on?'★':'☆';b.classList.toggle('selected',on);b.setAttribute('aria-checked',String(Number(b.dataset.star)===value))});return}});
document.addEventListener('submit',e=>{if(e.target.matches('[data-review-form]')){e.preventDefault();const f=e.target,job=jobs.find(j=>j.id===f.dataset.job),target=f.dataset.target,rating=Number(new FormData(f).get('rating')),text=new FormData(f).get('text').trim();if(!user){notify('შეფასებისთვის შედი ანგარიშზე.');return}if(!job||job.status!=='completed'){f.querySelector('[data-review-error]').textContent='შეფასების დატოვება მხოლოდ დასრულებული სამუშაოსთვის შეიძლება.';return}if(target===user.email||job.owner===user.email&&target===user.email){f.querySelector('[data-review-error]').textContent='საკუთარი თავის შეფასება შეუძლებელია.';return}if(reviewExists(job.id,user.email)){f.querySelector('[data-review-error]').textContent='ამ სამუშაოზე შეფასება უკვე დატოვე.';return}const apps=applicationsFor(job.id),isOwner=job.owner===user.email,participant=isOwner||apps.some(a=>a.email===user.email),authorizedTarget=isOwner?apps.some(a=>a.email===target&&target!==job.owner):(apps.some(a=>a.email===user.email)&&target===job.owner);if(!participant){f.querySelector('[data-review-error]').textContent='შეფასების დატოვება მხოლოდ სამუშაოს მონაწილეს შეუძლია.';return}if(!authorizedTarget){f.querySelector('[data-review-error]').textContent='შეაფასე მხოლოდ ამ სამუშაოს მეორე მონაწილე.';return}if(!rating){f.querySelector('[data-review-error]').textContent='აირჩიე 1-დან 5 ვარსკვლავამდე შეფასება.';return}const reviews=allReviews();reviews.push({id:'r'+Date.now(),jobId:job.id,target,authorEmail:user.email,authorName:user.name,rating,text,createdAt:Date.now()});set(reviewStoreKey,reviews);notify('შეფასება გამოქვეყნდა. მადლობა!');routeView()}});
function publicUserProfile(email){const account=get('dge-accounts',[]).find(x=>x.email===email),profile=get('dge-workers',[]).find(x=>x.owner===email),person=account||profile||{email},name=account?.name||profile?.name||'მომხმარებელი',place=profile||account||{},rating=reviewSummary(email);return `<section class="container"><div class="page-head public-profile-heading">${Avatar(person,'profile')}<div><a class="text-link" href="#/jobs">← განცხადებებზე დაბრუნება</a><span class="eyebrow">მომხმარებლის პროფილი</span><h1>${esc(name)}</h1><p>${place.city?`📍 ${esc(place.city)}${place.area?`, ${esc(place.area)}`:''}`:'დღიური სამუშაოების პლატფორმის წევრი'}</p></div></div><div class="public-profile-card"><div class="public-rating">${rating.count?`<strong>⭐ ${rating.average.toFixed(1)}</strong><span>${rating.count} შეფასება</span>`:'ჯერ არ აქვს შეფასებები'}</div><p>დასრულებული სამუშაოები: <strong>${completedCount(email)}</strong></p></div>${reviewSection(email)}</section>`}
const detailWithRatings=details;details=function(id){let html=detailWithRatings(id);const job=jobs.find(j=>j.id===id);if(job?.owner)html=html.replace(`<h3>${esc(job.name)}</h3>`,`<h3><a href="#/user/${encodeURIComponent(job.owner)}">${esc(job.name)}</a></h3>`);return html};
const routeWithReviewProfile=routeView;routeView=function(){const hash=location.hash||'#/';const [path,query='']=hash.slice(1).split('?');if(path.startsWith('/user/')){app.innerHTML=publicUserProfile(decodeURIComponent(path.slice('/user/'.length)));window.scrollTo(0,0);return}routeWithReviewProfile()};render=routeView;routeView();





