/* Date, duration and structured payment enhancements. Keeps the existing
   category/location widgets, favorites and review card wrappers. */
const scheduleDurations=[['1-2','1–2 საათით'],['2-4','2–4 საათით'],['4-8','4–8 საათით'],['full-day','მთელი დღით'],['multi-day','რამდენიმე დღით'],['by-agreement','შეთანხმებით']];
const paymentKinds=[['all','ყველა'],['hourly','საათობრივი'],['fixed','ფიქსირებული'],['daily','დღიური'],['negotiable','შეთანხმებით']];
const formPaymentKinds=[['daily','დღიური'],['hourly','საათობრივი'],['fixed','ფიქსირებული'],['negotiable','შეთანხმებით']];
const paymentNames={hourly:'საათობრივი',daily:'დღიური',fixed:'ფიქსირებული',negotiable:'შეთანხმებით'};
const experienceDurations=['6 თვე','1 წელი','2 წელი','3+ წელი','5+ წელი','10+ წელი','15+ წელი'];
const durationName=v=>scheduleDurations.find(x=>x[0]===v)?.[1]||v||'შეთანხმებით';
const localISO=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const plusDays=(d,n)=>{const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());x.setDate(x.getDate()+n);return x};
const scheduleToday=()=>localISO(new Date());
const kaMonths=['იანვარი','თებერვალი','მარტი','აპრილი','მაისი','ივნისი','ივლისი','აგვისტო','სექტემბერი','ოქტომბერი','ნოემბერი','დეკემბერი'];
const kaWeekdays=['ორშ','სამ','ოთხ','ხუთ','პარ','შაბ','კვი'];
const kaDate=v=>{if(!v)return '';const [y,m,d]=v.split('-').map(Number);return `${d} ${kaMonths[m-1]||''}`};
const fullKaDate=v=>{if(!v)return '';const [y,m,d]=v.split('-').map(Number);return `${d} ${kaMonths[m-1]||''}, ${y}`};
const relativeDate=v=>v===scheduleToday()?'დღეს':v===localISO(plusDays(new Date(),1))?'ხვალ':kaDate(v);
const payKind=j=>j.paymentType||'daily';
const payValue=j=>j.paymentAmount!=null?Number(j.paymentAmount):Number(j.pay||0);
const payLabel=j=>payKind(j)==='negotiable'?'შეთანხმებით':`${payValue(j).toLocaleString('ka-GE')} ₾${payKind(j)==='hourly'?' / საათი':payKind(j)==='daily'?' / დღე':''}`;
const inferredDuration=j=>{if(j.duration)return j.duration;if(j.dateEnd&&j.dateEnd!==j.date)return'multi-day';const [sh,sm]=(j.startTime||j.start||'09:00').split(':').map(Number),[eh,em]=(j.endTime||j.end||'17:00').split(':').map(Number),h=(eh*60+em-sh*60-sm)/60;return h<=2?'1-2':h<=4?'2-4':h<=8?'4-8':'full-day'};
const jobPeriod=j=>j.dateMode==='agreement'?'შეთანხმებით':j.dateEnd&&j.dateEnd!==j.date?`${kaDate(j.date)} — ${kaDate(j.dateEnd)}`:relativeDate(j.date);
const jobDuration=j=>durationName(inferredDuration(j));

function kaDatePickerMarkup(name,value='',options={}){const selected=value?fullKaDate(value):'აირჩიე თარიღი',min=options.min||'',required=options.required?'true':'false',clearable=options.clearable?'true':'false',hidden=options.hidden?' hidden':'',todayDisabled=min&&scheduleToday()<min?' disabled':'';return `<div class="ka-date-picker${options.className?' '+options.className:''}" data-ka-date-picker data-min-date="${esc(min)}" data-required="${required}" data-clearable="${clearable}"${hidden}><input class="ka-date-value" type="hidden" name="${esc(name)}" value="${esc(value)}" ${options.marker||''}><button class="ka-date-trigger" type="button" data-ka-date-trigger aria-haspopup="dialog" aria-expanded="false"><span class="ka-date-trigger-label${value?'':' is-empty'}">${esc(selected)}</span><svg class="day-icon" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></svg></button><section class="ka-date-popover" data-ka-calendar role="dialog" aria-label="თარიღის არჩევა" hidden><header class="ka-calendar-header"><button type="button" data-ka-month-shift="-1" aria-label="წინა თვე">‹</button><strong data-ka-month-label></strong><button type="button" data-ka-month-shift="1" aria-label="შემდეგი თვე">›</button></header><div class="ka-calendar-weekdays">${kaWeekdays.map((d,i)=>`<span aria-label="${['ორშაბათი','სამშაბათი','ოთხშაბათი','ხუთშაბათი','პარასკევი','შაბათი','კვირა'][i]}">${d}</span>`).join('')}</div><div class="ka-calendar-days" data-ka-calendar-days></div><footer class="ka-calendar-footer"><button type="button" data-ka-date-today${todayDisabled}>დღეს</button>${options.clearable?'<button type="button" data-ka-date-clear>გასუფთავება</button>':''}</footer></section></div>`}
function renderKaCalendar(control){const value=control.querySelector('.ka-date-value'),view=control.dataset.viewMonth||value.value||scheduleToday(),[year,month]=view.split('-').map(Number),first=new Date(year,month-1,1),offset=(first.getDay()+6)%7,start=new Date(year,month-1,1-offset),selected=value.value,min=control.dataset.minDate||'',days=control.querySelector('[data-ka-calendar-days]');control.querySelector('[data-ka-month-label]').textContent=`${kaMonths[month-1]} ${year}`;days.innerHTML=Array.from({length:42},(_,i)=>{const date=plusDays(start,i),iso=localISO(date),outside=date.getMonth()!==month-1,disabled=min&&iso<min;return `<button type="button" class="ka-calendar-day${outside?' outside-month':''}${iso===selected?' selected':''}${iso===scheduleToday()?' is-today':''}" data-ka-day-value="${iso}" ${disabled?'disabled':''} aria-pressed="${iso===selected}">${date.getDate()}</button>`}).join('')}
function openKaCalendar(control){document.querySelectorAll('[data-ka-calendar]:not([hidden])').forEach(c=>{if(c.parentElement!==control){c.hidden=true;c.parentElement.querySelector('[data-ka-date-trigger]')?.setAttribute('aria-expanded','false')}});const input=control.querySelector('.ka-date-value');control.dataset.viewMonth=(input.value||scheduleToday()).slice(0,7);renderKaCalendar(control);control.querySelector('[data-ka-calendar]').hidden=false;control.querySelector('[data-ka-date-trigger]').setAttribute('aria-expanded','true')}
function closeKaCalendar(control){if(!control)return;control.querySelector('[data-ka-calendar]').hidden=true;control.querySelector('[data-ka-date-trigger]').setAttribute('aria-expanded','false')}
function syncKaDatePicker(input){const control=input?.closest('[data-ka-date-picker]');if(!control)return;const label=control.querySelector('.ka-date-trigger-label');label.textContent=input.value?fullKaDate(input.value):'აირჩიე თარიღი';label.classList.toggle('is-empty',!input.value);if(!control.querySelector('[data-ka-calendar]').hidden)renderKaCalendar(control)}
function setKaDate(input,value){if(!input)return;input.value=value;syncKaDatePicker(input);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}
document.addEventListener('click',e=>{
 const mobileToggle=e.target.closest('[data-mobile-filter-toggle]');if(mobileToggle){e.preventDefault();e.stopImmediatePropagation();const form=mobileToggle.closest('#filters, #worker-filters');if(!form)return;const open=form.classList.toggle('additional-filters-open');mobileToggle.setAttribute('aria-expanded',String(open));mobileToggle.querySelector('[data-mobile-filter-label]').textContent=open?'ფილტრების დამალვა':'დამატებითი ფილტრები';return}
 const trigger=e.target.closest('[data-ka-date-trigger]');if(trigger){e.preventDefault();openKaCalendar(trigger.closest('[data-ka-date-picker]'));return}
 const shift=e.target.closest('[data-ka-month-shift]');if(shift){const control=shift.closest('[data-ka-date-picker]'),[year,month]=control.dataset.viewMonth.split('-').map(Number),next=new Date(year,month-1+Number(shift.dataset.kaMonthShift),1);control.dataset.viewMonth=localISO(next).slice(0,7);renderKaCalendar(control);return}
 const day=e.target.closest('[data-ka-day-value]');if(day){const control=day.closest('[data-ka-date-picker]'),input=control.querySelector('.ka-date-value');if(day.disabled)return;setKaDate(input,day.dataset.kaDayValue);closeKaCalendar(control);return}
 const today=e.target.closest('[data-ka-date-today]');if(today){const control=today.closest('[data-ka-date-picker]');setKaDate(control.querySelector('.ka-date-value'),scheduleToday());closeKaCalendar(control);return}
 const clearDate=e.target.closest('[data-ka-date-clear]');if(clearDate){const control=clearDate.closest('[data-ka-date-picker]');setKaDate(control.querySelector('.ka-date-value'),'');closeKaCalendar(control);if(control.dataset.clearable==='true')control.hidden=true;return}
 const quick=e.target.closest('[data-date-quick]');if(quick){e.preventDefault();e.stopImmediatePropagation();const mode=quick.dataset.dateQuick,active=scheduleDateFilter(),clear=active?.mode===mode;set('dge-date-filter',clear?null:{mode});document.querySelectorAll('[data-date-quick]').forEach(b=>b.classList.toggle('selected',!clear&&b===quick));updateResults();return}
 const postChoice=e.target.closest('[data-post-date-choice]');if(postChoice){e.preventDefault();e.stopImmediatePropagation();const form=postChoice.closest('#postForm'),input=form.querySelector('[data-post-date]'),control=input.closest('[data-ka-date-picker]'),mode=form.querySelector('[data-post-date-mode]'),choice=postChoice.dataset.postDateChoice;form.querySelectorAll('[data-post-date-choice]').forEach(button=>button.classList.toggle('selected',button===postChoice));if(choice==='agreement'){mode.value='agreement';input.value='';syncKaDatePicker(input);control.dataset.required='false';control.hidden=true;return}mode.value='date';control.dataset.required='true';control.hidden=false;if(choice==='other'){openKaCalendar(control);return}setKaDate(input,choice==='today'?scheduleToday():localISO(plusDays(new Date(),1)));return}
 if(e.target.closest('[data-clear-filter="date"], [data-clear-all-schedule]'))queueMicrotask(()=>{const input=document.querySelector('#filters [name="date"]');if(input){input.value='';syncKaDatePicker(input);input.closest('[data-ka-date-picker]').hidden=true}});
 const outside=e.target.closest('[data-ka-date-picker]');if(!outside)document.querySelectorAll('[data-ka-calendar]:not([hidden])').forEach(c=>closeKaCalendar(c.parentElement));
},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('[data-ka-calendar]:not([hidden])').forEach(c=>closeKaCalendar(c.parentElement))});
document.addEventListener('input',e=>{if(e.target.matches('[data-post-date]')){const form=e.target.form,mode=form?.querySelector('[data-post-date-mode]'),picker=e.target.closest('[data-ka-date-picker]');if(mode){mode.value='date';picker.dataset.required='true';picker.hidden=false;form.querySelectorAll('[data-post-date-choice]').forEach(button=>button.classList.toggle('selected',button.dataset.postDateChoice==='today'&&e.target.value===scheduleToday()||button.dataset.postDateChoice==='tomorrow'&&e.target.value===localISO(plusDays(new Date(),1))))}const end=form?.querySelector('[data-end-date]'),control=end?.closest('[data-ka-date-picker]');if(control){control.dataset.minDate=e.target.value||scheduleToday();if(end.value&&end.value<control.dataset.minDate)setKaDate(end,'')}}});
document.addEventListener('change',e=>{if(e.target.matches('#post-duration')){e.target.closest('[data-site-filter-select]')?.classList.toggle('has-error',!e.target.value);if(e.target.value!=='multi-day'){const end=document.querySelector('[data-end-date]');if(end){end.value='';syncKaDatePicker(end)}}}},true);
document.addEventListener('change',e=>{if(!e.target.matches('#workerProfileForm [data-worker-has-experience],#workerProfileForm [name="availability"]'))return;e.target.closest('[data-site-filter-select]')?.classList.toggle('has-error',!e.target.value);if(e.target.value)e.target.form?.querySelector('#workerMessage')?.replaceChildren()},true);
document.addEventListener('submit',e=>{if(e.target.id!=='postForm')return;const form=e.target,start=form.querySelector('[data-post-date]'),end=form.querySelector('[data-end-date]'),byAgreement=form.querySelector('[data-post-date-mode]')?.value==='agreement';if(!start.value&&!byAgreement){e.preventDefault();e.stopImmediatePropagation();document.getElementById('postMessage').innerHTML='<div class="error-msg">აირჩიე სამუშაოს თარიღი.</div>';openKaCalendar(start.closest('[data-ka-date-picker]'));return}if(!byAgreement&&form.querySelector('#post-duration')?.value==='multi-day'&&!end.value){e.preventDefault();e.stopImmediatePropagation();document.getElementById('postMessage').innerHTML='<div class="error-msg">აირჩიე დასრულების თარიღი.</div>';openKaCalendar(end.closest('[data-ka-date-picker]'))}},true);
document.addEventListener('submit',e=>{const form=e.target;if(form.id!=='postForm')return;const duration=form.querySelector('#post-duration');if(duration?.value)return;e.preventDefault();e.stopImmediatePropagation();const widget=duration?.closest('[data-site-filter-select]');widget?.classList.add('has-error');widget?.querySelector('[data-site-filter-trigger]')?.focus();document.getElementById('postMessage').innerHTML='<div class="error-msg">აირჩიე სამუშაოს ხანგრძლივობა.</div>'},true);

// Normalize saved/sample records once so older localStorage data remains usable.
jobs=jobs.map((j,i)=>{const kind=j.paymentType||(['j2'].includes(j.id)?'hourly':j.id==='j4'?'negotiable':j.id==='j5'?'fixed':'daily'),amount=kind==='negotiable'?null:(j.paymentAmount??(j.id==='j2'?20:Number(j.pay||0))),d=j.duration||(j.id==='j4'?'multi-day':inferredDuration(j));return {...j,district:j.district||j.area||'',startTime:j.startTime||j.start||'',endTime:j.endTime||j.end||'',paymentType:kind,paymentAmount:amount,paymentMin:j.paymentMin??amount,paymentMax:j.paymentMax??amount,duration:d,dateEnd:j.dateEnd||(j.id==='j4'&&j.date?localISO(plusDays(new Date(`${j.date}T12:00:00`),2)):'')}});
set('dge-jobs',jobs);

// Keep the original card's favorite/details controls.
const previousScheduleCard=jobCard;
jobCard=function(j){let html=previousScheduleCard(j);const location=`${esc(j.city||'')}${j.area?`, ${esc(j.area)}`:''}`,date=`${esc(jobPeriod(j))}`,duration=`${esc(jobDuration(j))}`;const meta=`<div class="meta schedule-card-meta"><span class="job-location">${location}</span><span>${date}</span><span>${duration}</span></div>`;const start=html.indexOf('<div class="meta">'),end=html.indexOf('</div>',start);if(start>=0&&end>=0)html=html.slice(0,start)+meta+html.slice(end+6);const ps=html.indexOf('<div class="price">'),pe=html.indexOf('</div>',ps);if(ps>=0&&pe>=0)html=html.slice(0,ps)+`<div class="price${payKind(j)==='fixed'?' price-fixed':''}">${esc(payLabel(j))}${payKind(j)==='fixed'?' / ფიქსირებული':''}</div>`+html.slice(pe+6);return html};

const scheduleDateFilter=()=>get('dge-date-filter',null);
const dateModeLabel=mode=>({today:'დღეს',tomorrow:'ხვალ',week:'ამ კვირაში',agreement:'შეთანხმებით'}[mode]||'');
function siteFilterSelectMarkup(name,id,label,value,items,selectAttributes='',fieldClass=''){const current=items.find(([kind])=>kind===value)?.[1]||items[0][1],sizeClass=name==='paymentType'?'payment-filter-field':name==='duration'?'duration-filter-field':'';return `<div class="field site-filter-field ${sizeClass} ${fieldClass}"><label id="${id}-label" for="${id}-trigger">${esc(label)}</label><div class="site-filter-select" data-site-filter-select><select class="site-filter-native" name="${esc(name)}" id="${id}" ${selectAttributes} tabindex="-1" aria-hidden="true">${items.map(([kind,text])=>`<option value="${esc(kind)}" ${kind===value?'selected':''}>${esc(text)}</option>`).join('')}</select><button class="site-filter-trigger" id="${id}-trigger" type="button" data-site-filter-trigger role="combobox" aria-haspopup="listbox" aria-expanded="false" aria-controls="${id}-options" aria-labelledby="${id}-label ${id}-value"><span id="${id}-value" data-site-filter-current>${esc(current)}</span><svg class="site-filter-chevron" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><div class="site-filter-menu" id="${id}-options" role="listbox" aria-labelledby="${id}-label" hidden>${items.map(([kind,text])=>`<button class="site-filter-option" type="button" role="option" data-site-filter-option="${esc(kind)}" aria-selected="${kind===value}"><span>${esc(text)}</span><span class="site-filter-check" aria-hidden="true">✓</span></button>`).join('')}</div></div></div>`}
function formPaymentSelectMarkup(id,label,value,selectAttributes='required'){return siteFilterSelectMarkup('paymentType',id,label,value,formPaymentKinds,selectAttributes,'site-form-select-field')}
function formDurationSelectMarkup(value){return siteFilterSelectMarkup('duration','post-duration','სამუშაოს ხანგრძლივობა *',value,[['','აირჩიე ხანგრძლივობა'],...scheduleDurations],'','site-form-select-field')}
function formChoiceSelectMarkup(name,id,label,value,items,selectAttributes=''){return siteFilterSelectMarkup(name,id,label,value,items,selectAttributes,'site-form-select-field')}
function paymentFilterMarkup(value='all'){return siteFilterSelectMarkup('paymentType','filter-payment','ანაზღაურების ტიპი',value,paymentKinds)}
function durationFilterMarkup(value=''){return siteFilterSelectMarkup('duration','filter-duration','ხანგრძლივობა',value,[['','ნებისმიერი'],...scheduleDurations])}
function syncSiteFilterSelect(widget){const select=widget?.querySelector('.site-filter-native');if(!select)return;const current=widget.querySelector('[data-site-filter-current]');if(current)current.textContent=select.selectedOptions[0]?.textContent||'';widget.querySelectorAll('[data-site-filter-option]').forEach(option=>option.setAttribute('aria-selected',String(option.dataset.siteFilterOption===select.value)))}
function scheduleJobsPage(){const q=new URLSearchParams(location.hash.split('?')[1]||''),mains=q.getAll('category'),subs=q.getAll('subcategory'),selectedCategories=mains.map((main,index)=>({main,sub:subs[index]||''})).filter(entry=>entry.main),cat=q.get('category')||'',sub=q.get('subcategory')||'',city=q.get('city')||'',area=q.get('area')||'',term=q.get('q')||'';if(scheduleDateFilter()?.mode==='date')set('dge-date-filter',null);const savedDate=scheduleDateFilter();const payment=q.get('payment')||'all',dur=q.get('duration')||'';return layout('დღიური სამუშაოს ძებნა','იპოვე დღიური სამუშაო შენთვის სასურველ დროსა და ადგილას',`<form id="filters" class="schedule-filter-panel">
  <div class="primary-filters"><div class="field primary-search"><label for="filter-term">რა სამუშაოს ეძებ?</label><input id="filter-term" name="q" placeholder="ძაღლის გასეირნება, დასუფთავება, გადატანა" value="${esc(term)}"></div><button type="button" class="mobile-filter-toggle" data-mobile-filter-toggle aria-expanded="false" aria-controls="additionalPrimaryFilters mobileAdditionalFilters"><span data-mobile-filter-label>დამატებითი ფილტრები</span><svg class="mobile-filter-chevron" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button><div class="additional-primary-filters" id="additionalPrimaryFilters"><div class="field quick-date-field"><label>როდის?</label><div class="quick-date-options"><button type="button" class="quick-date ${savedDate?.mode==='today'?'selected':''}" data-date-quick="today">დღეს</button><button type="button" class="quick-date ${savedDate?.mode==='tomorrow'?'selected':''}" data-date-quick="tomorrow">ხვალ</button><button type="button" class="quick-date ${savedDate?.mode==='week'?'selected':''}" data-date-quick="week">ამ კვირაში</button><button type="button" class="quick-date ${savedDate?.mode==='agreement'?'selected':''}" data-date-quick="agreement">შეთანხმებით</button></div></div><div class="mobile-location-fields">${locationField('city','ქალაქი',city,'','filter-city')}${locationField('area','უბანი',area,city,'filter-area')}</div></div></div>
  <div class="mobile-additional-filters" id="mobileAdditionalFilters"><div class="secondary-filters">
  ${multiCategoryPicker('category','კატეგორია','filter-category',selectedCategories)}
  ${paymentFilterMarkup(payment)}
  <div class="field min-pay-filter-field"><label for="filter-min">მინიმალური თანხა (₾)</label><input id="filter-min" name="min" type="number" min="0" placeholder="მაგ. 30" value="${esc(q.get('min')||'')}"></div>
  ${durationFilterMarkup(dur)}
  <div class="filter-actions"><button class="btn btn-primary" type="submit">🔍 ძებნა</button></div>
  </div></div>
  <div class="mobile-filter-submit"><button class="btn btn-primary" type="submit">🔍 ძებნა</button></div>
  </form><div id="scheduleChips" class="active-filters" aria-live="polite"></div><div id="jobResults"></div>`,'დღიური სამუშაოები საქართველოში')}
jobsPage=scheduleJobsPage;

const singleAssignedCategoryMatch=categoryFilterMatch;
categoryFilterMatch=function(job,main,sub){
 const filters=Array.isArray(main)?main:(main?[{main,sub}]:[]);if(!filters.length)return true;
 const assigned=Array.isArray(job.categorySelections)&&job.categorySelections.length?job.categorySelections:[{main:job.category||'',sub:job.subcategory||''}];
 return filters.some(filter=>assigned.some(entry=>singleAssignedCategoryMatch({...job,category:entry.main,subcategory:entry.sub},filter.main,filter.sub)))
};
function paymentMatches(j,kind,min){const jk=payKind(j),v=payValue(j);if(kind&&kind!=='all'&&jk!==kind)return false;if(min!==''){if(jk==='negotiable')return false;const hi=Number(j.paymentMax??v);if(hi<Number(min))return false}return true}
function dateMatches(j,filter){if(!filter)return true;const value=j.date||'';if(filter.mode==='agreement')return j.dateMode==='agreement';if(filter.mode==='today')return j.dateMode!=='agreement'&&value===scheduleToday();if(filter.mode==='tomorrow')return j.dateMode!=='agreement'&&value===localISO(plusDays(new Date(),1));if(filter.mode==='week'){const now=new Date(),monday=plusDays(now,-((now.getDay()+6)%7)),sunday=plusDays(monday,6),from=localISO(monday),to=localISO(sunday),end=j.dateEnd||value;return j.dateMode!=='agreement'&&value<=to&&end>=from}return !filter.value||value===filter.value}
function activeFilterMarkup(form){
 const f=new FormData(form),chips=[];
 const add=(key,label)=>chips.push('<button type="button" class="filter-chip" data-clear-filter="'+key+'">'+label+' <span>×</span></button>');
 if(f.get('city'))add('city','ქალაქი: '+esc(f.get('city')));
 if(f.get('area'))add('area','უბანი: '+esc(f.get('area')));
 const mains=f.getAll('category'),subs=f.getAll('subcategory'),selected=mains.map((main,index)=>({main,sub:subs[index]||''})).filter(entry=>entry.main);
 if(selected.length)add('category',selected.length===1?esc(selected[0].sub||('ყველა — '+selected[0].main)):'არჩეულია '+selected.length+' კატეგორია');
 const date=scheduleDateFilter();if(date)add('date','თარიღი: '+(date.mode==='date'?kaDate(date.value):dateModeLabel(date.mode)));
 if(f.get('paymentType')&&f.get('paymentType')!=='all')add('paymentType','ანაზღაურება: '+paymentNames[f.get('paymentType')]);
 if(f.get('min'))add('min','მინ. '+esc(f.get('min'))+' ₾');
 if(f.get('duration'))add('duration','ხანგრძლივობა: '+durationName(f.get('duration')));
 if(f.get('q'))add('q','ძებნა: '+esc(f.get('q')));
 return chips.length?'<div class="chips-heading"><strong>ფილტრები:</strong><button type="button" data-clear-all-schedule>ყველა ფილტრის გასუფთავება</button></div><div class="filter-chip-list">'+chips.join('')+'</div>':'';
}
function enhancedUpdateResults(){
 const form=document.getElementById('filters');if(!form)return;
 form.querySelectorAll('[data-site-filter-select]').forEach(syncSiteFilterSelect);
 const d=new FormData(form),mains=d.getAll('category'),subs=d.getAll('subcategory'),selectedCategories=mains.map((main,index)=>({main,sub:subs[index]||''})).filter(entry=>entry.main),city=(d.get('city')||'').trim().toLocaleLowerCase('ka'),area=(d.get('area')||'').trim().toLocaleLowerCase('ka'),term=(d.get('q')||'').trim().toLocaleLowerCase('ka'),date=scheduleDateFilter(),payment=d.get('paymentType')||'all',min=d.get('min')||'',duration=d.get('duration')||'';
 const matches=jobs.filter(j=>categoryFilterMatch(j,selectedCategories)&&(!city||(j.city||'').toLocaleLowerCase('ka').includes(city))&&districtSelectionMatches(area,j.area||j.district)&&dateMatches(j,date)&&paymentMatches(j,payment,min)&&(!duration||inferredDuration(j)===duration)&&(!term||(`${j.title} ${j.description} ${j.category} ${j.subcategory||''} ${(j.categorySelections||[]).map(entry=>`${entry.main} ${entry.sub}`).join(' ')}`).toLocaleLowerCase('ka').includes(term)));
 const chips=document.getElementById('scheduleChips');if(chips)chips.innerHTML=activeFilterMarkup(form);
 const results=document.getElementById('jobResults');if(!results)return;
 const categoryLabel=selectedCategories.length?'კატეგორია: '+(selectedCategories.length===1?esc(selectedCategories[0].sub||('ყველა — '+selectedCategories[0].main)):selectedCategories.length+' არჩეული'):'აირჩიე შენი საქმე';
 const cards=matches.length?'<div class="job-grid">'+matches.map(jobCard).join('')+'</div>':'<div class="empty"><strong>განცხადებები ვერ მოიძებნა</strong>შეცვალე ფილტრები ან სხვა სიტყვით სცადე ძებნა.<div><button class="btn btn-secondary btn-small" type="button" data-clear-all-schedule>ყველა ფილტრის გასუფთავება</button></div></div>';
 results.innerHTML='<div class="results-head"><span>ნაპოვნია <strong>'+matches.length+'</strong> განცხადება</span><span>'+categoryLabel+'</span></div>'+cards;
}
updateResults=enhancedUpdateResults;

function timePickerMarkup(name,value){const [hour,minute]=(value||'09:00').split(':');return `<div class="time-picker" data-time-picker><input class="time-picker-native" type="time" name="${esc(name)}" value="${esc(value)}" required tabindex="-1" aria-hidden="true"><button class="time-picker-trigger" type="button" data-time-trigger aria-haspopup="dialog" aria-expanded="false"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg><strong data-time-label>${esc(hour)}:${esc(minute)}</strong><span>აირჩიე დრო</span><svg class="time-chevron" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button><section class="time-picker-popover" data-time-panel role="dialog" aria-label="დროის არჩევა" hidden><header class="time-picker-heading"><strong>დროის არჩევა</strong><button type="button" data-time-cancel aria-label="დახურვა">×</button></header><div class="time-picker-columns"><div class="time-picker-column"><span>საათი</span><div class="time-picker-options time-hour-options" data-time-options="hour">${Array.from({length:24},(_,i)=>String(i).padStart(2,'0')).map(v=>`<button type="button" class="time-option" data-time-value="${v}" aria-pressed="${v===hour}">${v}</button>`).join('')}</div></div><div class="time-picker-column"><span>წუთი</span><div class="time-picker-options time-minute-options" data-time-options="minute">${Array.from({length:60},(_,i)=>String(i).padStart(2,'0')).map(v=>`<button type="button" class="time-option" data-time-value="${v}" aria-pressed="${v===minute}">${v}</button>`).join('')}</div></div></div><footer class="time-picker-actions"><button type="button" class="time-cancel-button" data-time-cancel>გაუქმება</button><button type="button" class="time-confirm-button" data-time-confirm>არჩევა</button></footer></section></div>`}

function schedulePostPage(){
 const params=new URLSearchParams(location.hash.split('?')[1]||''),editId=params.get('edit'),editingJob=editId?jobs.find(j=>j.id===editId&&j.owner===user?.email):null;
 if(editId&&!editingJob)return layout('განცხადების რედაქტირება','ამ განცხადების შეცვლის უფლება არ გაქვს.','<div class="empty"><strong>განცხადება მიუწვდომელია</strong><a class="btn btn-secondary" href="#/dashboard?tab=posts">ჩემს განცხადებებზე დაბრუნება</a></div>');
 const minDate=editingJob?.date||scheduleToday(),duration=editingJob?.duration||'',paymentType=editingJob?payKind(editingJob):'daily',amount=editingJob?(editingJob.paymentAmount??editingJob.pay??''):'',categorySelections=editingJob?.categorySelections?.length?editingJob.categorySelections:(editingJob?.category?[{main:editingJob.category,sub:editingJob.subcategory||''}]:[]),dateMode=editingJob?.dateMode||'date';
 const heading=editingJob?'განცხადების რედაქტირება':'ახალი განცხადების დამატება',description=editingJob?'შეცვალე განცხადების ინფორმაცია და შეინახე განახლებული ვერსია.':'მიუთითე სამუშაოს დეტალები და იპოვე შესაფერისი ადამიანი.';
 return layout(heading,description,`<form class="form-shell" id="postForm" data-edit-job="${esc(editingJob?.id||'')}"><div class="form-grid">
  <div class="field"><label>სამუშაოს დასახელება *</label><input name="title" required minlength="3" maxlength="35" placeholder="მაგ. ძაღლის გასეირნება" value="${esc(editingJob?.title||'')}"></div>${multiCategoryPicker('category','კატეგორია *','post-category',categorySelections)}
  <div class="field span-2"><label>სამუშაოს აღწერა *</label><textarea name="description" required minlength="15" placeholder="აღწერე შესასრულებელი საქმე">${esc(editingJob?.description||'')}</textarea></div>
  ${locationField('city','ქალაქი *',editingJob?.city||'','','post-city')}${locationField('area','უბანი / მდებარეობა *',editingJob?.area||'',editingJob?.city||'','post-area')}
  <div class="field span-2"><label>სამუშაოს თარიღი *</label><div class="post-date-options"><button type="button" class="${dateMode==='date'&&editingJob?.date===scheduleToday()?'selected':''}" data-post-date-choice="today">დღეს</button><button type="button" class="${dateMode==='date'&&editingJob?.date===localISO(plusDays(new Date(),1))?'selected':''}" data-post-date-choice="tomorrow">ხვალ</button><button type="button" class="${dateMode==='agreement'?'selected':''}" data-post-date-choice="agreement">შეთანხმებით</button><button type="button" data-post-date-choice="other">სხვა თარიღი</button></div><input type="hidden" name="dateMode" value="${esc(dateMode)}" data-post-date-mode>${kaDatePickerMarkup('date',editingJob?.date||'',{min:minDate,required:dateMode!=='agreement',hidden:dateMode==='agreement',marker:'data-post-date'})}</div>
  ${formDurationSelectMarkup(duration)}
  <div class="field post-end-date-field" ${duration==='multi-day'?'':'hidden'}><label>დასრულების თარიღი *</label>${kaDatePickerMarkup('dateEnd',editingJob?.dateEnd||'',{min:minDate,required:duration==='multi-day',marker:'data-end-date'})}</div>
  ${formPaymentSelectMarkup('post-payment-type','ანაზღაურების ტიპი *',paymentType)}
  <div class="field post-amount-field" ${paymentType==='negotiable'?'hidden':''}><label data-payment-label>${paymentType==='hourly'?'ანაზღაურება საათში (₾) *':paymentType==='fixed'?'სამუშაოს ღირებულება (₾) *':'დღიური ანაზღაურება (₾) *'}</label><input name="pay" type="number" min="1" placeholder="მაგ. 80" data-payment-amount ${paymentType==='negotiable'?'':'required'} value="${esc(amount)}"><small class="field-hint" data-payment-example>${paymentType==='hourly'?'მაგალითი: 10 ₾ / საათი':paymentType==='fixed'?'მაგალითი: 150 ₾':paymentType==='negotiable'?'ანაზღაურება: შეთანხმებით':'მაგალითი: 80 ₾ / დღე'}</small></div>
  <div class="field"><label>ტელეფონი / საკონტაქტო ინფორმაცია *</label><input name="phone" type="tel" required pattern="[+0-9 ()-]{9,}" placeholder="5XX XX XX XX" value="${esc(editingJob?.phone||'')}"></div><div class="field"><label>თქვენი სახელი *</label><input name="name" required value="${esc(editingJob?.name||user?.name||'')}" placeholder="სახელი და გვარი"></div>
  <div class="field span-2"><label>დამატებითი ინფორმაცია</label><textarea name="extra" placeholder="სასურველი გამოცდილება, საჭირო ნივთები და სხვა"></textarea></div>
  </div><button class="btn btn-primary form-submit">${editingJob?'ცვლილებების შენახვა':'განცხადების გამოქვეყნება'} →</button><div id="postMessage"></div></form>`,'ადამიანს ვეძებ')}
postPage=schedulePostPage;

// Edit a user's job-seeker profile from the combined "my posts" dashboard.
function workerProfileSkillEntries(profile){
 const stored=Array.isArray(profile?.skills)&&profile.skills.length?profile.skills:[profile?.subcategory||profile?.category].filter(Boolean),seen=new Set();
 return stored.map((value,index)=>{
  if(value&&typeof value==='object')return {main:String(value.main||''),sub:String(value.sub||'')};
  const skill=String(value||''),group=Object.entries(categoryGroups).find(([,subs])=>subs.includes(skill));
  if(group)return {main:group[0],sub:skill};
  if(categoryGroups[skill])return {main:skill,sub:''};
  if(index===0&&profile?.category)return {main:String(profile.category),sub:String(profile.subcategory||skill)};
  return {main:String(profile?.category||skill),sub:profile?.category?skill:''};
 }).filter(entry=>entry.main).filter(entry=>{const key=entry.main+'::'+entry.sub;if(seen.has(key))return false;seen.add(key);return true})
}
function workerSkillEntriesFromForm(form){
 const entries=[],seen=new Set();
 new FormData(form).getAll('workerSkill').forEach(value=>{try{const parsed=JSON.parse(value),entry={main:String(parsed.main||''),sub:String(parsed.sub||'')},key=entry.main+'::'+entry.sub;if(entry.main&&!seen.has(key)){seen.add(key);entries.push(entry)}}catch{}});
 return entries
}
const baseCategoryMenuRenderer=renderCategoryMenu;
renderCategoryMenu=function(widget,query='',selectedMain=''){
 if(!widget?.closest('[data-worker-skills-field]'))return baseCategoryMenuRenderer(widget,query,selectedMain);
 const options=widget.querySelector('[data-cat-options]'),term=query.trim().toLocaleLowerCase('ka'),selected=workerSkillEntriesFromForm(widget.closest('form'));
 selectedMain=selectedMain||widget.dataset.activeMain||'';
 const isAllSelected=main=>selected.some(entry=>entry.main===main&&!entry.sub),isSubSelected=(main,sub)=>isAllSelected(main)||selected.some(entry=>entry.main===main&&entry.sub===sub);
 if(!options)return;
 if(selectedMain&&!term){const available=(categoryGroups[selectedMain]||[]).filter(sub=>!isSubSelected(selectedMain,sub)),allOption=isAllSelected(selectedMain)?'':`<button type="button" class="category-option category-all" data-cat-all="${esc(selectedMain)}">ყველა — ${esc(selectedMain)}</button>`;options.innerHTML=allOption+available.map(sub=>`<button type="button" class="category-option" data-cat-subchoice="${esc(sub)}" data-cat-parent="${esc(selectedMain)}">→ ${esc(sub)}</button>`).join('')||'<div class="category-no-results">ყველა ქვეკატეგორია უკვე არჩეულია.</div>';widget.querySelector('[data-cat-back]').hidden=false;return}
 widget.querySelector('[data-cat-back]').hidden=!!term;const rows=[];
 for(const [main,subs]of Object.entries(categoryGroups)){const mainMatch=main.toLocaleLowerCase('ka').includes(term),matching=subs.filter(sub=>sub.toLocaleLowerCase('ka').includes(term)&&!isSubSelected(main,sub));if(!isAllSelected(main)&&(!term||mainMatch||matching.length)){rows.push(`<button type="button" class="category-option category-main" data-cat-open="${esc(main)}"><span>${categoryIcons[main]} ${esc(main)}</span><span>›</span></button>`);if(term&&(mainMatch||matching.length))rows.push(`<button type="button" class="category-option category-all" data-cat-all="${esc(main)}">ყველა — ${esc(main)}</button>`);if(term)for(const sub of matching)rows.push(`<button type="button" class="category-option category-sub" data-cat-subchoice="${esc(sub)}" data-cat-parent="${esc(main)}">→ ${esc(sub)}</button>`)}}
 options.innerHTML=rows.length?rows.join(''):'<div class="category-no-results">კატეგორია ვერ მოიძებნა</div>'
};
document.addEventListener('click',event=>{
 const remove=event.target.closest('[data-worker-skill-remove]');if(!remove)return;
 const field=remove.closest('[data-worker-skills-field]'),chip=remove.closest('[data-worker-skill-chip]'),widget=field?.querySelector('#cat-worker-skills-add'),popup=widget?.querySelector('.category-popover'),search=widget?.querySelector('[data-cat-search]'),wasOpen=!!popup&&!popup.hidden;
 chip?.remove();const error=field?.querySelector('[data-worker-skills-error]');if(error)error.hidden=true;
 if(wasOpen){renderCategoryMenu(widget,search?.value||'',widget.dataset.activeMain||'');popup.hidden=false;widget.querySelector('[data-cat-toggle]')?.setAttribute('aria-expanded','true');search?.focus({preventScroll:true})}
 event.preventDefault();event.stopImmediatePropagation()
},true);
function workerSkillChips(entries){return entries.map(entry=>{const label=entry.sub||('ყველა — '+entry.main),json=JSON.stringify(entry);return '<span class="worker-skill-chip" data-worker-skill-chip><span>'+esc(label)+'</span><button type="button" data-worker-skill-remove aria-label="'+esc(label)+' — ამოშლა"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><path d="m5 5 10 10M15 5 5 15"/></svg></button><input type="hidden" name="workerSkill" value="'+esc(json)+'"></span>'}).join('')}
function workerOfferValue(profile){return String(profile?.offer||profile?.offerTitle||'').trim()}
function workerSkillsField(profile){
 const pickerMarkup=categoryPicker('workerSkillDraft','','','კატეგორიის დამატება','worker-skills-add'),pickerStart=pickerMarkup.indexOf('<div class="category-picker"'),pickerEnd=pickerMarkup.lastIndexOf('</div>'),picker=pickerMarkup.slice(pickerStart,pickerEnd).replace('აირჩიე კატეგორია','კატეგორიის დამატება');
 return '<div class="field category-field worker-skills-field" data-worker-skills-field><label>რისი გაკეთება შემიძლია *</label><div class="worker-skill-chips" data-worker-skill-chips>'+workerSkillChips(workerProfileSkillEntries(profile))+'</div>'+picker+'<small class="field-hint">რამდენიმე კატეგორიის დამატება შეგიძლია.</small><div class="error-msg worker-skills-error" data-worker-skills-error hidden role="alert"></div></div>'
}
document.addEventListener('click',event=>{
 const remove=event.target.closest('[data-worker-skill-remove]');
 if(remove){const field=remove.closest('[data-worker-skills-field]'),chip=remove.closest('[data-worker-skill-chip]');chip?.remove();const widget=field?.querySelector('#cat-worker-skills-add'),popup=widget?.querySelector('.category-popover'),search=widget?.querySelector('[data-cat-search]');if(widget&&popup&&!popup.hidden)renderCategoryMenu(widget,search?.value||'',widget.dataset.activeMain||'');const error=field?.querySelector('[data-worker-skills-error]');if(error)error.hidden=true;return}
 const choice=event.target.closest('[data-cat-all],[data-cat-subchoice]'),widget=choice?.closest('#cat-worker-skills-add');
 if(!widget)return;
 const field=widget.closest('[data-worker-skills-field]'),main=widget.querySelector('[data-cat-main]').value,sub=widget.querySelector('[data-cat-sub]').value,entries=workerSkillEntriesFromForm(field.closest('form'));
 if(main&&!entries.some(entry=>entry.main===main&&(!sub?!entry.sub:entry.sub===sub)))entries.push({main,sub});
 if(main&&!sub){for(let index=entries.length-1;index>=0;index--)if(entries[index].main===main&&entries[index].sub)entries.splice(index,1)}
 field.querySelector('[data-worker-skill-chips]').innerHTML=workerSkillChips(entries);
 widget.querySelector('[data-cat-main]').value='';widget.querySelector('[data-cat-sub]').value='';widget.querySelector('[data-cat-value]').textContent='კატეგორიის დამატება';
 widget.dataset.activeMain=main;const search=widget.querySelector('[data-cat-search]');search.value='';renderCategoryMenu(widget,'',main);widget.querySelector('.category-popover').hidden=false;widget.querySelector('[data-cat-toggle]').setAttribute('aria-expanded','true');search.focus({preventScroll:true});event.preventDefault();event.stopImmediatePropagation();
 const error=field.querySelector('[data-worker-skills-error]');if(error)error.hidden=true
});
document.addEventListener('submit',event=>{
 const form=event.target.closest('#workerProfileForm');if(!form||workerSkillEntriesFromForm(form).length)return;
 event.preventDefault();event.stopImmediatePropagation();const error=form.querySelector('[data-worker-skills-error]');if(error){error.textContent='აირჩიე ერთი ან რამდენიმე კატეგორია.';error.hidden=false}form.querySelector('#cat-worker-skills-add [data-cat-toggle]')?.focus()
},true);
document.addEventListener('submit',event=>{const form=event.target.closest('#workerProfileForm');if(!form)return;const offer=form.querySelector('[name="offer"]'),normalizedOffer=String(offer?.value||'').trim();if(offer){offer.value=normalizedOffer;if(normalizedOffer.length>35){event.preventDefault();event.stopImmediatePropagation();offer.focus();form.querySelector('#workerMessage').innerHTML='<div class="error-msg">რას სთავაზობ? ველში მაქსიმუმ 35 სიმბოლო ჩაწერე.</div>';return}if(normalizedOffer.length<3){event.preventDefault();event.stopImmediatePropagation();offer.focus();form.querySelector('#workerMessage').innerHTML='<div class="error-msg">მიუთითე, რას სთავაზობ (მინიმუმ 3 სიმბოლო).</div>';return}}for(const [selector,message] of [['[data-worker-has-experience]','მიუთითე, გაქვს თუ არა გამოცდილება.'],['[name="availability"]','აირჩიე ხელმისაწვდომობის დრო.']]){const select=form.querySelector(selector);if(select?.value)continue;event.preventDefault();event.stopImmediatePropagation();const widget=select?.closest('[data-site-filter-select]');widget?.classList.add('has-error');widget?.querySelector('[data-site-filter-trigger]')?.focus();form.querySelector('#workerMessage').innerHTML=`<div class="error-msg">${message}</div>`;return}},true);
function scheduleWorkerProfileForm(){
 const params=new URLSearchParams(location.hash.split('?')[1]||''),editId=params.get('edit'),profile=editId?get('dge-workers',[]).find(row=>row.id===editId&&(row.owner===user?.email||row.email===user?.email)):null;
 if(editId&&!profile)return layout('პროფილის რედაქტირება','ამ პროფილის შეცვლის უფლება არ გაქვს.','<div class="empty"><strong>პროფილი მიუწვდომელია</strong><a class="btn btn-secondary" href="#/dashboard?tab=posts">ჩემს განცხადებებზე დაბრუნება</a></div>');
 const kind=profile?.paymentType||'daily',pay=profile?.pay??profile?.paymentAmount??'',negotiable=kind==='negotiable',hasExperience=profile?.hasExperience===true||profile?.hasExperience==='yes'?'yes':profile?.hasExperience===false||profile?.hasExperience==='no'?'no':profile?.exp?'yes':'',experienceDuration=profile?.experienceDuration||profile?.exp||'',experienceField=siteFilterSelectMarkup('experienceDuration','worker-experience-duration','რამდენი ხანია გაქვს გამოცდილება? *',experienceDuration,[['','აირჩიე ხანგრძლივობა'],...experienceDurations.map(value=>[value,value])],hasExperience==='yes'?'required':'','site-form-select-field worker-experience-duration-field').replace('<div class="field site-filter-field ','<div'+(hasExperience==='yes'?'':' hidden')+' class="field site-filter-field ');
 return layout(profile?'სამუშაოს ძებნის პროფილის რედაქტირება':'სამუშაოს ძებნის პროფილი',profile?'შეცვალე არსებული პირობები და შეინახე განახლებული პროფილი.':'შეავსე პროფილი, რომ დამსაქმებლებმა შესაფერისი საქმე შემოგთავაზონ.',`<form class="form-shell" id="workerProfileForm" data-edit-worker="${esc(profile?.id||'')}"><div class="form-grid">
  <div class="field"><label>სახელი *</label><input name="name" required value="${esc(profile?.name||user?.name||'')}" placeholder="სახელი და გვარი"></div><div class="field"><label>რას სთავაზობ? *</label><input name="offer" required minlength="3" maxlength="35" value="${esc(workerOfferValue(profile))}" placeholder="მაგ. ბინის დალაგება, ბავშვის მოვლა, ავეჯის აწყობა"><small class="field-hint">მაქსიმუმ 35 სიმბოლო.</small></div>
  ${locationField('city','ქალაქი *',profile?.city||'','','worker-city')}${locationField('area','უბანი *',profile?.area||profile?.district||'',profile?.city||'','worker-area')}${workerSkillsField(profile)}
  ${formChoiceSelectMarkup('hasExperience','worker-has-experience','გამოცდილება გაქვს? *',hasExperience,[['','აირჩიე'],['no','არა'],['yes','დიახ']],'data-worker-has-experience')}
  ${experienceField}
  ${formPaymentSelectMarkup('worker-payment-type','ანაზღაურების პირობა *',kind,'required data-worker-payment-type')}
  <div class="field" data-worker-pay-field ${negotiable?'hidden':''}><label data-worker-pay-label>${kind==='hourly'?'სასურველი ანაზღაურება (₾ / საათში) *':kind==='fixed'?'სასურველი ფიქსირებული თანხა (₾) *':'სასურველი დღიური ანაზღაურება (₾) *'}</label><input name="pay" type="number" min="1" placeholder="მაგ. 80" ${negotiable?'':'required'} value="${esc(pay)}"><small class="field-hint" data-worker-pay-hint>${kind==='hourly'?'მიუთითე სასურველი საათობრივი თანხა.':kind==='fixed'?'მიუთითე სასურველი სრული თანხა.':'მიუთითე სასურველი დღიური თანხა.'}</small></div>
  ${formChoiceSelectMarkup('availability','worker-availability','როდის ვარ ხელმისაწვდომი *',profile?.availability||'',[['','აირჩიე'],...['დღესვე','ხვალიდან','ამ კვირაში','შეთანხმებით'].map(value=>[value,value])])}<div class="field"><label>საკონტაქტო ინფორმაცია *</label><input name="phone" type="tel" required placeholder="5XX XX XX XX" value="${esc(profile?.phone||'')}"></div>
  <div class="field span-2"><label>მოკლე აღწერა *</label><textarea name="about" required minlength="15" placeholder="მოგვიყევი შენს გამოცდილებასა და უნარებზე">${esc(profile?.about||'')}</textarea></div></div><button class="btn btn-primary form-submit">${profile?'ცვლილებების შენახვა':'პროფილის გამოქვეყნება'} →</button><div id="workerMessage"></div></form>`,'სამუშაოს ვეძებ')
}
workerProfileForm=scheduleWorkerProfileForm;

document.addEventListener('submit',event=>{
 const form=event.target.closest('#workerProfileForm'),id=form?.dataset.editWorker;
 if(!id)return;
 event.preventDefault();event.stopImmediatePropagation();
 const profile=get('dge-workers',[]).find(row=>row.id===id&&(row.owner===user?.email||row.email===user?.email));
 if(!profile){document.getElementById('workerMessage').innerHTML='<div class="error-msg">ამ პროფილის შეცვლის უფლება არ გაქვს.</div>';return}
 const data=new FormData(form),skills=workerSkillEntriesFromForm(form),main=skills[0]?.main||'',sub=skills[0]?.sub||'',kind=String(data.get('paymentType')||'daily'),name=String(data.get('name')||'').trim();
 Object.assign(profile,{name,city:String(data.get('city')||''),area:String(data.get('area')||''),district:String(data.get('area')||''),skills:skills.map(skill=>skill.sub||skill.main),category:main,subcategory:sub,hasExperience:data.get('hasExperience')==='yes',experienceDuration:data.get('hasExperience')==='yes'?String(data.get('experienceDuration')||''):'',exp:data.get('hasExperience')==='yes'?String(data.get('experienceDuration')||''):'',paymentType:kind,pay:kind==='negotiable'?null:Number(data.get('pay')||0),availability:String(data.get('availability')||''),offer:String(data.get('offer')||'').trim(),about:String(data.get('about')||'').trim(),phone:String(data.get('phone')||'').trim(),initials:name.split(' ').map(value=>value[0]).slice(0,2).join(''),updatedAt:Date.now()});
 const profiles=get('dge-workers',[]);set('dge-workers',profiles);notify('პროფილი განახლდა');document.getElementById('workerMessage').innerHTML='<div class="success-box">ცვლილებები შენახულია. გადავდივართ შენს განცხადებებზე…</div>';setTimeout(()=>location.hash='#/dashboard?tab=posts',650)
},true);

// Edit an owned announcement in place, keeping its identity, owner and workflow status intact.
document.addEventListener('submit',e=>{
 const form=e.target.closest('#postForm'),id=form?.dataset.editJob;
 if(!id)return;
 e.preventDefault();e.stopImmediatePropagation();
 const job=jobs.find(item=>item.id===id&&item.owner===user?.email);
 if(!job){document.getElementById('postMessage').innerHTML='<div class="error-msg">ამ განცხადების შეცვლის უფლება არ გაქვს.</div>';return}
 const data=new FormData(form),categorySelections=categoryPickerSelections(form.querySelector('#cat-post-category')),date=String(data.get('date')||''),dateEnd=String(data.get('dateEnd')||''),duration=data.get('duration')||'';
 if(data.get('dateMode')!=='agreement'&&duration==='multi-day'&&(!dateEnd||dateEnd<date)){document.getElementById('postMessage').innerHTML='<div class="error-msg">დასრულების თარიღი დაწყების თარიღს უნდა ემთხვეოდეს ან გვიან იყოს.</div>';return}
 const kind=data.get('paymentType')||'daily',pay=kind==='negotiable'?null:Number(data.get('pay')||0),extra=String(data.get('extra')||'').trim();
 Object.assign(job,{title:String(data.get('title')||'').trim(),category:categorySelections[0]?.main||'',subcategory:categorySelections[0]?.sub||'',categorySelections,description:String(data.get('description')||'').trim()+(extra?` ${extra}`:''),city:String(data.get('city')||''),area:String(data.get('area')||''),district:String(data.get('area')||''),date:data.get('dateMode')==='agreement'?'':date,dateMode:data.get('dateMode')==='agreement'?'agreement':'date',dateEnd:data.get('dateMode')==='agreement'?'':duration==='multi-day'?dateEnd:'',start:job.start||'',end:job.end||'',startTime:job.startTime||job.start||'',endTime:job.endTime||job.end||'',duration,paymentType:kind,paymentAmount:pay,paymentMin:pay,paymentMax:pay,pay:pay||0,phone:String(data.get('phone')||''),name:String(data.get('name')||''),updatedAt:Date.now()});
 set('dge-jobs',jobs);notify('განცხადება განახლდა');
 document.getElementById('postMessage').innerHTML='<div class="success-box">ცვლილებები შენახულია. გადავდივართ შენს განცხადებებზე…</div>';
 setTimeout(()=>location.hash='#/dashboard?tab=posts',650);
},true);

// Add structured fields at the creation point used by the original posting flow.
// The legacy handler still reads name=pay; augment the newly-created record immediately before storage.
document.addEventListener('submit',e=>{if(e.target.id!=='postForm')return;const form=e.target,d=new FormData(form),categorySelections=categoryPickerSelections(form.querySelector('#cat-post-category'));if(d.get('dateMode')!=='agreement'&&d.get('duration')==='multi-day'&&(!d.get('dateEnd')||d.get('dateEnd')<d.get('date'))){e.preventDefault();e.stopImmediatePropagation();document.getElementById('postMessage').innerHTML='<div class="error-msg">დასრულების თარიღი დაწყების თარიღს უნდა ემთხვეოდეს ან გვიან იყოს.</div>';return}setTimeout(()=>{const j=jobs[0];if(!j||j.title!==d.get('title'))return;j.district=j.area;j.categorySelections=categorySelections;if(categorySelections[0]){j.category=categorySelections[0].main;j.subcategory=categorySelections[0].sub}j.startTime=j.start;j.endTime=j.end;j.duration=d.get('duration');j.dateMode=d.get('dateMode')==='agreement'?'agreement':'date';if(j.dateMode==='agreement'){j.date='';j.dateEnd=''}else j.dateEnd=d.get('dateEnd')||'';j.paymentType=d.get('paymentType')||'daily';j.paymentAmount=j.paymentType==='negotiable'?null:Number(d.get('pay')||0);j.paymentMin=j.paymentAmount;j.paymentMax=j.paymentAmount;set('dge-jobs',jobs)},0)},true);

const oldDetails=details;details=function(id){let html=oldDetails(id),j=jobs.find(x=>x.id===id);if(!j)return html;const start=html.indexOf('<div class="detail-meta">'),end=html.indexOf('<h3>სამუშაოს აღწერა</h3>',start);if(start<0||end<0)return html;const exactDate=j.dateMode==='agreement'?'შეთანხმებით':j.dateEnd&&j.dateEnd!==j.date?`${kaDate(j.date)} — ${kaDate(j.dateEnd)}`:kaDate(j.date);const info=`<div class="detail-meta schedule-detail-meta"><div><small>სამუშაოს თარიღი</small><strong>${esc(exactDate)}</strong></div>${j.startTime||j.start?`<div><small>სამუშაოს დრო</small><strong>${esc(j.startTime||j.start)}–${esc(j.endTime||j.end||'')}</strong></div>`:''}<div><small>ხანგრძლივობა</small><strong>${esc(jobDuration(j))}</strong></div><div><small>ანაზღაურების ტიპი</small><strong>${esc(paymentNames[payKind(j)]||paymentNames.daily)}</strong></div><div><small>ანაზღაურება</small><strong>${esc(payLabel(j))}</strong></div><div><small>მდებარეობა</small><strong>${esc(j.city||'')}${j.area?`, ${esc(j.area)}`:''}</strong></div><div><small>კატეგორია</small><strong>${esc(j.category||'')}${j.subcategory?` · ${esc(j.subcategory)}`:''}</strong></div></div>`;return (html.slice(0,start)+info+html.slice(end)).replace('<article class="detail-main">','<article class="detail-main schedule-job-detail">')};

function refreshSchedule(){updateResults()}
function closeSiteFilterSelect(widget,restoreFocus=false){if(!widget)return;widget.classList.remove('is-open');widget.querySelector('[data-site-filter-trigger]')?.setAttribute('aria-expanded','false');widget.querySelector('.site-filter-menu')?.setAttribute('hidden','');if(restoreFocus)widget.querySelector('[data-site-filter-trigger]')?.focus()}
function openSiteFilterSelect(widget){if(!widget)return;document.querySelectorAll('[data-site-filter-select].is-open').forEach(open=>closeSiteFilterSelect(open));widget.classList.add('is-open');const trigger=widget.querySelector('[data-site-filter-trigger]'),menu=widget.querySelector('.site-filter-menu');trigger?.setAttribute('aria-expanded','true');if(menu)menu.hidden=false;const bounds=trigger?.getBoundingClientRect(),spaceBelow=bounds?window.innerHeight-bounds.bottom:window.innerHeight,opensUp=!!bounds&&spaceBelow<180&&bounds.top>spaceBelow;widget.classList.toggle('opens-up',opensUp);if(menu)menu.style.maxHeight=opensUp?'':`${Math.max(140,Math.min(280,window.innerHeight*.42,spaceBelow-8))}px`;widget.querySelector('[data-site-filter-option][aria-selected="true"]')?.focus()}
document.addEventListener('click',e=>{const trigger=e.target.closest('[data-site-filter-trigger]');if(trigger){const widget=trigger.closest('[data-site-filter-select]');if(widget.classList.contains('is-open'))closeSiteFilterSelect(widget);else openSiteFilterSelect(widget);return}const option=e.target.closest('[data-site-filter-option]');if(option){const widget=option.closest('[data-site-filter-select]'),select=widget?.querySelector('.site-filter-native'),triggerButton=widget?.querySelector('[data-site-filter-trigger]');if(!widget||!select)return;select.value=option.dataset.siteFilterOption;syncSiteFilterSelect(widget);closeSiteFilterSelect(widget);select.dispatchEvent(new Event('change',{bubbles:true}));triggerButton?.focus();return}if(!e.target.closest('[data-site-filter-select]'))document.querySelectorAll('[data-site-filter-select].is-open').forEach(widget=>closeSiteFilterSelect(widget))});
document.addEventListener('keydown',e=>{const trigger=e.target.closest('[data-site-filter-trigger]');if(trigger&&(e.key==='ArrowDown'||e.key==='ArrowUp')){e.preventDefault();const widget=trigger.closest('[data-site-filter-select]');if(widget&&!widget.classList.contains('is-open'))openSiteFilterSelect(widget);else widget?.querySelector('[data-site-filter-option][aria-selected="true"]')?.focus();return}const option=e.target.closest('[data-site-filter-option]');if(!option)return;const widget=option.closest('[data-site-filter-select]'),options=[...widget.querySelectorAll('[data-site-filter-option]')],index=options.indexOf(option);if(e.key==='Escape'){e.preventDefault();closeSiteFilterSelect(widget,true);return}let next=index;if(e.key==='ArrowDown')next=(index+1)%options.length;else if(e.key==='ArrowUp')next=(index-1+options.length)%options.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=options.length-1;else return;e.preventDefault();options[next]?.focus()});
document.addEventListener('focusin',e=>{document.querySelectorAll('[data-site-filter-select].is-open').forEach(widget=>{if(!widget.contains(e.target))closeSiteFilterSelect(widget)})});
document.addEventListener('input',e=>{if(e.target.closest('#filters')&&!e.target.matches('[data-cat-search]'))refreshSchedule();if(e.target.matches('[data-post-date]')){const end=document.querySelector('[data-end-date]');if(end)end.min=e.target.value||scheduleToday()}});
document.addEventListener('change',e=>{if(e.target.matches('#filters select,#filters input'))refreshSchedule();if(e.target.matches('[data-post-date]'))refreshSchedule();if(e.target.matches('#postForm [name="paymentType"]')){const form=e.target.form,kind=e.target.value,amount=form.querySelector('[data-payment-amount]'),box=form.querySelector('.post-amount-field'),label=form.querySelector('[data-payment-label]'),example=form.querySelector('[data-payment-example]'),labels={hourly:['ანაზღაურება საათში (₾) *','მაგალითი: 10 ₾ / საათი'],daily:['დღიური ანაზღაურება (₾) *','მაგალითი: 80 ₾ / დღე'],fixed:['სამუშაოს ღირებულება (₾) *','მაგალითი: 150 ₾'],negotiable:['ანაზღაურება','ანაზღაურება: შეთანხმებით']};label.textContent=labels[kind][0];example.textContent=labels[kind][1];box.hidden=kind==='negotiable';amount.required=kind!=='negotiable';if(kind==='negotiable')amount.value=''}if(e.target.matches('#post-duration')){const box=document.querySelector('.post-end-date-field'),end=document.querySelector('[data-end-date]'),multi=e.target.value==='multi-day';box.hidden=!multi;end.required=multi;if(!multi)end.value=''}});
document.addEventListener('change',e=>{if(!e.target.matches('#workerProfileForm [data-worker-has-experience]'))return;const hasExperience=e.target.value==='yes',box=e.target.form.querySelector('.worker-experience-duration-field'),duration=e.target.form.querySelector('[name="experienceDuration"]');box.hidden=!hasExperience;duration.required=hasExperience;if(!hasExperience){duration.value='';syncSiteFilterSelect(box)}});
function closeTimePicker(picker){if(!picker)return;picker.querySelector('[data-time-panel]').hidden=true;picker.querySelector('[data-time-trigger]').setAttribute('aria-expanded','false')}
function syncTimePickerOptions(picker){const [hour,minute]=(picker.querySelector('.time-picker-native').value||'09:00').split(':');picker.dataset.draftHour=hour;picker.dataset.draftMinute=minute;picker.querySelectorAll('[data-time-options="hour"] .time-option').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.timeValue===hour)));picker.querySelectorAll('[data-time-options="minute"] .time-option').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.timeValue===minute)))}
document.addEventListener('click',e=>{const trigger=e.target.closest('[data-time-trigger]');if(trigger){const picker=trigger.closest('[data-time-picker]'),panel=picker.querySelector('[data-time-panel]'),open=!panel.hidden;document.querySelectorAll('[data-time-panel]:not([hidden])').forEach(p=>closeTimePicker(p.closest('[data-time-picker]')));if(!open){syncTimePickerOptions(picker);panel.hidden=false;trigger.setAttribute('aria-expanded','true');picker.querySelector('[aria-pressed="true"]')?.scrollIntoView({block:'nearest'})}return}const option=e.target.closest('.time-option');if(option){const picker=option.closest('[data-time-picker]'),type=option.closest('[data-time-options]').dataset.timeOptions;picker.dataset[type==='hour'?'draftHour':'draftMinute']=option.dataset.timeValue;option.parentElement.querySelectorAll('.time-option').forEach(b=>b.setAttribute('aria-pressed',String(b===option)));return}const confirm=e.target.closest('[data-time-confirm]');if(confirm){const picker=confirm.closest('[data-time-picker]'),hour=picker.dataset.draftHour||'09',minute=picker.dataset.draftMinute||'00',input=picker.querySelector('.time-picker-native');input.value=`${hour}:${minute}`;picker.querySelector('[data-time-label]').textContent=input.value;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));closeTimePicker(picker);picker.querySelector('[data-time-trigger]').focus();return}const cancel=e.target.closest('[data-time-cancel]');if(cancel){closeTimePicker(cancel.closest('[data-time-picker]'));return}if(!e.target.closest('[data-time-picker]'))document.querySelectorAll('[data-time-panel]:not([hidden])').forEach(p=>closeTimePicker(p.closest('[data-time-picker]')))});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('[data-time-panel]:not([hidden])').forEach(p=>{const picker=p.closest('[data-time-picker]');closeTimePicker(picker);picker.querySelector('[data-time-trigger]').focus()})});
document.addEventListener('click',e=>{const quick=e.target.closest('[data-date-quick]');if(quick){const mode=quick.dataset.dateQuick;const active=scheduleDateFilter(),clear=active?.mode===mode;set('dge-date-filter',clear?null:{mode});document.querySelectorAll('[data-date-quick]').forEach(b=>b.classList.toggle('selected',!clear&&b===quick));updateResults();return}const postChoice=e.target.closest('[data-post-date-choice]');if(postChoice){const input=document.querySelector('[data-post-date]'),choice=postChoice.dataset.postDateChoice;if(choice==='other'){input.focus();try{input.showPicker?.()}catch{}}else input.value=choice==='today'?scheduleToday():localISO(plusDays(new Date(),1));input.dispatchEvent(new Event('change',{bubbles:true}));return}if(e.target.closest('[data-more-filters]')){const b=e.target.closest('[data-more-filters]'),box=document.querySelector('[data-advanced-filters]'),open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));box.classList.toggle('expanded',!open);b.textContent=open?'მეტი ფილტრი':'ნაკლები ფილტრი';return}const clear=e.target.closest('[data-clear-filter]');if(clear){const f=document.getElementById('filters'),key=clear.dataset.clearFilter;if(key==='date'){set('dge-date-filter',null);document.querySelectorAll('[data-date-quick]').forEach(b=>b.classList.remove('selected'))}else if(key==='category'){setCategoryPickerSelections(f.querySelector('[data-cat-multiple="true"]'),[])}else if(key==='paymentType'){f.elements.paymentType.value='all';f.elements.min.value=''}else if(f.elements[key])f.elements[key].value='';updateResults();return}if(e.target.closest('[data-clear-all-schedule]')){const f=document.getElementById('filters');f.reset();for(const name of ['city','area','date','min','duration','q'])if(f.elements[name])f.elements[name].value='';f.elements.paymentType.value='all';set('dge-date-filter',null);setCategoryPickerSelections(f.querySelector('[data-cat-multiple="true"]'),[]);document.querySelectorAll('[data-date-quick]').forEach(b=>b.classList.remove('selected'));updateResults()}});


render=routeView;routeView();

