/* Account-aware saved jobs, reveal-on-click contacts, conversations and reports. */
const savedJobsKey='dge-saved-users',chatStoreKey='dge-conversations',reportStoreKey='dge-reports';
let savedJobsByUser=get(savedJobsKey,{}),savedAccount=user?.email||null;
if(user){if(!Object.prototype.hasOwnProperty.call(savedJobsByUser,user.email)){savedJobsByUser[user.email]=get('dge-saved',[]);set(savedJobsKey,savedJobsByUser)}saved=[...(savedJobsByUser[user.email]||[])];set('dge-saved',saved)}else saved=[];
function savedFavoritesCount(){const profilesByUser=get('dge-saved-profiles-users',{}),profiles=user?.email&&Array.isArray(profilesByUser[user.email])?profilesByUser[user.email]:[];return saved.length+profiles.length}

function activateSavedAccount(){const email=user?.email||null;if(email===savedAccount)return;if(savedAccount){savedJobsByUser[savedAccount]=[...saved];set(savedJobsKey,savedJobsByUser)}savedAccount=email;if(email){saved=[...(savedJobsByUser[email]||[])];set('dge-saved',saved)}else{saved=[];localStorage.removeItem('dge-saved')}}
function persistSaved(){if(!user)return;savedJobsByUser[user.email]=[...saved];set(savedJobsKey,savedJobsByUser);set('dge-saved',saved)}
function saveModal(id){document.querySelector('[data-save-modal]')?.remove();const m=document.createElement('div');m.className='modal-backdrop social-modal-backdrop';m.dataset.saveModal='';m.innerHTML=`<section class="social-modal save-prompt-modal" role="dialog" aria-modal="true" aria-labelledby="saveModalTitle"><button class="social-modal-close" type="button" data-close-social aria-label="დახურვა"><svg class="social-modal-close-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button><span class="social-modal-icon" aria-hidden="true"><svg class="save-prompt-icon" viewBox="0 0 48 48" fill="none" focusable="false"><path class="save-prompt-heart" d="M24 39S9 30.5 9 18.5a8.5 8.5 0 0 1 15-5.5 8.5 8.5 0 0 1 15 5.5C39 30.5 24 39 24 39Z"/><path class="save-prompt-spark" d="M8 8v6M5 11h6M39 31v7M35.5 34.5h7M39 7v3M37 8.5h4"/></svg></span><h2 id="saveModalTitle">განცხადების შესანახად საჭიროა შესვლა</h2><p>შედი ან შექმენი ანგარიში შენახული განცხადებების სამართავად.</p><div class="social-modal-actions"><button class="btn btn-primary" type="button" data-save-auth="login">შესვლა</button><button class="btn btn-secondary" type="button" data-save-auth="register">რეგისტრაცია</button></div></section>`;m.dataset.job=id;document.body.append(m)}
function setSaveButton(button,isSaved){button.classList.toggle('saved',isSaved);button.setAttribute('aria-label',isSaved?'შენახულია':'შენახვა');button.setAttribute('aria-pressed',String(isSaved));button.innerHTML='<span class="save-heart" aria-hidden="true">'+(isSaved?'♥':'♡')+'</span><span class="save-label">'+(isSaved?(location.hash.split('?')[0]==='#/saved'?'წაშლა შენახულებიდან':'შენახულია'):'შენახვა')+'</span>';button.title=isSaved?'შენახულებიდან წაშლა':'განცხადების შენახვა'}
function refreshSaveButtons(id){document.querySelectorAll('[data-save]').forEach(b=>{if(!id||b.dataset.save===id)setSaveButton(b,saved.includes(b.dataset.save))})}
const unsocialJobCard=jobCard;jobCard=function(j){let html=unsocialJobCard(j);return html.replace(/<button class="save-btn ([^"]*)" data-save="([^"]+)" aria-label="შენახვა">[♡♥]<\/button>/g,(all,cls,id)=>`<button class="save-btn ${cls} saved-action" data-save="${id}" aria-label="შენახვა"></button>`).replace(/<button class="save-btn ([^"]*) saved-action" data-save="([^"]+)" aria-label="შენახვა"><\/button>/g,(all,cls,id)=>`<button class="save-btn ${cls} saved-action" data-save="${id}" aria-label="შენახვა"><span class="save-heart" aria-hidden="true">${saved.includes(id)?'♥':'♡'}</span><span class="save-label">${saved.includes(id)?(location.hash.split('?')[0]==='#/saved'?'წაშლა შენახულებიდან':'შენახულია'):'შენახვა'}</span></button>`)};
const unsocialSavedPage=savedPage;savedPage=function(){if(!user)return layout('♡ შენახული განცხადებები','შენახული განცხადებები მხოლოდ ანგარიშზე შესვლის შემდეგ არის ხელმისაწვდომი.','<div class="empty"><strong>შედი ანგარიშზე შენახული განცხადებების სანახავად</strong><a class="btn btn-primary btn-small" href="#/login" style="margin-top:12px">შესვლა / რეგისტრაცია</a></div>');const list=jobs.filter(j=>saved.includes(j.id));return layout('♡ შენახული განცხადებები','აქ ნახავ შენ მიერ შენახულ ყველა განცხადებას.',list.length?`<div class="job-grid saved-job-grid">${list.map(jobCard).join('')}</div>`:'<div class="empty"><strong>შენახული განცხადებები ჯერ არ გაქვს.</strong><a href="#/jobs" class="btn btn-primary btn-small" style="margin-top:12px">სამუშაოს ძებნა</a></div>')};

function accountNavigation(){const nav=document.getElementById('nav');if(!nav)return;const common='<a href="#/">მთავარი</a><a href="#/jobs">სამუშაოს ძებნა</a><a href="#/workers">ადამიანის ძებნა</a><a href="#/how">როგორ მუშაობს</a>';if(!user){nav.innerHTML=`${common}<a class="nav-auth" href="#/login">შესვლა / რეგისტრაცია</a>`;return}const myPosts=jobs.filter(j=>j.owner===user.email).length+get('dge-workers',[]).filter(profile=>profile.owner===user.email||profile.email===user.email).length,favoritesCount=savedFavoritesCount();nav.innerHTML=`${common}<div class="account-nav"><button type="button" class="account-nav-trigger" data-account-toggle aria-expanded="false">👤 ${esc(user.name)} <span>⌄</span></button><div class="account-dropdown" data-account-dropdown hidden><a href="#/profile">👤 პროფილი და პარამეტრები</a><a href="#/dashboard?tab=posts">📋 ჩემი განცხადებები (${myPosts})</a><a href="#/saved">♡ შენახული განცხადებები${favoritesCount?` (${favoritesCount})`:''}</a><a href="#/messages">💬 შეტყობინებები</a><a href="#/" data-logout>🚪 გასვლა</a></div></div>`;const trigger=nav.querySelector('[data-account-toggle]'),panel=nav.querySelector('[data-account-dropdown]');trigger?.addEventListener('click',event=>{event.preventDefault();document.getElementById('nav')?.classList.remove('open');setAccountMenuState(trigger,panel,trigger.getAttribute('aria-expanded')!=='true')})}
const beforeSocialDashboard=dashboard;dashboard=function(){let html=beforeSocialDashboard(),favoriteCount=savedFavoritesCount();return html.replace(`<a href="#/saved">შენახული განცხადებები (${saved.length})</a>`,`<a href="#/saved">♡ შენახული განცხადებები${favoriteCount?` (${favoriteCount})`:''}</a>`).replace('<a href="#/profile">პროფილი</a>','<a href="#/messages">💬 შეტყობინებები</a><a href="#/profile">პროფილი და პარამეტრები</a>')};

const beforeSocialDetails=details;details=function(id){let html=beforeSocialDetails(id),j=jobs.find(x=>x.id===id);if(!j)return html;html=html.replace(/<button class="btn btn-primary" data-contact="([^"]+)">დაკავშირება<\/button>/,`<p class="contact-prompt">ტელეფონის ნომრის სანახავად დააჭირე დაკავშირებას.</p><button class="btn btn-primary" data-reveal-job-phone="${esc(j.id)}">დაკავშირება</button>`);html=html.replace('</article>',`<button class="report-link" type="button" data-open-report data-report-type="job" data-report-job="${esc(j.id)}" data-report-user="${esc(j.owner||'')}"><span class="report-link-icon" aria-hidden="true">⋯</span> განცხადების დარეპორტება</button></article>`);return html};

const beforeSocialWorkerDetail=workerDetail;workerDetail=function(id){let html=beforeSocialWorkerDetail(id),w=[...get('dge-workers',[]),...seedWorkers].find(x=>x.id===id);if(!w)return html;const self=!!user?.email&&(w.owner===user.email||w.email===user.email);html=html.replace(new RegExp(`<button class="btn btn-primary" data-worker-contact="${id}">დაკავშირება<\\/button>`),`<p class="contact-prompt">ტელეფონის ნომრის სანახავად დააჭირე დაკავშირებას.</p><button class="btn btn-primary" data-reveal-worker-phone="${esc(id)}">დაკავშირება</button>`);if(!self)html=html.replace('</article>',`<button class="report-link" type="button" data-open-report data-report-type="user" data-report-user="${esc(w.owner||`worker:${w.id}`)}"><span class="report-link-icon" aria-hidden="true">⋯</span> მომხმარებლის დარეპორტება</button></article>`);return html};
const beforePublicProfile=publicUserProfile;publicUserProfile=function(email){let html=beforePublicProfile(email),w=get('dge-workers',[]).find(x=>x.owner===email);if(w){html=html.replace('</section>',`<aside class="profile-box public-contact-box"><h3>დაკავშირება</h3><p class="contact-prompt">ტელეფონის ნომრის სანახავად დააჭირე დაკავშირებას.</p><button class="btn btn-primary" data-reveal-worker-phone="${esc(w.id)}">დაკავშირება</button></aside></section>`)}return html.replace('</section>',`<button class="report-link public-report" type="button" data-open-report data-report-type="user" data-report-user="${esc(email)}"><span class="report-link-icon" aria-hidden="true">⋯</span> მომხმარებლის დარეპორტება</button></section>`)};

function normalizedPhone(phone){return String(phone||'').replace(/[^0-9+]/g,'')}
function revealPhone(button,phone){if(!phone){notify('ტელეფონის ნომერი მითითებული არ არის.');return}const box=document.createElement('div');box.className='revealed-phone';box.innerHTML=`<strong>📞 ${esc(phone)}</strong><a class="btn btn-primary" href="tel:${esc(normalizedPhone(phone))}">დარეკვა</a><button class="btn btn-secondary" type="button" data-copy-phone="${esc(phone)}">ნომრის დაკოპირება</button>`;button.insertAdjacentElement('afterend',box);button.remove()}

const reportReasons=['საეჭვო განცხადება','ყალბი ინფორმაცია','შეურაცხმყოფელი შინაარსი','საეჭვო მომხმარებელი','სხვა'];
function openReport(button){document.querySelector('[data-report-modal]')?.remove();const modal=document.createElement('div');modal.className='modal-backdrop social-modal-backdrop';modal.dataset.reportModal='';modal.innerHTML=`<form class="social-modal report-modal" data-report-form role="dialog" aria-modal="true"><button class="social-modal-close" type="button" data-close-social aria-label="დახურვა"><svg class="social-modal-close-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button><h2>რატომ არ მოგწონს ეს განცხადება?</h2><div class="report-reasons">${reportReasons.map((x,i)=>`<label><input type="radio" name="reason" value="${esc(x)}" ${i===0?'required':''}>${esc(x)}</label>`).join('')}</div><label class="report-description">დამატებითი ინფორმაცია<textarea name="description" placeholder="თუ გსურს, მოგვწერე მეტი დეტალი"></textarea></label><input type="hidden" name="reportedUser" value="${esc(button.dataset.reportUser||'')}"><input type="hidden" name="relatedJob" value="${esc(button.dataset.reportJob||'')}"><input type="hidden" name="reportType" value="${esc(button.dataset.reportType||'job')}"><div data-report-error class="error-msg"></div><button class="btn btn-primary form-submit" type="submit">რეპორტის გაგზავნა</button></form>`;document.body.append(modal)}

function chatName(id,job){if(id.startsWith('poster:'))return job?.name||'განცხადების ავტორი';const profile=get('dge-workers',[]).find(x=>x.owner===id||x.email===id);return get('dge-accounts',[]).find(x=>x.email===id)?.name||profile?.name||userName(id,'მომხმარებელი')}
function chatKey(jobId,a,b){return `${jobId}::${[a,b].sort().join('::')}`}
function availableChats(){if(!user)return[];const rows=new Map(),add=(job,other,name)=>{if(!job||!other||other===user.email)return;const key=chatKey(job.id,user.email,other);rows.set(key,{key,jobId:job.id,jobTitle:job.title,other,otherName:name||chatName(other,job)})};jobs.filter(j=>j.owner===user.email).forEach(j=>applicationsFor(j.id).forEach(a=>add(j,a.email,userName(a.email,'სამუშაოს მაძიებელი'))));applicationsForUser(user.email).forEach(j=>add(j,j.owner||`poster:${j.id}`,j.name));get(chatStoreKey,[]).filter(c=>c.participants?.includes(user.email)).forEach(c=>{const other=c.participants.find(x=>x!==user.email),j=jobs.find(x=>x.id===c.jobId);rows.set(c.key,{key:c.key,jobId:c.jobId,jobTitle:j?.title||c.jobTitle,other,otherName:c.names?.[other]||chatName(other,j)})});return [...rows.values()]}
function messagesPage(){if(!user)return `<section class="container"><div class="empty"><strong>შეტყობინებების სანახავად საჭიროა შესვლა</strong><a class="btn btn-primary btn-small" href="#/login" style="margin-top:12px">შესვლა / რეგისტრაცია</a></div></section>`;const p=new URLSearchParams(location.hash.split('?')[1]||''),jobId=p.get('job')||'',other=p.get('with')||'',job=jobs.find(j=>j.id===jobId),key=jobId&&other?chatKey(jobId,user.email,other):'',chats=get(chatStoreKey,[]);let conv=chats.find(c=>c.key===key);if(job&&other&&!conv)conv={key,jobId,jobTitle:job.title,participants:[user.email,other],names:{[user.email]:user.name,[other]:chatName(other,job)},messages:[]};const list=availableChats(),active=conv;return `<section class="container messages-page"><div class="page-head"><span class="eyebrow">პირადი სივრცე</span><h1>💬 შეტყობინებები</h1><p>განცხადებებსა და განაცხადებთან დაკავშირებული საუბრები.</p></div><div class="messages-layout"><aside class="conversation-list"><h2>საუბრები</h2>${list.length?list.map(c=>`<a class="conversation-link ${active?.key===c.key?'active':''}" href="#/messages?job=${encodeURIComponent(c.jobId)}&with=${encodeURIComponent(c.other)}"><strong>${esc(c.otherName)}</strong><small>${esc(c.jobTitle)}</small></a>`).join(''):'<p class="conversation-empty">საუბრები ჯერ არ გაქვს. განცხადების გვერდიდან შეგიძლია მიწერო.</p>'}</aside><section class="chat-panel">${active?`<div class="chat-heading"><div><strong>${esc(active.otherName||chatName(other,job))}</strong><small>${esc(active.jobTitle||job?.title||'განცხადებასთან დაკავშირებული საუბარი')}</small></div></div><div class="chat-log" id="chatLog">${active.messages.length?active.messages.map(m=>`<div class="chat-message ${m.from===user.email?'mine':''}"><p>${esc(m.text)}</p><small>${new Date(m.createdAt).toLocaleString('ka-GE',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div>`).join(''):'<div class="chat-empty">დაიწყე საუბარი ამ განცხადებასთან დაკავშირებით.</div>'}</div><form class="chat-compose" data-chat-form data-chat-job="${esc(jobId)}" data-chat-with="${esc(other)}"><input name="message" required maxlength="1000" placeholder="დაწერე შეტყობინება..." aria-label="დაწერე შეტყობინება"><button class="btn btn-primary" type="submit">გაგზავნა</button></form>`:'<div class="chat-placeholder">აირჩიე საუბარი სიიდან ან გახსენი განცხადება და მიწერე მის ავტორს.</div>'}</section></div></section>`}

const beforeSocialRoute=routeView;routeView=function(){activateSavedAccount();const path=(location.hash||'#/').split('?')[0];if(path==='#/messages'){app.innerHTML=messagesPage();accountNavigation();refreshSaveButtons();return}beforeSocialRoute();accountNavigation();refreshSaveButtons();const pending=sessionStorage.getItem('dge-pending-save');if(user&&pending){sessionStorage.removeItem('dge-pending-save');if(jobs.some(j=>j.id===pending)&&!saved.includes(pending)){saved.push(pending);persistSaved();refreshSaveButtons(pending);notify('განცხადება შენახულებში დაემატა')}}};render=routeView;routeView();

document.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save){e.preventDefault();e.stopImmediatePropagation();if(!user){saveModal(save.dataset.save);return}const id=save.dataset.save;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];persistSaved();notify(saved.includes(id)?'განცხადება შენახულია':'წაშლა შენახულებიდან');if((location.hash||'').split('?')[0]==='#/saved')routeView();else refreshSaveButtons(id);accountNavigation();return}},true);
function setAccountMenuState(button,panel,open){if(!button||!panel)return;button.setAttribute('aria-expanded',String(open));button.classList.toggle('is-open',open);panel.hidden=!open;panel.classList.toggle('is-open',open)}
document.addEventListener('click',e=>{if(e.target.closest('[data-account-toggle]'))return;if(e.target.closest('[data-save-auth]')){const b=e.target.closest('[data-save-auth]'),modal=b.closest('[data-save-modal]'),id=modal.dataset.job;sessionStorage.setItem('dge-pending-save',id);sessionStorage.setItem('dge-return',`#/job/${encodeURIComponent(id)}`);modal.remove();location.hash=b.dataset.saveAuth==='register'?'#/login?register=1':'#/login';return}if(e.target.closest('[data-close-social]')||e.target.matches('[data-save-modal],[data-report-modal]')){e.target.closest('.modal-backdrop')?.remove();return}const revealWorker=e.target.closest('[data-reveal-worker-phone]');if(revealWorker){const w=[...get('dge-workers',[]),...seedWorkers].find(x=>x.id===revealWorker.dataset.revealWorkerPhone);revealPhone(revealWorker,w?.phone);return}const revealJob=e.target.closest('[data-reveal-job-phone]');if(revealJob){const j=jobs.find(x=>x.id===revealJob.dataset.revealJobPhone);revealPhone(revealJob,j?.phone);return}const copy=e.target.closest('[data-copy-phone]');if(copy){const phone=copy.dataset.copyPhone;const done=()=>notify('ნომერი დაკოპირდა');if(navigator.clipboard?.writeText)navigator.clipboard.writeText(phone).then(done).catch(()=>copyPhoneFallback(phone,done));else copyPhoneFallback(phone,done);return}const report=e.target.closest('[data-open-report]');if(report){openReport(report);return}const startChat=e.target.closest('[data-open-chat]');if(startChat){e.preventDefault();if(!user){sessionStorage.setItem('dge-return',`#/messages?job=${encodeURIComponent(startChat.dataset.openChat)}&with=${encodeURIComponent(startChat.dataset.chatWith)}`);location.hash='#/login';return}location.hash=`#/messages?job=${encodeURIComponent(startChat.dataset.openChat)}&with=${encodeURIComponent(startChat.dataset.chatWith)}`;return}if(e.target.closest('[data-logout]')){setTimeout(()=>{activateSavedAccount();accountNavigation()},0)}});
function copyPhoneFallback(phone,done){const t=document.createElement('textarea');t.value=phone;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();try{document.execCommand('copy');done()}catch{notify('ნომრის დაკოპირება ვერ მოხერხდა')}t.remove()}
document.addEventListener('submit',e=>{const report=e.target.closest('[data-report-form]');if(report){e.preventDefault();const d=new FormData(report),reports=get(reportStoreKey,[]);if(!d.get('reason')){report.querySelector('[data-report-error]').textContent='აირჩიე მიზეზი.';return}reports.push({id:'rep'+Date.now(),reportedUser:d.get('reportedUser')||null,relatedJob:d.get('relatedJob')||null,reason:d.get('reason'),description:(d.get('description')||'').trim(),createdAt:Date.now(),reportingUser:user?.email||null});set(reportStoreKey,reports);report.closest('[data-report-modal]').innerHTML='<section class="social-modal report-success" role="dialog" aria-modal="true"><button class="social-modal-close" type="button" data-close-social aria-label="დახურვა"><svg class="social-modal-close-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button><span class="social-modal-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><path d="m5 12.5 4.3 4.3L19 7.4" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg></span><h2>მადლობა. თქვენი შეტყობინება მიღებულია.</h2><button type="button" class="btn btn-primary" data-close-social>დახურვა</button></section>';return}const form=e.target.closest('[data-chat-form]');if(form){e.preventDefault();if(!user){location.hash='#/login';return}const d=new FormData(form),jobId=form.dataset.chatJob,other=form.dataset.chatWith,text=String(d.get('message')||'').trim(),job=jobs.find(j=>j.id===jobId);if(!text||!other)return;const chats=get(chatStoreKey,[]),key=chatKey(jobId,user.email,other);let conv=chats.find(c=>c.key===key);if(!conv){conv={key,jobId,jobTitle:job?.title||'განცხადება',participants:[user.email,other],names:{[user.email]:user.name,[other]:chatName(other,job)},messages:[]};chats.push(conv)}conv.messages.push({id:'m'+Date.now(),from:user.email,to:other,text,createdAt:Date.now()});set(chatStoreKey,chats);app.innerHTML=messagesPage();accountNavigation();const log=document.getElementById('chatLog');if(log)log.scrollTop=log.scrollHeight;return}});
